### ISSUE TITLE
Deploy a development version of the app to Heroku

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#106]
## Description
As a contributor,
I need to have a development deployed version of the app,
so that I can test the app before releasing a production version.

We want to have this available from a URL on Heroku.

### Update [Required]
- [ ] Make this deployable on Heroku

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
🤷‍♀️ hours

**Comment by isabelcosta** [comment]
I tried this and I did not get this yet. This is not very straight forward.
So I am opening this to anyone else to help.

**Comment by saideepesh000** [comment]
I can try this, I think it should be fairly simple as there is no back-end involved in it.

**Comment by saideepesh000** [comment]
@isabelcosta Can I use my account or is there any account for this project?

**Comment by isabelcosta** [comment]
@saideepesh000 feel free to use your account. We don't have an organization account on Heroku, I use my personal one. I tried before yesterday, and the page did not render the website, so I suspect we have to change something in the code to work with Heroku, I created an extra file `.procfile` I think.

So if you can do it on your own Heroku, then you can help us admins do the same :)

**Comment by saideepesh000** [comment]
@isabelcosta, Okay I'll try

**Comment by saideepesh000** [comment]
@isabelcosta, one doubt regarding the setup, 1. So the develop branch of my repo will be on the Heroku, right? ,2. When someone commits the main repo I need to pull the commits to my develop branch to keep the Heroku app updated, is this how it works?

**Comment by isabelcosta** [comment]
> So the develop branch of my repo will be on the Heroku, right?

Yes, we want the heroku deployment to uses `develop` branch, so we can test it before merging into `production`.
Currently, I think, develop branch is breaking and not building correctly, because when we merged to `production` the build failed.

> When someone commits the main repo I need to pull the commits to my develop branch to keep the Heroku app updated, is this how it works?

Yes, and on Heroku you can setup "Automatic Deploys"

@saideepesh000

**Comment by saideepesh000** [comment]
@isabelcosta,  I tried it on Heroku as you said it's failing, So I tried it on netlify, it worked. There are some warnings in the develop branch of the repo I removed those(on production create-react-app treats these as warnings, I think). If you are Ok with this I can share the process.

[anitab-org develop](https://pedantic-saha-b6acb9.netlify.app)

Warnings
![Screenshot (249)_LI](https://user-images.githubusercontent.com/43727167/88520211-e0ee7700-d010-11ea-86b3-da68349d8527.jpg)

**Comment by isabelcosta** [comment]
For now, netlify is a good option. It's better then nothing, we can figure out later how to use heroku, so we can keep to tools we already use.

If you have to submit a PR with any fix you did please do and refer to this PR. @saideepesh000

**Comment by saideepesh000** [comment]
Okay

**Comment by isabelcosta** [comment]
@saideepesh000 have you tried Heroku, with your fix?

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 have you tried Heroku, with your fix?

No, sorry, Ya would've tried in heroku. Should I?

**Comment by isabelcosta** [comment]
@saideepesh000 yes please :) That would be great!

**Comment by saideepesh000** [comment]
@isabelcosta, it's not deployed in heroku, https://anitab-org.herokuapp.com/

**Comment by saideepesh000** [comment]
@isabelcosta, The PR was closed and develop branch can now be deployed in netlify :)

**Comment by isabelcosta** [comment]
@saideepesh000 thank you for all your work! It was super important to get this issue fixed :) Now the develop branch is being deployed on a specific path 🙌

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 thank you for all your work! It was super important to get this issue fixed :) Now the develop branch is being deployed on a specific path 🙌

Thank you 👍
