### ISSUE TITLE
Bug: renderContent() function was declared two times

### ISSUE THREAD

**Issue by saideepesh000** [anitab-org/anitab-org.github.io#107]
### Describe the bug
In src/Components/Content/index.js, renderContent() function is declared two times.

### To Reproduce
1. Go to [src/Components/Content/index.js](https://github.com/anitab-org/anitab-org.github.io/blob/develop/src/Components/Content/index.js)
3. Scroll down to 'line 32'

### Expected behavior
This block of code should be present only one time

`function renderContent(title) {
  return <Text>{title}</Text>;
}`

### Screenshots
![Screenshot (248)](https://user-images.githubusercontent.com/43727167/88464159-2e19fe00-ced6-11ea-967f-0d362c5f1886.png)

**Comment by saideepesh000** [comment]
Can I do this

**Comment by nandini45** [comment]
u are already working on a issue i cant assign u more than one issue at a time

**Comment by nandini45** [comment]
if u want i can do it for u..

**Comment by saideepesh000** [comment]
@nandini45, I can do this, because with the previous issue I need a response to a question till then I can't start that, meanwhile, I can work on this because I think it's a serious one and needs to be corrected immediately.

**Comment by nandini45** [comment]
@saideepesh000  you want to work on it now?

**Comment by saideepesh000** [comment]
> 
> 
> @saideepesh000 you want to work on it now?

Actually I sent a PR(for deployment) which also fixes this issue, https://github.com/anitab-org/anitab-org.github.io/pull/113

**Comment by saideepesh000** [comment]
If you want to send a PR on this issue, I will do that, please assign me. @nandini45

**Comment by nandini45** [comment]
please revert your commit if you have mixed it with the other issue..
and create a separate PR for it.

**Comment by saideepesh000** [comment]
> 
> 
> please revert your commit if you have mixed it with the other issue..
> and create a separate PR for it.

@nandini45, Before this, I need to confirm with @isabelcosta whether she noted those changes to deploy the site so that she could close the PR.

**Comment by annabauza** [comment]
@saideepesh000 please work on this PR this is a critical issue and need to be solved immediately. I will not deploy anything until this has been resolved. Thanks!
