### ISSUE TITLE
Coding : Develop the following section for Home Page

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/anitab-org.github.io#111]
### Is your feature request related to a problem? Please describe.
As a developer,
I need the following section to be developed so that I can add is as a Home component [here](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components)

### Mocks
Develop this section only

![Screenshot (30)_LI](https://user-images.githubusercontent.com/60894542/88478423-c3b09e80-cf65-11ea-8cb8-b8905ee570c8.jpg)

Font Size for heading : Header Medium(24pt) weight- Medium
Font Size for the description below: body 14pt weight- Light
Font Style- Avenir
Font Color (heading): #103B81
Font Color (Body): #103B81

[Design link for development](https://xd.adobe.com/view/09a9fdf0-a193-4b3f-47c2-216055c7ca42-7f98/)

### Update [Required]
- [ ] Should follow all the margin guidelines mentioned above and should be responsive

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6-8 hours

**Comment by nandini45** [comment]
@anitab-org/coding-team can  anyone take up this issue?

**Comment by RiaDhanani** [comment]
I am new but I would like to work on this issue. Can you asssign it to me please? @nandini45

**Comment by RiaDhanani** [comment]
@vj-codes For the home section that is to be developed, is the whole thing one image or six seperate images and where can I get them?

**Comment by vj-codes** [comment]
@RiaDhanani sorry for the late reply, they are 6 different illustrations and you can find them in the open source drive >>design folder 
https://drive.google.com/drive/folders/1Y_yPuxBUYz0pVkPZ5RdWrs4rxdijdJZ6

**Comment by RiaDhanani** [comment]
@vj-codes @gaurivn @annabauza Could you please review my PR? This is my first PR 😄

**Comment by vj-codes** [comment]
@RiaDhanani sure! 
There's a minor change , the  margins are 32 pt from both sides. Could you update accordingly. Really sorry it was a mistake from my side and forgot to update the issue :)

**Comment by RiaDhanani** [comment]
@vj-codes Made the change. Could you review it?
