### ISSUE TITLE
content: add badge in the README.md

### ISSUE THREAD

**Issue by jivthesh** [anitab-org/anitab-org.github.io#112]
### Description
As a developer,
I need to see the badges symbolising the our communication channel

### Acceptance Criteria
Update [Required]
Add badges

### Definition of Done

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

### Estimation
30 min

**Comment by nandini45** [comment]
@jivthesh  please follow the issue template to create a issue
and i think you mean badges right?

**Comment by jivthesh** [comment]
@nandini45 which template to use

**Comment by jivthesh** [comment]
which template to use

**Comment by nandini45** [comment]
i knw there is not a specific template for it. but still the layout has to be followed.
 should i update it for you?
then you can work on it?

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/88580197-ea0b3280-d068-11ea-9644-aea30f2c0c37.png)
 see such a layout.
 although its for project page you can replace it with readme.

**Comment by isabelcosta** [comment]
@jivthesh you can follow this template: https://github.com/anitab-org/anitab-org.github.io/blob/develop/.github/ISSUE_TEMPLATE/user-story.md

Please be clear in the issue description which badges you are talking about :)

**Comment by jivthesh** [comment]
@nandini45 i can work on it

**Comment by nandini45** [comment]
OK change the issue template and i will assign it to u

**Comment by jivthesh** [comment]
@nandini45 update the issue template and assign me

**Comment by jivthesh** [comment]
@nandini45 updated please check
