### ISSUE TITLE
Missing mentorship-flutter in project_content.js

### ISSUE THREAD

**Issue by Techno-Disaster** [anitab-org/anitab-org.github.io#115]
### Describe the bug
As a developer i want to see all the projects listed on our sit including Mentorship-flutter. I am not sure if this is the only place but i could not find mentorship-flutter in project_content.js file.

### To Reproduce
mentorship flutter is one of our new project, we need to mention that.

### Screenshots
![image](https://user-images.githubusercontent.com/62046625/88840842-b829d580-d1fa-11ea-9924-8808a50c225a.png)
 missing flutter description

### Estimation
30 min

**Comment by nandini45** [comment]
@Techno-Disaster  can you edit the issue template you followed?

**Comment by nandini45** [comment]
i will like to work on it?

**Comment by annabauza** [comment]
Thank you @Techno-Disaster for catching this. We will add    :)

**Comment by nandini45** [comment]
@Techno-Disaster  can i work on it?

**Comment by Akanksha1212** [comment]
You can take this up @nandini45
