### ISSUE TITLE
Create a Contribution Guidelines markdown file

### ISSUE THREAD

**Issue by sidvenu** [anitab-org/anitab-org.github.io#12]
## Description
As a developer,
I need to see contributing guidelines,
so that I can contribute effectively.

### Update [Required]
- [ ] Create a Contribution Guidelines markdown file. Reference: https://github.com/anitab-org/mentorship-android/blob/develop/.github/CONTRIBUTING.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by annabauza** [comment]
approved!

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by mayburgos** [comment]
@gaurivn Go ahead! :) I've assigned it to you.
