### ISSUE TITLE
coding: make cards and develop the event section in event page

### ISSUE THREAD

**Issue by nandini45** [anitab-org/anitab-org.github.io#123]
## Description
As a user,i need to know about the events that take place in the community,
so that I can be a part of them.

## Mocks
![image](https://user-images.githubusercontent.com/62046625/89105047-91a6ad00-d43b-11ea-9c80-52e603800b6e.png)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 7 hours

**Comment by nandini45** [comment]
@sonal420 can u tell me the marking of this section

**Comment by Sonal240** [comment]
The overall margin of the card -16pt
EVENT TITLE top margin- 16pt
icon- 32 X 32
the margin between icon and text along it-16pt
the margin between EVENTS TIMINGS, LOCATION, AND DATE thing- 16pt
the top margin of lorem ipsum text description and EVENTS TIMING- 32pt
the top margin of Know More from description-32pt

**Comment by Sonal240** [comment]
the rest of the colors are same as doc

**Comment by dwvicy** [comment]
Can I work on this?

**Comment by nandini45** [comment]
@dwvicy  sure i will assign it to u

**Comment by nandini45** [comment]
sorry i didnt see you were working on other issue..
 you can work on it after you complete merge that one

**Comment by dwvicy** [comment]
@nandini45 I've already submitted the pull request for the other issue

**Comment by nandini45** [comment]
ahh ok @dwvicy  here you go
the web metric are given in the comment box by simran'
feel free to ask any query..

**Comment by 19-pragya** [comment]
Can i work on this issue

**Comment by nandini45** [comment]
@19-pragya it is already taken please look for any other issue, sorry for the mistake

**Comment by dwvicy** [comment]
@nandini45 just an update as it's been quite long, I am halfway through. Would be submitting the PR in a couple of days!

**Comment by nandini45** [comment]
yeah thanks for the update.
i literally forgot to ask for the update

**Comment by shravani05** [comment]
Is this issue still open?
I am interested in taking this issue

**Comment by shravani05** [comment]
Is this issue still available?
I would like to work on this issue

**Comment by dwvicy** [comment]
@shravani05 I am working on it got carried away with other work.

**Comment by shravani05** [comment]
Okay, no problem :)

**Comment by annabauza** [comment]
there is a card decorator, please use it @shravani05

**Comment by nandini45** [comment]
@dwvicy  any updates?

**Comment by dwvicy** [comment]
Would need like a couple more days at max! I'm extremely sorry for the delay :(

**Comment by dwvicy** [comment]
I'm having some compiling issues after pulling the latest code.

**Comment by dwvicy** [comment]
> the rest of the colors are the same as doc, discussed by doc by Anna

where can I find this doc? I need to change the colors

**Comment by nandini45** [comment]
colors for what exactly?
cards have color hex #E2EAF2

**Comment by Akanksha1212** [comment]
Hi @dwvicy, Any updates on work? Let us know if you need any help

**Comment by dwvicy** [comment]
@Akanksha1212 Thanks for asking, actually I switched laptops and lost all the local changes due to screen damage. I'll give you an update by tomorrow EOD.

**Comment by parthsarthiprasad** [comment]
@nandini45 is the top bar a progress bar?
![image](https://user-images.githubusercontent.com/44730599/96850945-0dc9f300-1475-11eb-9ff6-87a01b25f81a.png)
Something like :
![progressbar](https://user-images.githubusercontent.com/44730599/96851122-4cf84400-1475-11eb-86b8-109b863f72a5.gif)

**Comment by Vuyanzi** [comment]
@nandini45 can I kindly be assigned to this.

**Comment by Akanksha1212** [comment]
Sure @Vuyanzi

**Comment by nandini45** [comment]
@Vuyanzi  are you working on it? if yes can you give us updates on the progress you made so far

**Comment by Bucky25** [comment]
@nandini45 i would like to work on it

**Comment by nandini45** [comment]
@Bucky25 ok i will assign it to u.
Keep giving us the update of ur work after 3 4 days .

**Comment by Bucky25** [comment]
@nandini45 how do we have to attach icons of date, location and time .
is it through material or font-awesome

**Comment by Bucky25** [comment]
@nandini45 event and highlight section is ready would sent a pr by tomorrow some questions.
1) i have changed events_and_highlights.json file to to js file and some more changes in objects but no change in data  will it be fine  .
2) is the know more part in card should be click able ? i have made it .

**Comment by nandini45** [comment]
@Bucky25  yes know more part should be clickable.. 
As far as for Changing the file structure i think that is an issue..but let me ask the admin first..i will get back to u.
Btw did u attach the icons??

**Comment by Bucky25** [comment]
@nandini45 for the file structure i have changed as of projects and abt icons should i download it put in assets/events_and_highlights folder then use it ?

**Comment by Bucky25** [comment]
can i send a pr i have completed my work and looking for feedback and suggested changes 
![Screenshot from 2020-12-01 19-01-08](https://user-images.githubusercontent.com/65112369/100747380-fbde5700-3407-11eb-845e-5561f5422f2e.png)
![Screenshot from 2020-12-01 19-03-26](https://user-images.githubusercontent.com/65112369/100747384-fda81a80-3407-11eb-8b0b-f7f9093414a1.png)

**Comment by Bucky25** [comment]
@nandini45  @annabauza can you please provide me icons of calendar and clock which as given in design page

**Comment by annabauza** [comment]
@vj-codes @Vuyanzi @Sonal240 @simranaggarwal1999, can any of you please provide proper icons?

**Comment by Sonal240** [comment]
@annabauza @Bucky25  those are just pngs downloaded from material design site... I recently got my laptop formatted so I don't have them with me as of now...try looking for it else I'll provide it by tomorrow... Thanks

**Comment by parthsarthiprasad** [comment]
@Sonal240 I'd suggest @Bucky25 can try normal fa-icons, and scale them accordingly, fa-calendar, fa-map-marker etc will work fine?

**Comment by Sonal240** [comment]
Ya sure but I think we are following material guidelines so I think it's better to go with material design icons... @annabauza would be the right person to answer this fact

**Comment by Bucky25** [comment]
@Sonal240  @parthsarthiprasad  thanks guys for the suggestions . I will try material icons and let you know if any problem
