### ISSUE TITLE
Zulip badge links to design stream instead of the project's stream

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#126]
## Description

Change the zulip badge link on the README to the anitab-oorg.github.io stream on Zulip

### Update [Required]
- [ ] Change the link of the zulip badge to the link of this project's stream

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 min

**Comment by dwvicy** [comment]
@isabelcosta can I work on this?

**Comment by isabelcosta** [comment]
Sure it's assigned to you :)

**Comment by 19-pragya** [comment]
can i work on this issue

**Comment by yerramsettysaimeghana** [comment]
Can I work on this issue ?

**Comment by vj-codes** [comment]
Sorry @yerramsettysaimeghana @19-pragya this issue has already been claimed and a PR has been sent.
[Here](https://github.com/anitab-org/anitab-org.github.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22Status%3A+Available%22) are a few available issues!
