### ISSUE TITLE
Code: Update the Footer Color

### ISSUE THREAD

**Issue by sakshi1499** [anitab-org/anitab-org.github.io#130]
### Is your feature request related to a problem? Please describe.
The footer color has to be changed so that it follows the AnitaB Color Guidelines.

### Describe the solution you'd like
The existing color code should be changed to #231b4e. 
The footer color inspiration has been taken from [GHC](https://ghc.anitab.org/speakers/)

**Comment by adithyaakrishna** [comment]
Can I claim this issue and work on it?😊

**Comment by vj-codes** [comment]
Sure assigning you @adithyaakrishna 
Happy coding!

**Comment by adithyaakrishna** [comment]
Thank you! :)

**Comment by nandini45** [comment]
@sakshi1499
we are not updating the footer color. we have to redesign it whole.
