### ISSUE TITLE
Create the config.yml file for the Welcome Bot

### ISSUE THREAD

**Issue by Frenzyritz13** [anitab-org/anitab-org.github.io#131]
## Description
 As a first time contributor,
 I need a bot to help guide my first contribution,
 so that I can follow this org's contribution guidelines.
 
 ## Mocks
 ![Screen Shot 2020-08-06 at 10 26 14 AM](https://user-images.githubusercontent.com/2440938/89543720-44299780-d7cf-11ea-82a0-bd81664f0d8e.png)
 
 ## Acceptance Criteria
 ### Update [Required]
 * [ ]  newIssueWelcomeComment is complete with the correct links to this repo.
 * [ ]  newPRWelcomeComment is complete with the links to the project's stream or topic and the repo's Code of Conduct.
 * [ ]  firstPRMergeComment is complete.
 
 ## Definition of Done
 * [ ]  All of the required items are completed.
 * [ ]  Approval by 1 mentor.
 
 ## Estimation
 0.5 hours

**Comment by adithyaakrishna** [comment]
This commit added a config.yml file for the welcome bot as requested in Issue #131
The file is placed in .github directory to allow for easier installation and setup of the Welcome-Bot :)

**Comment by adithyaakrishna** [comment]
My bad, Should have claimed this issue first. Sorry for that

**Comment by vj-codes** [comment]
@adithyaakrishna Assigned it to you , please don't send PRs until a specific issue is assigned to you from next time!

**Comment by adithyaakrishna** [comment]
Yeah, sure will keep that in mind :)

**Comment by nandini45** [comment]
@adithyaakrishna  you are already working on another issue. i have to unassign you from this.

**Comment by Aaishpra** [comment]
@nandini45 can i take this up if no one is working on it currently?

**Comment by adithyaakrishna** [comment]
Hey, sorry for the delay and @Aaishpra I've finished creating the file but had forgot to push the changes, my bad :/ @nandini45, Can I push those changes seperately?

**Comment by nandini45** [comment]
did you merge the issue with other issue and openend a PR? @adithyaakrishna

**Comment by adithyaakrishna** [comment]
Yeah, had done that but Anna told me not to do that and create another one so Ig she had deleted the commit

**Comment by nandini45** [comment]
@adithyaakrishna  Yes you have to open two separates PR for both the issues you are working on.

**Comment by adithyaakrishna** [comment]
Okayy, got it. So can I create another pull request now

**Comment by nandini45** [comment]
yes

**Comment by nandini45** [comment]
any updates?? it is your pending work?

**Comment by adithyaakrishna** [comment]
@nandini45  Yess, I've created the pull request, Do lmk if any changes are needed :)
