### ISSUE TITLE
Bug: Wrong Tech Stack on BridgeInTech Web and Backend

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/anitab-org.github.io#136]
### Describe the bug
The Tech stack mentioned in the BridgeInTech Web and Backend are wrong

### To Reproduce
1. Go to browser anitab-org.github.io
2. See tech stack on Bridge-In-Tech Web as javascript
3. See tech stack on Bridge-In-Tech Backend as react ja and python

### Expected behavior
Bridge-In-Tech Web tech stack supposed to be: react js
Bridge-In-Tech Backend tech stach supposed to be: python, flask, sqlalchemy and postgresql

### Screenshots
<img width="324" alt="Screen Shot 2020-08-31 at 8 55 16 pm" src="https://user-images.githubusercontent.com/29667122/91713022-4b747300-ebcc-11ea-905f-e0c5d744c64b.png">

### Desktop (please complete the following information):
 - OS: MacOs
 - Browser: Chrome
 - Version ??

**Comment by mtreacy002** [comment]
@annabauza, can you please assign this issue to me? I'd like to give it a try 😊

**Comment by annabauza** [comment]
Thanks you @mtreacy002 we don't need issue for that it was from my pr 🤗 so it's not live.

**Comment by mtreacy002** [comment]
aa...I see.... Ok, no worries then... maybee next time... 😂😂😂. Will clost the issue now. 👍
