### ISSUE TITLE
Content: Add more information to Bridge-In-Tech web and backend project 

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/anitab-org.github.io#137]
## Description
As a project initiator,
I need add more information to Bridge-In-Tech web and backend project description,
so that I can make sure the descrription captures the concept of the project.

## Mocks
NA

### Update [Required]
- [ ] update the desccription for Bridge-In-Tech web and backend

### Enhancement to Update [Optional]
NA

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by mtreacy002** [comment]
@annabauza, Is iit ok for me to open this issue on this? Plus, I'd like to work on it so can I please be assigned to this? Thanks

**Comment by annabauza** [comment]
Sure.

**Comment by mtreacy002** [comment]
Ok. Will start working on it 😉
