### ISSUE TITLE
docs: Update wiki with guidelines on how to deploy a fork to GitHub Pages

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/anitab-org.github.io#139]
## Description
As a developer,
I need to update the wiki with guidelines on how to deploy a fork to GitHub pages,
so that it would aid contributors in doing the same.

## Mocks
[INSERT RELEVANT PNG FILE]

### Update [Required]
- [ ] Update wiki with guidelines on how to deploy a fork to GitHub Pages

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by shravani05** [comment]
Can I work on this issue?

**Comment by gaurivn** [comment]
Hi @shravani05, this issue is currently not available to others since it requires edit access for the wiki.

**Comment by shravani05** [comment]
Okay, no problem
Thank you!

**Comment by Akanksha1212** [comment]
Hi, @gaurivn @nandini45 I've updated the steps on the doc. Have a look and suggest changes.

**Comment by Akanksha1212** [comment]
Closing this as discussed in website open session.
