### ISSUE TITLE
Add project information to the readme file.

### ISSUE THREAD

**Issue by abha224** [anitab-org/anitab-org.github.io#14]
## Description
As a contributor,
I need to understand what the project is about,
so that I can contribute to it.

Since it is the first version of the README, it could probably include:

- description of the website (2-3 sentences)
- Contributing (links to contributing docs, code of conduct, etc)
- contact (e.g.: Zulip link )
- License (reference to license file)

### Update [Required]
- [x] README.md 

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
30 mins

**Comment by annabauza** [comment]
Aprroved

**Comment by mayburgos** [comment]
@abha224 In the future, please make sure to comment on this task "I'd like to work on this issue." Sometimes people open issues and leave it for other contributors to work on. :) It just lets us know you want to be the person who is assigned to the task.

**Comment by abha224** [comment]
Sorry, my bad. Will keep this in mind! :)

**Comment by isabelcosta** [comment]
this was done through #15 
cc @annabauza
