### ISSUE TITLE
Coding: Create a responsive Navbar

### ISSUE THREAD

**Issue by tichnas** [anitab-org/anitab-org.github.io#174]
### Is your feature request related to a problem? Please describe.
Currently, on small screens, the navbar is still of full width (greater than device width) to accommodate everything because of which full navbar is not visible.
![image](https://user-images.githubusercontent.com/56799401/101652156-e8fcff80-3a63-11eb-8793-29c4c24ba0a5.png)

### Describe the solution you'd like
A possible solution would be to change the navbar to a vertically collapsible navbar like
![image](https://user-images.githubusercontent.com/56799401/101652217-00d48380-3a64-11eb-94cc-405aa126831d.png)

### Additional context
Refer https://tichnas.github.io/ (on smaller screens) to get an idea of what type of navbar I'm saying.

**Comment by tichnas** [comment]
@prabhat04011998 Please comment here if you're interested in taking up this issue.

**Comment by prabhat04011998** [comment]
Yes you can assign this to me .@tichnas i am intrerested.

**Comment by tichnas** [comment]
@nandini45 Please approve this issue and assign @prabhat04011998

**Comment by nandini45** [comment]
@tichnas ok.. i approved it and assigned it.
But can you add few screenshots of what it is and what we are trying to do in the description of the jssue??

**Comment by alpha2320** [comment]
@nandini45  can i work on this ?

**Comment by nandini45** [comment]
@prabhat04011998  are u working on it? or you have opened one PR for both the related issues?

**Comment by prabhat04011998** [comment]
@nandini45 yes i am working over it and i have'nt generated PR yet , i am just waiting for other issues to be resolved,after that i'll generate for this issues else this issue will also create problem.

**Comment by nandini45** [comment]
@prabhat04011998  any updates??

**Comment by prabhat04011998** [comment]
Hey @nandini45  ,
I hope you must be doing well.
Apologies for the delay. I was busy with traveling for my work, 
Please can I take two more days?

**Comment by annabauza** [comment]
2 more days, then we reassign if not ready.

**Comment by sanjay270899** [comment]
@annabauza Can I work on this issue?

**Comment by chinmaym07** [comment]
Hey @annabauza  If this issue is available .. Can I work on this issue. ?

**Comment by annabauza** [comment]
@prabhat04011998 have you finished this task?

**Comment by chinmaym07** [comment]
@annabauza is this issue available .?

**Comment by annabauza** [comment]
I'm releasing this issue to the public due to no response.

**Comment by sanjay270899** [comment]
@annabauza I have implemented Responsive NavBar in my local machine for this project. Should I send PR?

**Comment by sanjay270899** [comment]
![image](https://user-images.githubusercontent.com/43892590/106498606-89602500-64e5-11eb-9dc2-8f97bc62d9b4.png)

**Comment by Rahulm2310** [comment]
@sanjay270899 Please request the maintainer to assign the issue to you before starting working on it. This way both you and the community will be benifitted. Thanks 🙂

**Comment by sanjay270899** [comment]
Ok Thanks @Rahulm2310.

I own how open source works. I just find this issue interesting and I solved this. Then, later I decided that let's contribute my solution. (It was not like that I have started working on this for contribution. Later I changed my mind.)

I hope you got the thing what I am trying to say. 🙂

**Comment by sanjay270899** [comment]
@annabauza @nandini45 
I would Like to work on this issue. Can you assign me this issue?

**Comment by annabauza** [comment]
@sanjay270899 I need to close that issue as other contributor is moving navigation to react js
