### ISSUE TITLE
Improper display of contact us section details

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/anitab-org.github.io#175]
### Describe the bug
The content present in contact us section is not properly displayed.

### To Reproduce
1. Go to Landing page
2. Scroll down to 'Bottom
3. See error

### Expected behavior
Contact us section details must be properly displayed for better user experience.
### Screenshots
![Screenshot (2)](https://user-images.githubusercontent.com/56120084/101493040-87696200-398b-11eb-8a12-32db92944eff.png)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser Brave

**Comment by nlok5923** [comment]
@nandini45 please review this issue .

**Comment by tichnas** [comment]
@nlok5923 Sorry, I didn't get what exactly is the issue... Also, what solution do you propose?

**Comment by nlok5923** [comment]
@tichnas  The details in the contact us section is not properly formatted as well as they should be concise and clear.
![Screenshot (8)](https://user-images.githubusercontent.com/56120084/101508092-45e1b280-399d-11eb-9317-3b8c14d4fd5d.png)
Solution: To make each point more smaller, clear and concise and to display it in a list format.

**Comment by Bucky25** [comment]
@nlok5923 the redesign of contact us page is still ongoing and the issue is already there
