### ISSUE TITLE
Coding : Develop Dark-Mode for community website

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/anitab-org.github.io#179]
### Is your feature request related to a problem? Please describe.
No. It's not related to a problem .But it's an additional feature as almost every web-app today has a dark-mode feature.

### Describe the solution you'd like
To Implement Dark-Mode 

If it's a valid feature .Please assign this to me .

**Comment by nandini45** [comment]
@chinmaym07  it is a valid feature. we do want to include but its a future work.
for now we don't need that
 we need to work on the website for now.
you can look for issues in the repositories
