### ISSUE TITLE
Fix Pull Request Template

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/anitab-org.github.io#18]
### Describe the bug
While attempting to create a new pull request, the pull request template does not get preloaded as it does in the other repositories.

### To Reproduce
1. Go to 'Pull Requests'
2. Click on 'New pull request'
3. Select base and head or fork
4. See error 'Pull request template isn't loaded in the PR box'

### Expected behavior
Pull request template is preloaded when contributor clicks new pull request

**Comment by gaurivn** [comment]
@mayburgos , @annabauza , I would like to work on this issue if it gets approved.

**Comment by mayburgos** [comment]
@gaurivn Do you know why that's happening? I'm thinking it's because we haven't merged the issue templates into the `master` branch.

**Comment by gaurivn** [comment]
Yes @mayburgos , it is probably due to the .md file being placed inside PULL_REQUEST_TEMPLATE folder. Instead it should be placed in .github itself. Ma'am, the same issue was there in mentorship-flutter repo too and I saw how it got solved. Please check [here](https://stackoverflow.com/questions/52139192/github-pull-requests-template-not-showing/52139815).

**Comment by mayburgos** [comment]
@gaurivn Thank you! I researched it as well. Please follow [this format](https://github.com/anitab-org/mentorship-android/tree/develop/.github) and make sure the .md file is all CAPS. 

I've assigned you to the task.

**Comment by gaurivn** [comment]
You are welcome @mayburgos . Thank you Ma'am, I will do accordingly.
