### ISSUE TITLE
Re-style the footer

### ISSUE THREAD

**Issue by arnoob16** [anitab-org/anitab-org.github.io#184]
## Description
As a user, I feel the footer is too complicated looking with the links, stream names etc. I feel it would be better if the text is left aligned, which will make it a lot readable than it is now. Highlighting the links/stream names with a different color and using anchor tags to wrap up the complex looking URLs would make it look better.

I also saw the issue #165 but I don't think a separate page is required "just" for the details mentioned in the footer.

## Sample Screenshot - 
![image](https://user-images.githubusercontent.com/49037005/103075326-60e53100-45f1-11eb-8793-d110d2eb41fa.png)

**Comment by nandini45** [comment]
@arnoob16  we are not planning for a separate or any other things. 
We just  need to redesign the footer for all the pages and then code it. 
I said it there and i will repeat if you want to work on it give us the design of how the footer will look like . What content will it have etc

**Comment by tirlochanarora16** [comment]
Can I also submit a proposed design for the footer?

**Comment by annabauza** [comment]
Yes footer is indeed too big. we need to adjust the content there. I think designs were way smaller originally, but content team has created too long text. We need add contact us with e-mail pointing to open-source@anitab.org and also link to zulip. We can add link to github. Best would be use only icons, I think.

**Comment by tirlochanarora16** [comment]
@annabauza , can you please tell the site on which all these changes have to be made?

**Comment by annabauza** [comment]
Can @anitab-org/design-team prepare better designs for this issue please?

**Comment by vj-codes** [comment]
@annabauza yes I would like to, shall I send the link here when I'm done or will it be reviewed in design open session?

**Comment by nandini45** [comment]
@annabauza the issue #165 is related to the same topic that this issue is meant for.
Bcoz the other one was opened 1st 
Therefore i am closing this one.
@arnoob16 if u want to work on it. U can comment there. I can assign u when the design is finalised.
@vj-codes when the design is finalised please mention the link in the #165 issue. And thereby we can assign it further to the required person

**Comment by annabauza** [comment]
@vj-codes yours, remember what we talked about on design session. Just icons + mail icon which opens mail client app.
