### ISSUE TITLE
Same description in Google Summer of Code and Google Code in Section

### ISSUE THREAD

**Issue by avinal** [anitab-org/anitab-org.github.io#190]
### Describe the bug
The introductory description under Google Summer of Code and Google Code-in is the same, even the name of the event has not been changed.

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Scroll down to **Open Source Programs**
3. See error

### Expected behavior
Different description of different programs

### Screenshots
![image](https://user-images.githubusercontent.com/74113200/103506240-3d887480-4e82-11eb-9f48-fe1f50b097ec.png)

**Comment by jalajcodes** [comment]
I think hanging the Program name in the second point should do it, as the years differ in both points? @annabauza 

On that note, maybe a line gap between the point heading and text will make everything more readable

**Comment by Manav1** [comment]
Can I work on the issue?

**Comment by nandini45** [comment]
@avinal It's a v minute issue.. do u want to do the changes or i should assign it to other person ?

**Comment by jalajcodes** [comment]
@nandini45 If no one is available assign it to me

**Comment by avinal** [comment]
Hello @nandini45, I am little occupied now a days so, please feel free to assign it to someone. Sorry I didn't tell earlier. Thanks 😅

**Comment by nandini45** [comment]
@jalajcodes here you go.. u can work on it.. and do give us your update if the work  time exceed 3 days..
Happy coding!!

**Comment by jalajcodes** [comment]
@nandini45 can you please review the pr
