### ISSUE TITLE
Documentation needs text formatting for better readability 

### ISSUE THREAD

**Issue by zyberg2091** [anitab-org/anitab-org.github.io#192]
### Describe the bug
There is a need for line break in between subtopic heading and points. This should be done on the home webpage.

### To Reproduce

Line breaks are needed at several places

1.
Now :
![image 1](https://user-images.githubusercontent.com/42847318/104100098-07545600-52c3-11eb-82a5-d5253685cf5b.png)

After:
![image 4](https://user-images.githubusercontent.com/42847318/104103209-eb52b380-52c6-11eb-9c2f-5a596e4a977a.png)

2.
Now:
![image 2](https://user-images.githubusercontent.com/42847318/104102068-9f523f80-52c3-11eb-92d5-2be3afd0177b.png)

After:
![image 5](https://user-images.githubusercontent.com/42847318/104103259-2228c980-52c7-11eb-82aa-a3432cd9b668.png)

3.
Now:
![image 3](https://user-images.githubusercontent.com/42847318/104103294-4b495a00-52c7-11eb-84eb-01fb089a0947.png)

After:
![image 6](https://user-images.githubusercontent.com/42847318/104103350-9c594e00-52c7-11eb-88fb-1b4051b72b6b.png)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser : Chrome
    Version : Latest

**Comment by nandini45** [comment]
@annabauza do u approve of this issue??

**Comment by annabauza** [comment]
Yes approved

**Comment by Amulya-coder** [comment]
@annabauza can I work on this issue.

**Comment by annabauza** [comment]
Yours @Amulya-coder

**Comment by nandini45** [comment]
@Amulya-coder i am so sorry 
The PR has been opened for this issue Already.
There is a content issue  if u want i can assign u that

**Comment by nandini45** [comment]
@annabauza i apologize for not informing u earlier but the person who made the issue already opened a PR .. i think it will be better if  his PR  is considered and merged

**Comment by nandini45** [comment]
@zyberg2091  @Amulya-coder  can you mention the link to your Pull request
 if not there i will unassign you from the work
