### ISSUE TITLE
TITLE 2 instead of proper title in events tab

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#199]
### Describe the bug

Events tab has placeholder text "TITLE 2" instead of proper title.

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Click on events
3. See there is `TITLE 2`

### Expected behavior
There should be a proper title

### Screenshots
![Screenshot 2021-01-25 at 20 24 40](https://user-images.githubusercontent.com/31966073/105761737-649b0900-5f4b-11eb-8ed3-c2ed3c2b8c13.png)

### Desktop (please complete the following information):
 - OS: any
 - Browser any
 - Version any

### Smartphone (please complete the following information):
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Comment by Amulya-coder** [comment]
@annabauza I would like to take up this issue but I have a one doubt that in Title2 the description is same as Events so on what basis I would decide the title

**Comment by annabauza** [comment]
Yours @Amulya-coder

**Comment by shades-7** [comment]
@annabauza can I work on it?
