### ISSUE TITLE
Spell Checking errors in Documentation                 

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/anitab-org.github.io#200]
### Describe the bug
There will be some Spelling errors in documentation on events tab page

### To Reproduce
1. Go to ' https://anitab-org.github.io/'
2. Click on ' events'
3. See on Events and TITLE 2 content the first , second line and last line contain errors.

### Expected behavior
There should be correct Spelled words.

### Screenshots
![Bug_Anita_B](https://user-images.githubusercontent.com/66437295/105848195-a8057e00-6004-11eb-937d-7ff5a8d03e3d.png)

### Desktop (please complete the following information):
 - OS: any
 - Browser: any
 - Version: any

### Smartphone (please complete the following information):
 - Device: any
 - OS: any
 - Browser: any
 - Version: any

**Comment by Amulya-coder** [comment]
@annabauza please approve this issue and assign it to me

**Comment by Amulya-coder** [comment]
@isabelcosta can you please verify this issue.

**Comment by isabelcosta** [comment]
Oh I didn't check this, sorry. I already assigned a similar issue to someone else. I will assign this to you, the other contributor can fix the other typos you did not mention here :)

**Comment by isabelcosta** [comment]
Oh I noticed you already have a PR in review process, I will close this issue and reference in the other that is a little bit more complete @Amulya-coder

**Comment by isabelcosta** [comment]
This is the predecessor of https://github.com/anitab-org/anitab-org.github.io/issues/203
