### ISSUE TITLE
Add our Medium publication to the website

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#201]
## Description
As a visitor of the website,
I need know where I can find more information about the community, such as the Medium publication,
so that I can learn more about the community through community blog posts.

Blog at https://medium.com/anitab-org-open-source

### Update [Required]
- [ ] If possible add the Medium publication to the project

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by nlok5923** [comment]
Please assign this to me

**Comment by anushruti11** [comment]
Can I take up this issue?

**Comment by annabauza** [comment]
since @nlok5923 was first, I'm assigning this issue to @nlok5923.

**Comment by isabelcosta** [comment]
Is it possible to adds the medium icon with the link to the publication? In terms of design and space on footer. I should have been more clear in the ticket @annabauza

**Comment by annabauza** [comment]
I think this should be new issue to add it to follow us in footer. Great idea @isabelcosta !
