### ISSUE TITLE
Grammatical Errors

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/anitab-org.github.io#203]
### Describe the bug
There are a few grammatical errors in the `home` , `Projects`  and `About Us` page description.

### To Reproduce
1. Go to https://anitab-org.github.io
3. See errors in the descriptions

### Expected behavior
All the grammatical errors needs to be fixed.

### Screenshots
Home Page
![osp-grammar1](https://user-images.githubusercontent.com/54268438/106031339-293c3e00-60f5-11eb-96f3-72da06cd8469.JPG)
![osp-grammar2](https://user-images.githubusercontent.com/54268438/106031348-2c372e80-60f5-11eb-834b-92d2f4f717ff.JPG)
![osp-grammar3](https://user-images.githubusercontent.com/54268438/106031354-2d685b80-60f5-11eb-9b18-87d5a7345444.JPG)

Projects
![osp-grammar4](https://user-images.githubusercontent.com/54268438/106031357-2e998880-60f5-11eb-963f-7f6a0a9ccea5.JPG)

About Us
![osp-grammar5](https://user-images.githubusercontent.com/54268438/106031649-833d0380-60f5-11eb-88ee-24de44f57404.JPG)

Events
![grmtical-issue](https://user-images.githubusercontent.com/54268438/106190479-b9e74c80-61cf-11eb-8c61-b2299865eebf.JPG)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome 
 - Version : 84

**Comment by Rahulm2310** [comment]
@isabelcosta Please confirm this issue and if valid please assign me. Thanks 🙂

**Comment by isabelcosta** [comment]
@Rahulm2310 very good catch! 👏 🎉 I will assign to you :)
