### ISSUE TITLE
adding content to README.md

### ISSUE THREAD

**Issue by nandini45** [anitab-org/anitab-org.github.io#21]
###Description
As a user who doesn't know what this repository is about. So In the readme i can add a little more detail like what this repo is about and if you want to learn more mention all the links

### Describe the solution you'd like
A detailed description in the README.md section.

**Comment by nandini45** [comment]
i would like to work on it too

**Comment by mayburgos** [comment]
@nandini45 How is this different than issue #14 ?

**Comment by nandini45** [comment]
i think it is the same. i will close it.
