### ISSUE TITLE
feat: adding an editorconfig file to project

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/anitab-org.github.io#210]
### Is your feature request related to a problem? Please describe.
Editor  config file will help to maintain the standard code formatting throughout the project style which will eventually leads to better code readability

### Describe the solution you'd like
Adding .editorconfig file considering the best code standards for the project.

### Describe alternatives you've considered
This feature do not have any alternative adding an editorconfig file

### Additional context
Choosing code standards in such a way that should make code readable and easy to understand.

**Comment by nlok5923** [comment]
@annabauza @isabelcosta what's your views over it 🤔

**Comment by annabauza** [comment]
good call, I think someone was already working on code standards, can you review issues and wiki to make sure we have no clash @nlok5923 ?

**Comment by nlok5923** [comment]
Sure @annabauza

**Comment by nlok5923** [comment]
@annabauza i reviewed issues and find no one working on code standards.

**Comment by annabauza** [comment]
Great then it's approved

**Comment by nlok5923** [comment]
@annabauza   Shall I create a pr for it considering standard code format needed for react native project.

**Comment by annabauza** [comment]
I think you are assigned to other issue atm. @nlok5923

**Comment by nlok5923** [comment]
@annabauza please can you add appropriate labels to this issue so that interested contributor may know about it.

**Comment by nandini45** [comment]
@nlok5923  i will make it a beginners issue.
 and i think edit the issue description as per the community instructions.

**Comment by nandini45** [comment]
@nlok5923  ???

**Comment by nlok5923** [comment]
@nandini45 extremely sorry for late response i had edited the issue description please review it.

**Comment by nandini45** [comment]
@nlok5923 no issue .
 are u working on it? or i can make it available for newcomers?

**Comment by nlok5923** [comment]
Yea @nandini45  I am working on it.
