### ISSUE TITLE
Add 'react.js' tag to Open Source Programs Web in Projects page

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/anitab-org.github.io#211]
### Describe the bug
Currently there is no  `react.js` tag on the Open Source Programs Web project under Projects page.

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Scroll down to Open Source Programs Web

### Expected behavior
There should be a `react.js` tag for Open Source Programs Web project.

### Screenshots
![anitab-tag-issue](https://user-images.githubusercontent.com/54268438/106363812-d363d200-6350-11eb-993c-ba47dfd15e4f.JPG)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser: Chrome
 - Version : 88.0.4324.104

**Comment by annabauza** [comment]
💯  approved!

**Comment by prathameshbhalekar** [comment]
I'm new here, can i work on it?

**Comment by aindrila2412** [comment]
I use macOSx . Am I eligible to contribute?

**Comment by annabauza** [comment]
> I'm new here, can i work on it?

Yours!

**Comment by annabauza** [comment]
> I use macOSx . Am I eligible to contribute?

I'm working on mac os too 💪

**Comment by aindrila2412** [comment]
> > I use macOSx . Am I eligible to contribute?
> 
> I'm working on mac os too 💪

Then I want to contribute to this

**Comment by Rahulm2310** [comment]
@aindrila2412 Sorry, but @prathameshbhalekar was the first to claim this issue. Please have a look at some other available issues. Thanks 🙂
