### ISSUE TITLE
Fix programs timeline data to real events

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#212]
### Describe the bug
Current Programs timeline show random data. Setup only GSoC 21 real timeline dates for now.

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Click on Programs
3. See programs display dummy data

### Expected behavior
Proper data should be displayed on timeline

### Screenshots
<img width="1473" alt="Screenshot 2021-01-31 at 12 17 17" src="https://user-images.githubusercontent.com/31966073/106383496-566f4180-63be-11eb-8938-10b47e1b45cb.png">

### Desktop (please complete the following information):
 - OS: Any
 - Browser Any
 - Version Any

### Smartphone (please complete the following information):
 - Device: Any
 - OS: Any
 - Browser Any
 - Version Any

### Additional context
Take dates from https://summerofcode.withgoogle.com/

**Comment by nlok5923** [comment]
@annabauza i want to work on it.

**Comment by annabauza** [comment]
yes yours @nlok5923

**Comment by nlok5923** [comment]
@annabauza that program section shows timeline in production but showing under construction in develop branch.
![image](https://user-images.githubusercontent.com/56120084/106497942-b3651780-64e4-11eb-8012-31c40972a945.png)

**Comment by annabauza** [comment]
production is not used anymore. I think it has been merged to develop. have you fetched from upstream?

**Comment by nlok5923** [comment]
Sorry @annabauza  i forgot to fetched from upstream now it's fine
