### ISSUE TITLE
Missing Key Props ISSUE 

### ISSUE THREAD

**Issue by atharmohammad** [anitab-org/anitab-org.github.io#215]
### Missing key props
key props are not implemented in map method in components

### To Reproduce

- start the app 
- press cntrl + shift + I to open console
- there are warnings due to missing key props or not having a unique key

![warnings](https://user-images.githubusercontent.com/56029409/106500530-f5438d00-64e7-11eb-8be2-447f4c6bbcbd.PNG)
###components that don't have unique key props or dont have a key are :

1. ContributionSection
2. ContributionCard
3. Home
4. Projects
5. Events
6. Contribute

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser :Chrome
 - Version 88.0.4324.104

**Comment by Rahulm2310** [comment]
@atharmohammad Please add screenshots/GIF for the issue so that it is easy for anyone to confirm what issue you are trying to raise. Also, please follow the issue pattern while reporting a new issue. Thanks 🙂

**Comment by atharmohammad** [comment]
> @atharmohammad Please add screenshots/GIF for the issue so that it is easy for anyone to confirm what issue you are trying to raise. Also, please follow the issue pattern while reporting a new issue. Thanks 🙂

I have updated my issue ,Hope it will be easy for everyone to understand now, Tell me if you think more changes are needed ,also I have submitted a PR for this issue

**Comment by sagar-barapatre** [comment]
@atharmohammad Hey! I suggest you to wait until a maintainer confirms and assigns the issue to you before creating a pull request.

**Comment by annabauza** [comment]
approved

**Comment by atharmohammad** [comment]
> approved

can you assigne thi issue to me  ?

**Comment by annabauza** [comment]
yes it can @atharmohammad , yours :)
