### ISSUE TITLE
Add Medium icon in Footer

### ISSUE THREAD

**Issue by Amulya-coder** [anitab-org/anitab-org.github.io#226]
## Description
As a user, I think there should be a Medium icon also in the footer so visitors can directly follow and see the medium blog-post of the community.

Medium Link: https://medium.com/anitab-org-open-source

### Update [Required]
Add Medium Publication link

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hour

**Comment by Amulya-coder** [comment]
@annabauza what you think 🤔.

**Comment by annabauza** [comment]
:100: @Amulya-coder

**Comment by Amulya-coder** [comment]
@annabauza can you please add the tags and make it available for newcomers. Thanks🙂.

**Comment by shades-7** [comment]
hey if it's still open can I work on it?

**Comment by Amulya-coder** [comment]
Yes @shades-7, but wait until it's get assigned to you.

**Comment by nandini45** [comment]
@shades-7 I have assigned you the issue. Give us the update within three days ..

**Comment by shades-7** [comment]
@nandini45 ok

**Comment by shades-7** [comment]
@nandini45 i have send a PR, please review it.
