### ISSUE TITLE
Bug: Add STEM diverse tv cms to projects list

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/anitab-org.github.io#228]
### Describe the bug
Although [stem-diverse-tv-cms](https://github.com/anitab-org/stem-diverse-tv-cms) is actively developed, still it is not listed in the projects list

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Click on Projects
3. Scroll down

### Expected behavior
[stem-diverse-tv-cms](https://github.com/anitab-org/stem-diverse-tv-cms) should also be listed in the projects list.

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

### Smartphone (please complete the following information):
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@annabauza Can you please confirm/approve this issue. Thanks 🙂

**Comment by annabauza** [comment]
Yes approved, thank you @Rahulm2310

**Comment by Rahulm2310** [comment]
@annabauza Can I work on it or should I leave it for a new comer

**Comment by nandini45** [comment]
@Rahulm2310  probably a 1st timer issue.
you can look for other issues.

**Comment by KhushalAbrol** [comment]
I am new to open source can I do it, please?

**Comment by Rahulm2310** [comment]
@KhushalAbrol Of course you can, just wait for a maintainer to assign you the issue before starting on the fix. Thanks 🙂

**Comment by nandini45** [comment]
@KhushalAbrol  i can assign you the work but the work is a bit much 
can you do it, if yes i can assign u.
![image](https://user-images.githubusercontent.com/62046625/108128582-f6bda980-70d2-11eb-947c-7ab79d105af9.png)

**Comment by KhushalAbrol** [comment]
@nandini45 There is no card on the website yet. I thought I just have to add "stem-diverse-tv-cms" to the list of projects which I can do. But making these cards is bit much for me. I because never did this before. So I will not be able to do this.

**Comment by ishitakeshawani** [comment]
@nandini45 I can make a card for stem-diverse-tv-cms. Can you assign me this issue?

**Comment by keshakaneria** [comment]
> @nandini45 I can make a card for stem-diverse-tv-cms. Can you assign me this issue?

Go for it

**Comment by ishitakeshawani** [comment]
@keshakaneria Can you please review #236?

**Comment by Rahulm2310** [comment]
@nandini45 @keshakaneria  There is no response from @ishitakeshawani on #239. Also, the PR needs to be closed as it is raised from `develop` branch. I think this should be made available again. If yes, I would like to fix this quickly.

**Comment by keshakaneria** [comment]
> @nandini45 @keshakaneria There is no response from @ishitakeshawani on #239. Also, the PR needs to be closed as it is raised from `develop` branch. I think this should be made available again. If yes, I would like to fix this quickly.

Go ahead! 👍
