### ISSUE TITLE
Add jest tests and snapshots

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#23]
## Description
As a Developer,
I need to add jest test and snapshots,
so that I can see automated tests has passed on PR.

### Update [Required]
- [ ] contain at least 1 test and at least 1 snapshot

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by annabauza** [comment]
please do!

**Comment by annabauza** [comment]
@gaurivn it has been 7 days since you started this issue. Please let me know if you are close to finish otherwise I will re-assign it.

**Comment by gaurivn** [comment]
@annabauza , I was facing problems when writing the test for App.js as App.test.js inside _tests_.
 I am completely new to jest and thence the delay. I would like to work on this for today and try complete it.

**Comment by gaurivn** [comment]
@annabauza , I tried many ways but I am unable to get tests working correctly and am only getting what is shown in below attached screenshot. I would want to be unassigned from this issue so that it's open to others and I can focus on other issues at hand. 
![jestunable](https://user-images.githubusercontent.com/48416306/80840495-7e066300-8c0e-11ea-8c69-4cdc75ac270f.png)

**Comment by annabauza** [comment]
Please share it maybe I could help?

**Comment by gaurivn** [comment]
@annabauza , sorry for the delay in replying. I didn't get how to use react test renderer in App.js to connect to src/_ tests _/App.test.js. Grateful if you could help me solve this issue. Please find the screenshot of what I tried below, I tried and commented few functions.
![jestunable2](https://user-images.githubusercontent.com/48416306/80899387-88188680-8d20-11ea-85a8-8863426deccb.png)

**Comment by annabauza** [comment]
Yeah I have similar issue. Changed label from easy to hard. Keep going I will help if I have time.

**Comment by gaurivn** [comment]
Thank you, I will continue trying and ask you if I have doubts.

**Comment by gaurivn** [comment]
@annabauza , please can you unassign me from this issue...I have college work too and I am unable to write proper tests that work and generate snapshots after trying a lot from different sources since I am a beginner to jest. I would like to leave this issue for other contributors.

**Comment by tonythetiger323** [comment]
I would like to take a stab at this!

**Comment by gaurivn** [comment]
Sure @tonythetiger323, assigning to you, happy coding!

**Comment by tonythetiger323** [comment]
Thanks! Getting started right now.

**Comment by tonythetiger323** [comment]
My apologies, had a computer issue and had to erase my system and reinstall, getting things set back up today and then will be on it, sucks as I had pretty much had it done. My apologies.

**Comment by gaurivn** [comment]
No problem @tonythetiger323, thanks for the update.

**Comment by gaurivn** [comment]
How's it going....pls give an update

**Comment by gaurivn** [comment]
Unassigning due to inactivity.

**Comment by khushishikhu** [comment]
@annabauza  @gaurivn  may i take this issue?

**Comment by annabauza** [comment]
Yours

**Comment by khushishikhu** [comment]
@annabauza do we have to write tests for the automated test on PR, like for travis-ci in app.test.js file

**Comment by annabauza** [comment]
One snapshot and one test is enough to show integration works

**Comment by khushishikhu** [comment]
@annabauza  can you please explain me for what we need to check integration test here.

**Comment by annabauza** [comment]
@khushishikhu ahh unit test is interesting question. Not sure if we do anything adbance here, so maybe just snapshot of projects screen?

**Comment by khushishikhu** [comment]
@annabauza  yes, i think we can do snapshot testing for project's screen 👍

**Comment by khushishikhu** [comment]
can anyone please review my PR

**Comment by Bucky25** [comment]
@annabauza  if nobody is working on it can i take it over

**Comment by Bucky25** [comment]
@nandini45 if nobody is working on this. 
I would like to take it over .

**Comment by annabauza** [comment]
Yes @Bucky25 please do, good luck!

**Comment by Bucky25** [comment]
@annabauza some questions are we using react-testing library for conforming that and making a new folder for test will be better so we can latter add more test if needed  .what are your thoughts on it .

**Comment by Bucky25** [comment]
@annabauza do i have to write snapshot test for each component
