### ISSUE TITLE
PR Template in CONTRIBUTING.md doesn't exist

### ISSUE THREAD

**Issue by prathameshbhalekar** [anitab-org/anitab-org.github.io#230]
### Describe the bug
PR Template in CONTRIBUTING.md doesn't exist

### To Reproduce
1. Go to 'https://github.com/anitab-org/anitab-org.github.io/blob/develop/CONTRIBUTING.md'
2. Scroll down to 'Contributing Guidelines'
3. Click on 'this template '

### Expected behavior
Should direct to PR template

### Screenshots
![image](https://user-images.githubusercontent.com/33856767/107728241-8e0db000-6d13-11eb-9132-a3318a5e0538.png)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Firefox
 - Version 85.0.1 (64-bit)

**Comment by Rahulm2310** [comment]
@prathameshbhalekar yes, it is a valid issue. `this template` should be linked to https://github.com/anitab-org/anitab-org.github.io/blob/develop/.github/PULL_REQUEST_TEMPLATE.md. 
@annabauza This can be a good first timers only issue. Thanks 🙂

**Comment by ayan-biswas0412** [comment]
@Rahulm2310 @prathameshbhalekar @annabauza is anyone working in this issue ? if not then I can solve this issue

**Comment by Rahulm2310** [comment]
@ayan-biswas0412 Sure you can but please wait for a maintainer to confirm/approve this issue and assign it to you. 🙂

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Sure you can but please wait for a maintainer to confirm/approve this issue and assign it to you. 🙂

@isabelcosta is this issue valid and workable for me ?

**Comment by nandini45** [comment]
@prathameshbhalekar do u want to work on it or i can assign it to other contributors?

**Comment by prathameshbhalekar** [comment]
> 
> 
> @prathameshbhalekar do u want to work on it or i can assign it to other contributors?

No, i don't want to work on it.

**Comment by nandini45** [comment]
@ayan-biswas0412  do u wan to work on it?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 do u wan to work on it?

Yes I want to

**Comment by shruti1421** [comment]
If no one is working in this issue, can I take this up?

**Comment by ayan-biswas0412** [comment]
@shruti1421 I am not working in this , wait for a maintainer to assign you

**Comment by Rahulm2310** [comment]
@shruti1421 You can surely fix it if you have not contributed to this project in the past as it is a `First Timers only` issue. 

Cc: @nandini45 @isabelcosta

**Comment by im-sakshijain** [comment]
Hi! I'm new to this community, really want to contribute. May I fix this issue?

**Comment by Amulya-coder** [comment]
> Hi! I'm new to this community, really want to contribute. May I fix this issue?

Hi, @im-sakshijain Welcome to the community 🎉🎉 as @shruti1421 was the first to claim it this get assigned to him. Feel free to look at other available issues. Thanks 🙂

**Comment by shruti1421** [comment]
@isabelcosta could you please assign this to me after that I'll start working on it.

**Comment by im-sakshijain** [comment]
> > Hi! I'm new to this community, really want to contribute. May I fix this issue?
> 
> Hi, @im-sakshijain Welcome to the community 🎉🎉 as @shruti1421 was the first to claim it this get assigned to him. Feel free to look at other available issues. Thanks 🙂

@Amulya-coder Thank you, I'll look at other available issues.

**Comment by nandini45** [comment]
@shruti1421  i will assign you the issue.
please give us update after 3 days

**Comment by Jyotika999** [comment]
@nandini45 can you please assign this issue to me?
