### ISSUE TITLE
NavBar not responsive on mobile devices

### ISSUE THREAD

**Issue by pranay-simejia** [anitab-org/anitab-org.github.io#231]
### Describe the bug
Unresponsive navbar and list items (contribute) in  the bar requires more margin.

### Expected behavior
A button which toggles a sidebar should appear in small screen devices. 

### Screenshots
![image](https://user-images.githubusercontent.com/70064696/107796471-e4183d00-6d7f-11eb-949a-e9f679e45fd8.png)

**Comment by pranay-simejia** [comment]
Would you like me to work on this issue?

**Comment by Rahulm2310** [comment]
@pranay-simejia Thanks for showing interest but there already existed a issue (#174) which was closed as we are migrating to `react.js`.

**Comment by nandini45** [comment]
@Rahulm2310  thanks for the clarification.
@pranay-simejia  thanks for bringing it up again. i will close this issue for now.
 feel free to look at other available issues
