### ISSUE TITLE
Bug : Events page not loading properly on firefox browser

### ISSUE THREAD

**Issue by prathameshbhalekar** [anitab-org/anitab-org.github.io#232]
### Describe the bug
The events page is not loading properly on firefox browser.  It works fine some times but most of the times it is buggy. I tried the same on chrome and edge but its fine.

### To Reproduce
1. Go to 'https://anitab-org.github.io' in firefox
2. Click on 'events'
3. See error

### Expected behavior
same as chrome.

### Screenshots
![image](https://user-images.githubusercontent.com/33856767/107905617-1e96fb00-6f75-11eb-8d84-e5364355bd98.png)

![image](https://user-images.githubusercontent.com/33856767/107905628-25257280-6f75-11eb-898c-15a0e5a77e58.png)

![image](https://user-images.githubusercontent.com/33856767/107905643-2d7dad80-6f75-11eb-95f8-50dde9df5cbc.png)

![image](https://user-images.githubusercontent.com/33856767/107905653-34a4bb80-6f75-11eb-8859-259c13685544.png)

### Desktop:

 -   OS: Windows 10
 -   Browser Firefox
 -  Version 85.0.2 (64-bit)

**Comment by Rahulm2310** [comment]
@prathameshbhalekar I tried zooming in and after zooming out again, the page is rendered correctly. Seems to be an issue with mozilla I guess. It is working perfectly on Microsoft Edge as well.

**Comment by prathameshbhalekar** [comment]
Should I close the issue?

**Comment by Rahulm2310** [comment]
@prathameshbhalekar The issue persist when we first open the website on firefox. After zooming in/out, the page renders perfectly. I saw a few issues raised by devs using [firefox.](https://stackoverflow.com/questions/31349524/firefox-css-not-loading).
