### ISSUE TITLE
Event page need to align properly

### ISSUE THREAD

**Issue by shades-7** [anitab-org/anitab-org.github.io#234]
### Describe the bug
I believe the event section should be aligned properly 

### To Reproduce
1. Go to ' Events tab in navbar'
2. Scroll down to 'events'

### Expected behavior
There should be proper alignment.

### Screenshots
![Screenshot from 2021-02-16 15-15-07](https://user-images.githubusercontent.com/58786336/108045922-048b1480-706a-11eb-8602-50f9532d752e.png)

### Desktop (please complete the following information):
 - OS: [Ubuntu 18.04]
 - Browser [chrome]
 - Version [18.04.5 LTS]

**Comment by prathameshbhalekar** [comment]
Can i work on it?

**Comment by prathameshbhalekar** [comment]
Can I work on it if approved?

**Comment by shades-7** [comment]
@prathameshbhalekar wait till it is approved as an issue and i have begun the work on it.

**Comment by Rahulm2310** [comment]
@shades-7 Please wait for a maintainer's approval. There are ample opportunities to contribute. 🙂

**Comment by shades-7** [comment]
@Rahulm2310 okay sure, should I recreate the issue in the required form?

**Comment by nandini45** [comment]
@shades-7  yes please
 i will assign u the work

**Comment by Rahulm2310** [comment]
@nandini45 I think @shades-7 is already assigned to #226 . We should not assign multiple issues to a contributor.

**Comment by nandini45** [comment]
@Rahulm2310  thanks for telling 
@shades-7  u can work on only one issue at a time. after completing the 226 issue 
i can issue you afterwards

**Comment by mtochi** [comment]
Can I work on this?

**Comment by nandini45** [comment]
sure @mtochi

**Comment by nandini45** [comment]
@mtochi  are u working on it?

**Comment by mtochi** [comment]
@nandini45 Hey, yes sorry I haven't checked my github the last 3 days.

**Comment by mtochi** [comment]
@nandini45 I have been trying to set up the environment but I am running on some issues with Mac OS M1 chip, in case someone else will be interested please assign it to them, in the meantime I will continue to set up the environment.

**Comment by PriyaPal-tech** [comment]
Hi! I would like to work on this issue.
Thanks!

**Comment by keshakaneria** [comment]
> Hi! I would like to work on this issue.
> Thanks!

Assigned! :)
