### ISSUE TITLE
Add "Intro to Open Source" event to Events page

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#238]
## Description

As a newcomer,
I need see all the community events,
so that I can learn more about the community history and contributions to the community.

Event page: https://community.anitab.org/event/intro-to-open-source/
**Need image shared on social media** 🤔 

### Update [Required]
- [ ] Add "Intro to Open Source" event to Events page

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by Debanitrkl** [comment]
@isabelcosta can I work on this?

**Comment by Samyu982000** [comment]
@isabelcosta can I work on the issue.

**Comment by nandini45** [comment]
@Samyu982000  it think someone is already working on it.
u can look for probably other issues

**Comment by nandini45** [comment]
@Debanitrkl can you give us update of your work?

**Comment by Debanitrkl** [comment]
@nandini45 I was having difficulty in setting it up in my local system, now it's done will finish it in few hours

**Comment by PrernaSingh587** [comment]
Is this issue up for grabs?

**Comment by keshakaneria** [comment]
> Is this issue up for grabs?

Hello @PrernaSingh587 this is issue is taken by @Debanitrkl. But dont worry you can have a look at other issues which are unassigned and start working on them once assigned to you. [Let us know](https://anitab-org.zulipchat.com/#) if you are stuck anywhere 😄

**Comment by isabelcosta** [comment]
@Debanitrkl do you need help with the setup still?

**Comment by isabelcosta** [comment]
Here's the image you can use for the event https://twitter.com/KediaRasika/status/1261001532738138112/photo/1

**Comment by isabelcosta** [comment]
@Debanitrkl will unassign due to our rule of 3 days unresponsiveness.

**Comment by The-Keshav-Agarwal** [comment]
@isabelcosta I would like to work on this issue.

**Comment by The-Keshav-Agarwal** [comment]
@isabelcosta can you please tell me what should I write in par.
either i have to just copy paste all these point which is in the below image or i have to write it by my own?
![image](https://user-images.githubusercontent.com/56120769/110413727-63b1d700-80b4-11eb-9359-f3dabac47ced.png)

**Comment by isabelcosta** [comment]
@The-Keshav-Agarwal you can copy-paste, and then on code reviewing your pull request we can suggest changes if necessary :) thank you for checking in :)

**Comment by Aayush-hub** [comment]
@isabelcosta @vj-codes @epicadk @HeroicHitesh @codesankalp @codesankalp Is AnitaB.org comming in GSoC'21, as the full timeline of the program is mentioned in Programs section in AnitaB site (https://anitab-org.github.io/) , but we can't see AnitaB on GSoC website. Can you please confirm?

**Comment by isabelcosta** [comment]
@Aayush-hub no, its not participating on GSoC 2021 :) So it should be removed. cc @annabauza

**Comment by A-GHOSH-dev** [comment]
Can I contribute here? Please let me know

**Comment by nandini45** [comment]
@A-GHOSH-dev  someone is working on it. please look for other issues

**Comment by The-Keshav-Agarwal** [comment]
@A-GHOSH-dev I already made a pr for this, but no one has reviewed it till now.

**Comment by A-GHOSH-dev** [comment]
> @A-GHOSH-dev I already made a pr for this, but no one has reviewed it till now.

Ohh...Please continue your work.... :) @The-Keshav-Agarwal I will look for another issue....
