### ISSUE TITLE
Delete .github/ISSUE_TEMPLATE folder

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/anitab-org.github.io#242]
## Description
As a org contributor,
We need to maintain 1 version of issue templates used in the organization,
so that we can avoid duplicating work and having different versions of the templates, when we want to use the same ones across all projects.

Because the issue templates are now on [https://github.com/anitab-org/.github](https://github.com/anitab-org/.github), we don't need to have issue templates present in the repository. Read more about these type of files here [https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file](https://docs.github.com/en/github/building-a-strong-community/creating-a-default-community-health-file)

### Update [Required]
- [ ] [Delete .github/ISSUE_TEMPLATE]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hours

**Comment by Rahulm2310** [comment]
@nandini45 Could you please add labels to it. It can be a good first timers only issue. Thanks 🙂

**Comment by im-sakshijain** [comment]
Hi! I want to work on this issue, please assign this issue to me.
Thanks!

**Comment by Rahulm2310** [comment]
@im-sakshijain Also, please update the links to this file wherever it is required so that we don't get a `404 Page Not Found`.

**Comment by im-sakshijain** [comment]
@Rahulm2310 Sure!!
