### ISSUE TITLE
Proper Alignment of Events in Events Page

### ISSUE THREAD

**Issue by Vishal-raj-1** [anitab-org/anitab-org.github.io#243]
### Describe the bug
Currently it show only two events in one row, extra white spaces are there.

### To Reproduce
1. GO to Event Page of the Website. You will see
![events](https://user-images.githubusercontent.com/59874304/109111061-400a9a80-775e-11eb-8706-68002a6f3c15.JPG)

### Expected behavior
It should have three events in one row.

### Desktop (please complete the following information):
 - OS: [Window]
 - Browser [chrome]

**Comment by tosimiadesoye** [comment]
May I work on this?

**Comment by nandini45** [comment]
@Vishal-raj-1  the issue is already there
@tosimiadesoye  you can look for other issues probably
this is a duplicate issue
there are lot many issues on which you can  work

**Comment by Vishal-raj-1** [comment]
@nandini45 Is this same ? In that issue it was mentioned to align the paragraph and image. But in this issue It is mentioned that "we should use 3 card in one row instead of 2".
