### ISSUE TITLE
Change web title from `React App` to `AnitaB.org Open Source`

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#25]
### Describe the bug
Title in web tab says `React App`

### To Reproduce
1. Go to https://anitab-org.github.io
2. See title of web is `React App`

### Expected behavior
Title in web tab should say `AnitaB.org Open Source`

### Screenshots
<img width="415" alt="Screenshot 2020-04-24 at 20 00 06" src="https://user-images.githubusercontent.com/31966073/80247609-3dcf3f80-8666-11ea-96d1-4e3d7d22a3ff.png">

**Comment by nandini45** [comment]
Can i work on it??
@annabauza

**Comment by annabauza** [comment]
yes @nandini45 :) assign you

**Comment by nandini45** [comment]
@annabauza  i did the changes a day ago but i am not able to make the commit. can you help me out?
