### ISSUE TITLE
Bug : Programs Page buttons not designed properly

### ISSUE THREAD

**Issue by prathameshbhalekar** [anitab-org/anitab-org.github.io#251]
### Describe the bug
The icons and text are not aligned properly and the text is not clickable.

### To Reproduce
1. Go to 'https://anitab-org.github.io/'
2. Click on 'programs tab'
3. See error

### Expected behavior
The icon and text should be aligned. The text and icon can be clickable instead of only icon.

### Screenshots
![image](https://user-images.githubusercontent.com/33856767/110268526-ca1cf380-7fe7-11eb-83a1-ffb1dccfe0b9.png)

Desktop (please complete the following information):

    OS: Windows 10
    Browser Firefox
    Version 85.0.1 (64-bit)

**Comment by prathameshbhalekar** [comment]
@Rahulm2310  @nandini45  what do you think?

**Comment by darshanhande11** [comment]
@prathameshbhalekar I would like to work on this issue

**Comment by keshakaneria** [comment]
> 
> 
> @keshakaneria @Aaishpra @codesankalp I would like to work on this issue

You can go ahead to solve the issue 😄

**Comment by codesankalp** [comment]
@keshakaneria @darshanhande11 is already assigned to many other issues in this repo.

**Comment by darshanhande11** [comment]
@codesankalp I have assigned to #260 (for which I have made a PR and it has been labeled ready-to-merge) and #263 (which I am trying to fix). Also, I have fixed this issue and will be making a PR shortly.

**Comment by keshakaneria** [comment]
> 
> 
> @keshakaneria @darshanhande11 is already assigned to many other issues in this repo.

In this case you will be assigned once you create the PRs of those issues. Till that time, if no one comes to solve this issue, we may assign you again :)
