### ISSUE TITLE
feat: show contributor username on hover on contributor's github profile image

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/anitab-org.github.io#252]
### Is your feature request related to a problem? Please describe.
I think it would be good to provide an small hover effect like a UI popup once any user hovers on contributor's github profile pic at project information card
![image](https://user-images.githubusercontent.com/56120084/110274005-dad36680-7ff3-11eb-854d-da949eb7aa40.png)

### Describe the solution you'd like
Is ti bring a Uipopup component which will display github username when user hover on contributor profile image.

### Describe alternatives you've considered
Simple solution as described above would suffice this feature

### Additional context
Example: 
same as Uipop up element of semantic UI:
![image](https://user-images.githubusercontent.com/56120084/110273915-a3fd5080-7ff3-11eb-9b1e-899b434b63d8.png)

**Comment by nandini45** [comment]
@annabauza i think its a good suggestion.
if you approve it 
i can assign him the work
