### ISSUE TITLE
[Bug]: CONTRIBUTING.md is present at two locations in the repo

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/anitab-org.github.io#256]
### Describe the bug
CONTRIBUTING.md file is present at root as well as under the `docs` folder.

### To Reproduce
1. Go to https://github.com/anitab-org/anitab-org.github.io
2. See error

### Expected behavior
One of them should be removed. (Ideally the one present at root must be removed as it is not referenced from anywhere)

### Desktop (please complete the following information):
 - OS: Any
 - Browser: Any
 - Version: Any

**Comment by Rahulm2310** [comment]
@keshakaneria @nandini45 Please add `First Timers only` label.

**Comment by keshakaneria** [comment]
Thanks to notice this duplication! Sure adding the label.

**Comment by im-sakshijain** [comment]
Hi! May I work on this issue ?

**Comment by keshakaneria** [comment]
> Hi! May I work on this issue ?

Sure, go ahead 😄

**Comment by keshakaneria** [comment]
> @im-sakshijain As you are assigned to #242 , you are not a First Timer. Please let a newcomer fix it. You can look for some other available issues. 🙂
> 
> Cc: @keshakaneria

Her previous PR was ready to merge so thought of assigning her. But yes I'm sorry @im-sakshijain, new contributors should solve this so that they get a pinch of motivation to contribute in Open source. In the mean time you can look forward to new issues which aren't first timers 😄

**Comment by Chelsi-create** [comment]
Hii!
May I work on this issue?

**Comment by keshakaneria** [comment]
> Hii!
> May I work on this issue?

Sure go ahead!

**Comment by Chelsi-create** [comment]
@keshakaneria  I've raised a PR, please review it!
