### ISSUE TITLE
Open the footer social link in new tab

### ISSUE THREAD

**Issue by shades-7** [anitab-org/anitab-org.github.io#260]
### Describe the bug
Right now the link of social icons opens in the same tab, it will be better if it opens in another tab so that the user won't get redirected from the main website.

### To Reproduce
1. Go to 'https://anitab-org.github.io/'
2. Scroll down to 'footer'
3. Click on 'any of the social icon'
4. See error 'as it opens in the same tab'

### Expected behavior
When we click on the social icon in the footer the link should open in a new tab

### Desktop (please complete the following information):
 - OS: [ubuntu 18.04]
 - Browser [ chrome]

**Comment by aditisingh2412** [comment]
Hey, can I work on this issue?

**Comment by Ayush-projects** [comment]
Hey, can I work on this issue?

**Comment by P-riyanka-prasad** [comment]
Is this still open ? can i work on this

**Comment by darshanhande11** [comment]
@shades-7 If no one else is working on this issue, may I work on this?

**Comment by darshanhande11** [comment]
@keshakaneria @nandini45 I would like to fix this. I have completed the fix, please assign me this issue, so that I can make a pull request.

**Comment by keshakaneria** [comment]
> 
> 
> @keshakaneria @nandini45 I would like to fix this. I have completed the fix, please assign me this issue, so that I can make a pull request.

Go for it!
