### ISSUE TITLE
Bug: Mismatch dates for OSH period under Rules and Timeline | URGENT

### ISSUE THREAD

**Issue by mtreacy002** [anitab-org/anitab-org.github.io#262]
### Describe the bug
The OSH periods stated under Rules and Timelines sections are different. Under Rules it's 1-31 Sep, under Timelines it's 1-30 April.

### To Reproduce
1. Go to https://anitab-org.github.io/events/open-source-hack/
2. Scroll down to Rules and check dates
3. Scroll down to Timeline and check dates
4. Notice the different OSH periods

### Expected behavior
The OSH periods should be the same across the site

### Screenshots
<img width="788" alt="Screen Shot 2021-03-15 at 11 01 27 am" src="https://user-images.githubusercontent.com/29667122/111089288-521e7280-857f-11eb-8566-5479b185e135.png">

<img width="761" alt="Screen Shot 2021-03-15 at 11 01 44 am" src="https://user-images.githubusercontent.com/29667122/111089294-56e32680-857f-11eb-9500-a6127e954061.png">

### Desktop (please complete the following information):
 - OS: macOS Catalina v10.15.7
 - Browser: Safari v 14.0.2

### Additional context
NA

**Comment by mtreacy002** [comment]
Labelling this `First-timers only` issue

**Comment by annabauza** [comment]
Approved need to be fixed ASAP

**Comment by mtreacy002** [comment]
> Approved need to be fixed ASAP

Making it available for others to pickup as I have made my first contribution through PR #138 😉

**Comment by jalajcodes** [comment]
Are these dates supposed to overlap?
![image](https://user-images.githubusercontent.com/17108695/111140334-3bd8dc80-85a8-11eb-9757-b5f6e7ec9aca.png)

**Comment by 17sushmita** [comment]
Can I work on this issue?

**Comment by devkapilbansal** [comment]
@17sushmita Assigning you :tada:

**Comment by aditisingh2412** [comment]
Can I fix this issue?

**Comment by HeroicHitesh** [comment]
@17sushmita Any updates on your progress?

**Comment by 17sushmita** [comment]
> @17sushmita Any updates on your progress?

Sorry for the delay. I'm making the PR.

**Comment by 17sushmita** [comment]
I'm not able to find this page while running the project on the local server.
Can anyone help on this.
![image](https://user-images.githubusercontent.com/42088159/111583989-3e734600-87e3-11eb-863c-b736ece6356b.png)

**Comment by devkapilbansal** [comment]
@mtreacy002 @anitab-org/admins this issue should be in different repo.
Here is the line where it is mentioned:- 👇 
https://github.com/anitab-org/events/blob/9ca09b968a9e369aef09ba2fc10cdf0468074757/open-source-hack/index.html#L187

Consider either closing this issue and opening a new one or transferring it the concerned repo

**Comment by mtreacy002** [comment]
@devkapilbansal , thanks for pointing this out and referring to the right repo. Will close it here and open a new one on the other repo as I'm not sure how to transfer it (perhaps not authorised to do it 😁). Sorry for misplacing the issue here and @17sushmita , sorry for the inconvenience 😊.
