### ISSUE TITLE
Bug : Replace text links with Href

### ISSUE THREAD

**Issue by prathameshbhalekar** [anitab-org/anitab-org.github.io#263]
### Describe the bug
Replace text links with href in ```about us```, ```contribute``` tabs and footer 

### To Reproduce
1. Go to 'https://anitab-org.github.io/'
3. See error

### Expected behavior
links in href instead of normal text

### Desktop (please complete the following information):
 - OS:  Windows 10
 - Browser Firefox
 - Version 85.0.1 (64-bit)

**Comment by aditisingh2412** [comment]
Hey, Can I work on this issue?

**Comment by prathameshbhalekar** [comment]
> 
> 
> Hey, Can I work on this issue?

Sure, just wait for approval.

**Comment by aditisingh2412** [comment]
So should I start working on this issue now or after it has been approved?

**Comment by HeroicHitesh** [comment]
> So should I start working on this issue now or after it has been approved?

@aditisingh2412 You should start working after the issue is approved and you are assigned till then you can setup the project in your local machine.

**Comment by aditisingh2412** [comment]
Okay sure!

**Comment by darshanhande11** [comment]
@prathameshbhalekar @keshakaneria If no one else is currently working on this issue, then I would like to work on this.

**Comment by keshakaneria** [comment]
> 
> 
> @prathameshbhalekar @keshakaneria @HeroicHitesh If no one else is currently working on this issue, then I would like to work on this.

Yeah no one is currently assigned this issue! Go for it @darshanhande11
