### ISSUE TITLE
Explain development setup and run instructions

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#27]
## Description

As a contributor getting to run the project for the first time,
I need instructions on how to setup and run it,
so that I can get started with contributing to the project.

This should be added to the README. It would be good to include instructions on how to run tests locally as well.

### Update [Required]
- [ ] Add setup and run section to README

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by annabauza** [comment]
please do gaurivn

**Comment by annabauza** [comment]
@gaurivn I saw you have other issue assigned which has not been done - https://github.com/anitab-org/anitab-org.github.io/issues/23, which one you are doing atm?

**Comment by gaurivn** [comment]
@annabauza  I will do this issue first and then complete the other one you mentioned.
