### ISSUE TITLE
Change style of 'Today' button on Events Page.

### ISSUE THREAD

**Issue by devptyagi** [anitab-org/anitab-org.github.io#276]
### Description
The 'Today' button on the Events page has default styling and looks kinda ugly.

### To Reproduce
1. Go to 'https://anitab-org.github.io/'
2. Click on 'Events'
3. Scroll down to 'Event Calendar'
4. Have a look at the 'Today' Button

### Expected behavior
Button styling should match the page color.

### Screenshots
* Before:
![image](https://user-images.githubusercontent.com/56474716/121837156-93dfc600-ccf2-11eb-8966-a5a1547ea8b8.png)

* After:
![image](https://user-images.githubusercontent.com/56474716/121837188-9f32f180-ccf2-11eb-96c9-67928e33f09f.png)

### Desktop:
 - OS: All
 - Browser All
 - Version All

### Smartphone:
 - Device: All
 - OS: All
 - Browser All
 - Version All

### Additional context
NIL.

**Comment by devptyagi** [comment]
@epicadk @isabelcosta @annabauza kindly review this.

**Comment by epicadk** [comment]
Since this is a UI change it needs @anitab-org/designers  approval

**Comment by nandini45** [comment]
@devptyagi  it can be changed , i approve it,
u can work on it

**Comment by devptyagi** [comment]
@nandini45 Yes I wanna work on this!

**Comment by devptyagi** [comment]
@nandini45 @vj-codes I just had a look into it and realized that the 'Today' button is inside the Embedded Google Calendar Iframe. We can not change the style of elements inside the iframe. 😔

**Comment by nandini45** [comment]
yes @devptyagi  there is no need to change.
and i think it looks fine to me. there is  no need for changes in the button color for now . if @vj-codes  agrees we can close this issue. you can probably look for other design issues or design changes in the site.!
![s](https://user-images.githubusercontent.com/62046625/122202821-07ccca80-cebb-11eb-9805-5e7fc025223d.jpg)

**Comment by vj-codes** [comment]
Agreed 👍
