### ISSUE TITLE
Add reference to new stream on Zulip on README

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#28]
## Description

As a new contributor,
I need to know what channels are focused on discussions about this project on Zulip,
so that I can participate in such discussions.

The idea here is to enhance the Contact section on README to include the link to the anitab-org.github.io stream on Zulip.

### Update [Required]
- [ ] Add link to Zulip stream on Contact section on README

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
1 hours

**Comment by nandini45** [comment]
can i do this? @isabelcosta

**Comment by nandini45** [comment]
@isabelcosta  i think we have that section on the Readme

**Comment by isabelcosta** [comment]
We have the section, but it has the link to the design team and not the actual project zulip stream. Do you still wish to work on this? @nandini45

**Comment by nandini45** [comment]
oh sure!! i will change it
@isabelcosta

**Comment by isabelcosta** [comment]
Oh, i just noticed, you are already assigned to an issue here, and this is for first timers only, can you please finish the one you were assigned to and leave this for new contributors? @nandini45

**Comment by nandini45** [comment]
okk 😅😅
@isabelcosta

**Comment by abha224** [comment]
@isabelcosta can I work on this issue?

**Comment by isabelcosta** [comment]
You already contributed to this project right? Could you check other issues since this issue is fairly simple and we leave this for someone new to the project and make their first contributions to it? @abha224

**Comment by abha224** [comment]
Ohh ok, I understand. Will look out for other issues to work on!@isabelcosta

**Comment by isabelcosta** [comment]
Thank you @abha224 :)

**Comment by doctypehuman** [comment]
Hello Isabel, 

I have recently joined Github and I would like to help. Let me know if it works for you. Thanks !

**Comment by isabelcosta** [comment]
@doctypehuman sure :) I will assign this to you, what would you need help with? Have you checked the README already?
cc @annabauza

**Comment by doctypehuman** [comment]
@isabelcosta I did read the README. If i have understood this correctly, within the contact section of README , a link to zulip to be inserted. So I can clone the branch, edit the section and push it back ? 
Also, apologies for the late reply. Thanks. 
cc@annabauza

**Comment by AyushSatyam** [comment]
Hello @isabelcosta,
I am new to open Source. Can I work on this issue?

**Comment by isabelcosta** [comment]
@AyushSatyam this is assigned to @doctypehuman 
Can you please look for other issues? Also I hope you are on Zulip, every week we are deciding on how this website will look like, and discuss potential issues :)

**Comment by isabelcosta** [comment]
No problem @doctypehuman :) Yes, what we want is to have the stream dedicated to this project mentioned in the Contact section, together with the link to it.
You can fork -> clone -> git commit -> git push. You can also do this in the GitHub interface, without cloning to your dev environment, however you prefer :)

**Comment by doctypehuman** [comment]
Thanks @isabelcosta . Its done. I have created a pull request and the merge is pending review.  Thanks !
