### ISSUE TITLE
Linking component is not being imported, which is currently breaking build (:

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#280]
## Description

So there is a little error in one of the files that is causing fail in the build. I merged the PR very recently 🤦🏾‍♀️  https://github.com/anitab-org/anitab-org.github.io/pull/247

Error 😳  https://github.com/anitab-org/anitab-org.github.io/runs/3175046196
```
./src/Components/Footer/Social.js
  Line 52:13:  'Linking' is not defined  no-undef
```
### Update [Required]
- [ ] Fix error that is breaking build

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by mimzivvimzi** [comment]
Hi @isabelcosta Is this still up for grabs?  If so, I have the fix ready.

**Comment by vj-codes** [comment]
Assigning you @mimzivvimzi 
Happy coding!

**Comment by isabelcosta** [comment]
Go ahead and submit a pull request when you ready @mimzivvimzi 🤗
