### ISSUE TITLE
Make Install and Build step run a PR check

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#284]
## Description

As a reviewer/contributor/admin,
I need new PR check to make sure the app is building successfully,
so that I can merge PR with confidence that the code is not breaking the app.

## Mocks

Here's an example of this check for every commit: https://github.com/anitab-org/anitab-org.github.io/runs/3175046196

### Update [Required]
- [ ] New pull request check for every new pull request created
- [ ] Run tests on every new pull request created

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

**Comment by nlok5923** [comment]
@isabelcosta i would like to work on this issue.

**Comment by raffaelecalza** [comment]
Hi @isabelcosta can I work on this for the hacktoberfest?

**Comment by isabelcosta** [comment]
@raffaelecalza of course! I will assign it to you!

**Comment by raffaelecalza** [comment]
Hey @isabelcosta I opened a new PR. I tested the workflow inside my repo and it runs as expected. Let me know if I have to change something or if it's okay
