### ISSUE TITLE
Add link to docusaurus to each project that has it deployed

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#286]
## Description

As a contributor,
I need to see where project documentation is available,
so that I can learn more about a project.

We want to have a link to the project's docusaurus next to the project. [mentorship-android](https://github.com/anitab-org/mentorship-android) has their documentation at https://anitab-org.github.io/mentorship-android/

## Mocks

You can get this on the `Projects` page - this represent a project card.

<img src="https://user-images.githubusercontent.com/11148726/136611912-94300bf2-c0a5-42f6-9d19-a7041183a2b5.png" alt="mentorship android project card on Projects page" width="200"/>

Feel free to suggest where to place the docusaurus link. I don't have any specific preference for this.

### Update [Required]
- [ ] Add a docusaurus link to each project's card

## Definition of Done
- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation
4 hours

**Comment by brittanyjoiner15** [comment]
@isabelcosta do you think adding it [here](https://github.com/anitab-org/anitab-org.github.io/blob/develop/src/Components/Projects/ProjectCard/index.js#L25) might make sense? And would it simply be making a line to show a link and map `props.docsLink`? 

Also how can you tell which projects in [content/project_content](https://github.com/anitab-org/anitab-org.github.io/blob/develop/src/content/projects_content.js) have docs? Or is that part of the issue... going to look those up and finding their docs?

**Comment by isabelcosta** [comment]
I can assign it to you @brittanyjoiner15 :) Just so you know, as per our community guidelines, we try to have contributors one on one task at a time. I'll assign since you're now waiting for review and we haven't yet requested changes.

**Comment by isabelcosta** [comment]
I wonder about putting it under GitHub and Zulip rows 🤔 (ignore the GitHub icon, we can replace it with another icon) 
I also wonder about putting the description on the topic of those links, but that could be another issue :)
You have some creative freedom here :) I really appreciate your due diligence 🤓 🤗 What do you think @brittanyjoiner15 ?

![project card](https://user-images.githubusercontent.com/11148726/137227128-34709ddc-a970-4d37-9705-a881b80b2531.png)

**Comment by brittanyjoiner15** [comment]
@isabelcosta i think i like this! what do you think?
![image](https://user-images.githubusercontent.com/16166290/137331542-a3e03aa0-b038-452c-bb1f-9f62142135e5.png)
