### ISSUE TITLE
Remove travis.yml from the repository

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/anitab-org.github.io#288]
### Is your feature request related to a problem? Please describe.
Since the organization is now using Github Actions for CI/CD, we should remove travis file from the code.

### Describe the solution you'd like
Remove the file

**Comment by vj-codes** [comment]
@isabelcosta what do you think about this issue?

**Comment by isabelcosta** [comment]
sounds good @vj-codes ! since we are getting a GH Actions workflow in place :)

**Comment by WizardLemon** [comment]
Hi, I'm new to contributing to open source, can I take this on?

**Comment by isabelcosta** [comment]
Sure go ahead @WizardLemon :)

**Comment by WizardLemon** [comment]
@isabelcosta hi, I've made a PR for this, have I used the PR template correctly?

**Comment by isabelcosta** [comment]
Yes you did @WizardLemon :)
