### ISSUE TITLE
Fix tests and enable GitHub Actions job for running tests

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#292]
## Description

As a maintainer,
I need tests to be passing,
so that I can enable workflow jobs to run tests for each PR.

There is an issue #284 adding a GH Action workflow to the project, this has a step to run tests, which is now commented and it's meant to be uncommented once the tests are passing.

## Mocks
N/A

### Update [Required]
- [ ] Fix tests until these pass and enable tests step on GitHub Actions workflow

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by isabelcosta** [comment]
@WizardLemon yes, you can assume that code is alright for now :) I will assign to you!

**Comment by WizardLemon** [comment]
I've updated the test snapshots, the PR that fixes #284 and adds the tests has not yet been merged, do you want me to rebase on top of that once it's been merged?

**Comment by isabelcosta** [comment]
@WizardLemon however you prefer, we usually use "Squash and merge" option. Would this eventually cause any issue?

Could you take a look at https://github.com/anitab-org/anitab-org.github.io/pull/287 and review it, if you feel you understand how it works? Once it has 2 approvals, I am happy to approve and then you can rebase :)
