### ISSUE TITLE
Add a code linter and it's github action

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/anitab-org.github.io#293]
### Is your feature request related to a problem? Please describe.
Different contributors have different code styles, so when merging the code we need to make sure the code is consistent.
Like Black is a linter for python, use Prettier or Eslint in this project.

### Describe the solution you'd like
Integrate either Prettier.io (https://prettier.io/) or Eslint(https://eslint.org/), format and push the updated code and 
add GitHub action to check the formatting using either of the two.

**Comment by brittanyjoiner15** [comment]
@vj-codes I was also thinking Prettier since i have more experience with it!
