### ISSUE TITLE
[Feature] Enable routers on the website

### ISSUE THREAD

**Issue by ftonato** [anitab-org/anitab-org.github.io#294]
### Is your feature request related to a problem? Please describe.

This can even be seen as a **bug** if we assume that currently if I'm on the "about us" route and try to share the link the receiver will always get the link from the "home" page.

Having the active routes would make links that could be shared seamlessly between anyone.

### Describe the solution you'd like

I would like to propose the implementation of routes for the application.

**Comment by isabelcosta** [comment]
I absolutely love this collaboration between contributors 🤩 🚀 💪🏾 🤗  This is really amazing 🙌🏾 

@ftonato no worries if this task is too much for you to work on at this time (thank you so much for your honesty!). I am happy to assign this to @brittanyjoiner15 , once the PRs are their way to merge.

🧐 On a related note, in this community, we really encourage people to participate in code reviews, so if you two want to review PRs and accelerate these approvals/merges processes, you are more than welcome to!

**Comment by brittanyjoiner15** [comment]
@isabelcosta wooho! Sounds great!! I'll keep an eye out and look for other PRs. Just reviewed the capital letters one you tagged me in! Will take a look at some others later! 👀

**Comment by brittanyjoiner15** [comment]
@isabelcosta can you go ahead and assign this to me since my other issues are completed? I'll start working on this!

**Comment by ftonato** [comment]
@isabelcosta go to your telegram acc

**Comment by isabelcosta** [comment]
No worries! thank you for this update @brittanyjoiner15 :) 💪🏾 
Feel free to submit the PR whenever you see fit, I don't mind work-in-progress PRs.
