### ISSUE TITLE
[Refactor] Update our navigation bar converting all capital letters to normal text

### ISSUE THREAD

**Issue by ftonato** [anitab-org/anitab-org.github.io#295]
### Describe the situation
We are using in our navigation bar all texts as capital letters and this brings some special problems for (screen readers & search engines).

### To Reproduce
Steps to reproduce the behaviour:
1. Go to our website
2. Look for the navigation bar (check the image below)

![image](https://user-images.githubusercontent.com/5417662/136962981-26d27055-7ad1-4b60-aa45-711fa2f6dee2.png)

### Expected behaviour
At the end of the day we should have the same result, but using the proper properties in our code.

### Desktop (please complete the following information):
 - OS: MacOS
 - Browser: https://www.whatsmybrowser.org/b/LI5WH

**Comment by ftonato** [comment]
I'm also available to work on this "refactor" if approved!

**Comment by eleensmathew** [comment]
Hi can i work on this issue? I'm a beginner so I might need help.

**Comment by ftonato** [comment]
@eleensmathew we have open PR's for that since [12 Oct 2021](https://github.com/anitab-org/anitab-org.github.io/issues/295#ref-pullrequest-1023830806)

**Comment by eleensmathew** [comment]
Oh okay 👍

**Comment by ftonato** [comment]
I'm closing outdated issues and pull-requests that are no longer relevant given how much time has passed since they were opened.
