### ISSUE TITLE
Add archive section to projects page

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/anitab-org.github.io#301]
## Description
As a contributor,
I need to keep the website updated ,
so that the information is accurate and true.Thus add archive section to the page to display archived projects like mentorship-ios and flutter, vms and portal OR remove them from projects page

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by vj-codes** [comment]
@isabelcosta what do you think about adding a new section below the active projects and mentioning the archived projects. Removing them is also another option but I think it won't be kind of fair :/

**Comment by abritpal** [comment]
Hi! @vj-codes , I would like to work on this can you assign me this issue

**Comment by vj-codes** [comment]
> @isabelcosta what do you think about adding a new section below the active projects and mentioning the archived projects. Removing them is also another option but I think it won't be kind of fair :/

@abritpal I'm waiting for this comment's reply and once confirmed will assign it to you :)

**Comment by abritpal** [comment]
ok cool!
