### ISSUE TITLE
Events page has overlap content

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#303]
## Description

Events page seems broken with the overlap of content. The calendar is under text, and there should not be overlap.

## Mocks

Check https://anitab-org.github.io/
This is what it looks like now.
![event calendar on top of text](https://user-images.githubusercontent.com/11148726/137631124-cb1d3feb-1b12-4552-b29c-06e61bd0461b.png)

### Update [Required]

- [ ] Solve overlap of content on Events page

## Definition of Done

- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

8 hours

**Comment by isabelcosta** [comment]
It's yours @arisaokasaka now 🤗

**Comment by prabhavagrawal7** [comment]
Can I work on this issue? Pleasee... It's would be my first commit ! 🥺

**Comment by isabelcosta** [comment]
@prabhavagrawal7 this task is already assigned and being worked on by @arisaokasaka :) Could you please look into other issues? We are trying to create new issues. Feel free to create if you see something that can be improved. If we approve, we can then assign to you
