### ISSUE TITLE
Move documentation files to docs folder

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#304]
## Description

This ticket is to clean up the root folder of this project. There are 2 files on the root folder that don't need to be there: `Wiki.md` and `fork.png`. These can be stored instead on `docs` folder.

### Update [Required]

- [ ] Move documentation files to docs
- [ ] Make sure to refactor the places in the documentation where the image is being referred to (avoiding breaking the link)

## Definition of Done

- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

## Estimation

0.5 hours

**Comment by jashlodhavia** [comment]
Can i be assigned this?

**Comment by sunil14701** [comment]
Hello!
I would like to work on this issue.
Could I?
Thank you so much!

**Comment by vj-codes** [comment]
@shades-7 hey sorry this is a first timers only issue :(

**Comment by vj-codes** [comment]
@sunil14701 any updates?

**Comment by Ayushi271** [comment]
Hello, My sincere Greetings
I want to work on this issue.
Can you assign me this.

**Comment by vj-codes** [comment]
@sunil14701 unassigning you due to inactivity

**Comment by vj-codes** [comment]
Assigning you @Ayushi271 
Happy documenting!

**Comment by Ayushi271** [comment]
@vj-codes Good evening Mam.
I am a beginner to open source contribution.
I have made some changes in files . But I don't know how  to upload for reviewing it. But it is  showing in pull request option  #337.
Can you please  guide me about that.

**Comment by Ayushi271** [comment]
Hello any updates?

**Comment by Ayushi271** [comment]
Can you please review it.

**Comment by eleensmathew** [comment]
Hi is this issue still open. If not can I please work on this?

**Comment by Ayushi271** [comment]
@eleensmathew  Hi, actually I had already made a PR for this which is in reviewing stage. So, you can find another issue and start contributing. Thanks

**Comment by Ayushi271** [comment]
#344 Please review

**Comment by Ayushi271** [comment]
#347 Please review

**Comment by udyanojha** [comment]
@isabelcosta  Please review the PR by @Ayushi271

**Comment by isabelcosta** [comment]
@udyanojha @Ayushi271 what is the PR to be reviewed? Could you please share the link here

**Comment by Ayushi271** [comment]
@isabelcosta  https://github.com/anitab-org/anitab-org.github.io/pull/347

**Comment by Ayushi271** [comment]
Please review it and if there is something wrong then please guide me

**Comment by isabelcosta** [comment]
@Ayushi271 could you please post this on Zulip, to see if anyone from the community can also review it. I will add a few points there, but we usually require 2 approvals before merging

**Comment by suryakapurothu** [comment]
Hello @isabelcosta and @Ayushi271 ,
I'm a new born here ;)
Ready to make small and helpful contributions.
You can assign me on this anytime for necessary changes.

**Comment by vedant-z** [comment]
@isabelcosta I am willing to work on this>
