### ISSUE TITLE
GitHub Actions is not deploying the project to GitHub Pages

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#312]
## Description

GH Actions is not deploying the project to GH Pages.
Commits: https://github.com/anitab-org/anitab-org.github.io/commits/develop
The deploy to GH Pages stopped working from commit https://github.com/anitab-org/anitab-org.github.io/commit/8db566a29aecc7d67a040b16dae468714761ef6f

![actions failing due to wrong syntax](https://user-images.githubusercontent.com/11148726/137748104-e53ff35b-bb3a-42e5-a366-24fcd157c7aa.png)

https://github.com/anitab-org/anitab-org.github.io/actions/runs/1354958354

### Update [Required]

- [ ] Fix deploy GitHub action step, making sure it also works on pull requests 💪🏾 

## Definition of Done

- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by aabhas-sao** [comment]
@isabelcosta I opened a PR #313 one task is not passing that might be due to my GitHub account not having authorization. Otherwise now prettier is running and formatting the files and there is no syntax error. Let me know If it working now or what to do next.
