### ISSUE TITLE
Comment out placeholders in Pull Request template

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#316]
## Description

We want placeholders to be commented out, so that when a contributor can notice soon when they have not filled in necessary details in the template.

Here's an example of how it should look like https://raw.githubusercontent.com/anitab-org/.github/main/.github/PULL_REQUEST_TEMPLATE.md

### Update [Required]

- [ ] Comment out placeholders in Pull Request template

## Definition of Done

- [ ] All of the required items are completed.
- [x] Approval by 1 mentor.

**Comment by mctraore** [comment]
Hello, I'm interested in working on this issue. Could you assign it to me?

**Comment by Koda-Pig** [comment]
Hi there, I'd love to have the chance to work on this.

**Comment by mctraore** [comment]
Hello! Here is a link to my PR: https://github.com/anitab-org/anitab-org.github.io/pull/321
