### ISSUE TITLE
Welcome bot not working

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/anitab-org.github.io#323]
### Describe the bug

When a contributor creates their first issue or first PR, ideally the welcome bot should drop a comment, but it does not seem to be working on any of our integrated projects except Bridge-in-tech-web which uses a different config.

BIT-web uses - https://github.com/behaviorbot/welcome (working)
Other projects use - https://github.com/bash-bot/the-welcome-bot (not-working)

### Solution 
Either make the bash-bot work or shift to behaviour bot config
 
### To Reproduce

1. Create your first issue/PR
2. See error, bot does not work

### Desktop (please complete the following information):

- OS: [Mac OS , Windows 10]

**Comment by vj-codes** [comment]
@madhhuurrii hey any updates?

**Comment by sabakhilji** [comment]
Hey, I want to contribute . Is the issue open now?
