### ISSUE TITLE
Broken CONTRIBUTING.md link inside the current README.md

### ISSUE THREAD

**Issue by sakshi-vats** [anitab-org/anitab-org.github.io#336]
**Description**
Fix the broken link for CONTRIBUTING.md in the current README.md
<img width="1352" alt="Screenshot 2021-11-22 at 12 08 26 AM" src="https://user-images.githubusercontent.com/47550087/142774737-6d20282c-d0a6-4109-a019-7d53797549d3.png">

**Comment by isabelcosta** [comment]
fixed with https://github.com/anitab-org/anitab-org.github.io/pull/335
