### ISSUE TITLE
docs: Create a new GitHub Wiki page that includes the "Setup and Install"

### ISSUE THREAD

**Issue by nandini45** [anitab-org/anitab-org.github.io#35]
### **Description**
As a contributor,
I need not see too much details on the README,
instead [we](url) can make a fork clone readme and mention it in the main readme and on clicking that readme appears.

### **Acceptance Criteria**
**Update [Required]**
Make a fork and clone readme separately and mention it in the readme 

### **Definition of Done**
 All of the required items are completed.
 Approval by 1 mentor.
### **Estimation**
1 hours

**Comment by nandini45** [comment]
@mayburgos @annabauza  i would like to work on this issue if it gets approved?

**Comment by mayburgos** [comment]
@nandini45 I'm confused on what you mean. There are both "fork" and "clone" instructions in the "Setup and run" section of the [ReadMe](https://github.com/anitab-org/anitab-org.github.io/blob/develop/README.md).

Can you specify what is missing?

**Comment by nandini45** [comment]
no i am saying that there is a there is a lot content on readme so we can create a separate fork clone readme and mention it in the readme.

**Comment by mayburgos** [comment]
I'm still a bit confused. You want a separate repo created for the readme? Can you send me examples of what you mean? @nandini45

**Comment by nandini45** [comment]
![Annotation 2020-04-30 015322](https://user-images.githubusercontent.com/62046625/80643293-7bc4cd00-8a85-11ea-9509-11e9a28bcba8.png)

**Comment by nandini45** [comment]
like this. for the people who are new to github we can make it easier for them to navigate @mayburgos

**Comment by mayburgos** [comment]
Oh! So you want to create an additional Wiki Page on the [anitab-org.github.io GitHub Wiki](https://github.com/anitab-org/anitab-org.github.io/wiki) to match the steps listed in the [Mentorship Android GitHub Wiki](https://github.com/anitab-org/mentorship-android/wiki/Fork,-Clone-&-Remote).

Right now, we haven't discussed the structure of the GitHub wiki. Since we use this repo's Wiki for Programs that we apply to (i.e. GSoC, GCI, etc) then we might have a different Wiki setup as others.

**Comment by nandini45** [comment]
@mayburgos  i had a request if you think this is a 1st timer issue 
can i open it for then??

**Comment by nandini45** [comment]
@mayburgos  Can i open it as a first timer issue for the new user?

**Comment by ShreyaPrasad1209** [comment]
Is anyone working on this issue? If not, then can I work on it?

**Comment by nandini45** [comment]
@mayburgos  @annabauza can i open it and assign it to her???

**Comment by mayburgos** [comment]
@nandini45 Github Wiki editing requires Write Access. However, Shreya can create the markdown files here so someone can upload. Here's an [example from Powerup iOS](https://github.com/anitab-org/powerup-iOS/issues/251). A zip file was uploaded.

**Comment by nandini45** [comment]
ok May 
..
@ShreyaPrasad1209  are u interested in working on this issue??

**Comment by ShreyaPrasad1209** [comment]
@nandini45 yes

**Comment by nandini45** [comment]
ok i will assign it to you. you can work on it
