### ISSUE TITLE
Typo in Archive page

### ISSUE THREAD

**Issue by isabelcosta** [anitab-org/anitab-org.github.io#355]
### Describe the bug

There is a typo in the description of archived projects

### To Reproduce
1. Go to https://anitab-org.github.io/
2. Click on Projects
3. Scroll down to "Archived Projects" section
4. See description of section with typo in word "avialable"

### Expected behavior

Should have "available" instead of "available"

### Screenshots

![typo in archived projects section](https://user-images.githubusercontent.com/11148726/172447680-24717841-6c15-4e0b-87a7-7bcc51ccd6f2.png)

### Additional context

This applies to any device where this website can be accessed.

**Comment by isabelcosta** [comment]
Sure! Make sure when you create the PR to add to the description this "Fixes #355" so it links to this issue. @Esther-Wavinya

**Comment by Esther-Wavinya** [comment]
Hey

I have edited the PR Description

**Comment by udyanojha** [comment]
Hi! @isabelcosta The issue is still there, may I please contribute to this?
![image](https://user-images.githubusercontent.com/51847297/178268948-3c22387b-884b-470d-ac32-db3b4b10923f.png)

**Comment by udyanojha** [comment]
> Hi! @isabelcosta The issue is still there, may I please contribute to this? ![image](https://user-images.githubusercontent.com/51847297/178268948-3c22387b-884b-470d-ac32-db3b4b10923f.png) 
- archieved  to  archived
- avialable to available

**Comment by AbhijeetKadam-coder** [comment]
Hello! @isabelcosta The issue still persists, may I work on this issue, please?

**Comment by kaykaym01** [comment]
Is this issue closed?
