### ISSUE TITLE
design:Create 4 doodle icons for home page.

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#37]
## Description
As a Developer,
I need to have 4 doodle icons (getting started, ways to contribute, our projects, open source programs),
so that I can place them in homepage following the agreed mockup.

## Mocks
[Agreed mockup](https://anitab-org.zulipchat.com/user_uploads/16723/uvNAUxnyTGnUq1hhHCNiNJFU/AnitaB_OS_Website-1st-Iteration.pdf)

### Update [Required]
- [ ] getting started doodle icon
- [ ] ways to contribute icon
- [ ] our projects icon
- [ ] open source programs
- [ ] all icons are kept in the same style

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[12] hours

**Comment by nandini45** [comment]
@annabauza  I had a question i will have to basically make the doodle and share them with you. nothing else??

**Comment by nandini45** [comment]
and what does style here?

**Comment by annabauza** [comment]
Good point, create PR to add them to this repo `/src/assets/` folder.

**Comment by nandini45** [comment]
and what does style mean here?

**Comment by annabauza** [comment]
it is up to you but they all need to be consistent

**Comment by nandini45** [comment]
i had a suggestion if vuyanzi is working on it too we both can distribute our work like 2-2 each or we both can work on it that way we will have more suggestions to look through

**Comment by nandini45** [comment]
If you @annabauza @mayburgos  both agree to any one of my suggestions. i will willingly contribute to whatever you say.

**Comment by Vuyanzi** [comment]
> i had a suggestion if vuyanzi is working on it too we both can distribute our work like 2-2 each or we both can work on it that way we will have more suggestions to look through

I think to get a variety to choose from we could work on the four separately.

**Comment by mayburgos** [comment]
@nandini45 We can assign up to 10 people to the same issue, so we can receive multiple perspectives.

No to distributing the work because then the icons will not be consistent with the same style. 

If you do not feel comfortable working on the same issue as another contributor, we can un-assign you to this task. However, we will definitely keep this issue open and assign additional designers if they are interested.

**Comment by nandini45** [comment]
No I can work on it too.. @mayburgos 
I will share my designs too

**Comment by nandini45** [comment]
i was under the impression that a issue can only be assigned to only one user at a time🤣🤣.

**Comment by mayburgos** [comment]
@nandini45 I think we need to update our contributing guidelines to allow for multiple submissions for issues labeled "Category: User Interface" or any issues related to design. 🤔

**Comment by nandini45** [comment]
yeah.. we can update our contributing guidelines in all the repositories

**Comment by alpha2320** [comment]
@nandini45  so i have to work upon icons for homepage ? (just for clarification)

**Comment by Sonal240** [comment]
Hey, @mayburgos even I want to contribute, I am currently working on our project icon and have updated the landing page illustration too

**Comment by Vuyanzi** [comment]
@mayburgos and @annabauza can we keep pushing our drafts and fine-tuning while getting feedback from zulip. so that maybe by next week during our design session we can then have like final drafts for members to choose from. I have seen that the time allocated for this issue is 12 hours and its limiting someone's creativity.

**Comment by nandini45** [comment]
@Sonal240  (simran right?) the four icons mentioned above. work on them to start. you can start with any of the four doodle icons and as Vuyanzi said  ask zulip for more reviews

**Comment by nandini45** [comment]
@alpha2320 (ashish right?) priorly that's one of the milestones we have to work on. if you want to work on it
 i have to ask the admins if being on the coding team can i assign you and @Sonal240  this issue
and @Vuyanzi  sorry i did it by mistake

**Comment by Vuyanzi** [comment]
> @alpha2320 (ashish right?) priorly that's one of the milestones we have to work on. if you want to work on it
> i have to ask the admins if being on the coding team can i assign you and @Sonal240 this issue
> and @Vuyanzi sorry i did it by mistake

sorry for what @nandini45 ?

**Comment by nandini45** [comment]
i unassigned you for a sec by mistake

**Comment by alpha2320** [comment]
@nandini45  you guessed it right its ashish ....also if its not urgent and also if it has also been assigned to someone else its okay !

**Comment by nandini45** [comment]
@alpha2320  even i thought so but May told me a user interface issue can be assigned to maximum 10 people. so we still have many people who are willing and can help us out.
