### ISSUE TITLE
Content: 4 short descriptions needed to add in homepage.

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#39]
## Description
As a Developer,
I need to have 4 descriptions (getting started, ways to contribute, our projects, open source programs),
so that I can place them in homepage following the agreed mockup.

## Mocks
[Agreed mockup](https://anitab-org.zulipchat.com/user_uploads/16723/uvNAUxnyTGnUq1hhHCNiNJFU/AnitaB_OS_Website-1st-Iteration.pdf)

### Update [Required]
- [ ] `getting started` short descriptions
- [ ] `ways to contribute` short descriptions
- [ ] `our projects` short descriptions
- [ ] `open source programs` short descriptions

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[3] hours

**Comment by gaurivn** [comment]
@annabauza , I'd like to work on this issue.

**Comment by vj-codes** [comment]
@annabauza Can I work on this issue?

**Comment by AyushSatyam** [comment]
Hello @annabauza, I want to work on this issue

**Comment by annabauza** [comment]
@gaurivn this is first time issue for content team, you are currently working on other issue. I'm assigning this issue to next in queue @vj-codes.

**Comment by vj-codes** [comment]
heyy @annabauza should the PR be a text doc along with a mockup ?

**Comment by annabauza** [comment]
hi @vj-codes, sorry just saw your message. Can you create content under src folder and add home_content.json file and put it there? Thank you!

**Comment by garimasingh128** [comment]
@annabauza Hey this is my first time contributing to this project. Can I work on this issue as we can have multiple alternatives to the content?

**Comment by annabauza** [comment]
yes totally please work on this  @garimasingh128

**Comment by vj-codes** [comment]
> @vj-codes how it's going?

Almost done, will send a PR today! @annabauza

**Comment by annabauza** [comment]
Can someone from @anitab-org/content-team help here just saw @vj-codes does not belong to content team. Thanks!

**Comment by mitchell-frost** [comment]
Is this already closed? If not, can i work on this?
