### ISSUE TITLE
Integrate react native navigation

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#42]
### Is your feature request related to a problem? Please describe.
We want to have ability to build navigation stacks so we can build mobile versions later.

### Describe the solution you'd like
Integrate [React Native Navigation package](https://reactnavigation.org/docs/getting-started)

### Describe alternatives you've considered
Using other packages or implement own navigation stacks

### Additional context
Each menu tab should have own stack so we can go back from nested pages.

**Comment by annabauza** [comment]
@anitab-org/coding-team anyone interested?

**Comment by mitchell-frost** [comment]
I am new here...can I work on this?

**Comment by saurabhkanswal** [comment]
@mitchell-frost sure, go ahead.

**Comment by mitchell-frost** [comment]
@saurabhkanswal  On it!

**Comment by mitchell-frost** [comment]
It would be really helpful if someone could give me a hint about where to start as I am new here.

**Comment by nandini45** [comment]
@mitchell-frost  Are you a first timer ??
that is you have you ever solved  a issue beforehand in this repository?

**Comment by gaurivn** [comment]
@nandini45 , yes this issue assignee is indeed a first timer, you can check that [here](https://github.com/anitab-org/anitab-org.github.io/graphs/contributors) and [here](https://github.com/anitab-org/anitab-org.github.io/pulls).

**Comment by nandini45** [comment]
but this isnt a first timer issue.. so she is not allowed to work right?
@gaurivn

**Comment by gaurivn** [comment]
No, first timer issues can only be assigned to first timers, not the other way round. As a first timer to VMS, Mentorship Backend I worked on the non first timer issues. Let's focus on helping this issue assignee solve this issue for now.

**Comment by mitchell-frost** [comment]
@nandini45  @gaurivn Yes, I am a first timer. So, I need help to get started or is it not allowed for me to work on this?

**Comment by gaurivn** [comment]
> No, first timer issues can only be assigned to first timers, not the other way round. As a first timer to VMS, Mentorship Backend I worked on the non first timer issues. Let's focus on helping this issue assignee solve this issue for now.

@mitchell-frost , there are no first timer issues (for this repository), and this issue is assigned to you. Please feel free to work on it. If you have doubts or get stuck anywhere, do ask here and anyone from @anitab-org/coding-team or anyone who knows how to solve this issue will help you.

**Comment by mitchell-frost** [comment]
@gaurivn I will start working on this. Any tips on where to start?

**Comment by nandini45** [comment]
@mitchell-frost  you are working on this issue or any  other issue,?
Focus on only one issue

**Comment by nandini45** [comment]
@mitchell-frost  and if you are working on this issue.. you have to integrate react native navigation.. create a file in the code through which you  can install the dependencies in this project and  write the code

**Comment by mitchell-frost** [comment]
@nandini45 I will work on this issue. I will start by setting it up locally. Thanks!

**Comment by mitchell-frost** [comment]
@nandini45 @gaurivn  I have set it up locally and I have installed the react native dependencies. The dependencies are added in the package.json file. Is that okay? or do I need to create another file?

**Comment by saurabhkanswal** [comment]
@mitchell-frost any update? or if get stuck please let me know.

**Comment by gaurivn** [comment]
> @nandini45 @gaurivn I have set it up locally and I have installed the react native dependencies. The dependencies are added in the package.json file. Is that okay? or do I need to create another file?

@saurabhkanswal , can you help @mitchell-frost with this

**Comment by saurabhkanswal** [comment]
@gaurivn sure 💯  
@mitchell-frost please go through this doc - > https://reactnavigation.org/docs/getting-started
it has all the information you need.

**Comment by mitchell-frost** [comment]
@saurabhkanswal  thanks!

**Comment by annabauza** [comment]
@mitchell-frost is this issue in progrees?

**Comment by mitchell-frost** [comment]
@annabauza I am adding in the changes to the code. Will open a pull request shortly.

**Comment by mitchell-frost** [comment]
@saurabhkanswal after navigating to a particular page, I think only that should be displayed in the header along with a go back button redirecting to the home page right?

**Comment by mitchell-frost** [comment]
@saurabhkanswal I am a little confused. Should I create the Home function and the corresponding functions for the different pages as stacks and then create their stacks? What do I do with the MenuItem function inthe header? Also, should i change the look of the header on every page?

**Comment by annabauza** [comment]
each page should have own stack and after going to sub page I think we we should leave top and just add back button. Thanks @mitchell-frost

**Comment by mitchell-frost** [comment]
thanks @annabauza

**Comment by saurabhkanswal** [comment]
hey, @mitchell-frost sorry for the unavailability 😃 
Any update on this issue?
please let me know if you find this issue a little bit hard as a first-timer, also you can check other issues. We love to you to help you 😄

**Comment by saurabhkanswal** [comment]
unassign @mitchell-frost as there is no response.

**Comment by saurabhkanswal** [comment]
@anitab-org/coding-team anyone?

**Comment by sakshi1499** [comment]
@anitab-org/coding-team Please take up this issue

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by vj-codes** [comment]
Assigning you @gaurivn 
Happy coding!

**Comment by gaurivn** [comment]
I had faced the error (screenshot below), tried solving it following [this post](https://peterthaleikis.com/posts/how-to-fix-throw-er-unhandled-error-event.html) but the same error persists. Can anyone help solve this error
![integrate_react-nav_err](https://user-images.githubusercontent.com/48416306/87611508-4c833b00-c719-11ea-80a4-ed6c2abf58bb.png)

**Comment by mitchell-frost** [comment]
> hey, @mitchell-frost sorry for my unavailability 😃
> Any update on this issue?
> please let me know if you find this issue a little bit hard as a first-timer, also you can check other issues. We love to you to help you
> But if the things are done and you are about to create PR then just ignore the above line ⬆️ 😄

I am really sorry for the delay. Yes, it was tough for me and hence, I could not open a PR. I will look for other issues :)

**Comment by nandini45** [comment]
@gaurivn  are u working on it?

**Comment by gaurivn** [comment]
Yes I am working on it

**Comment by gaurivn** [comment]
I don't have the bandwidth to complete this atm ... something came up with work, making it available

**Comment by saideepesh000** [comment]
@nandini45, @sakshi1499, @annabauza, Can I work on it.

**Comment by saideepesh000** [comment]
@gaurivn, @annabauza, @nandini45, @sakshi1499, (Just to be clear)I need to integrate 'ABOUT US', 'PROGRAMS', 'PROJECTS', 'EVENTS', 'CONTRIBUTE', in a stack navigator(according to the React Navigation).

**Comment by saideepesh000** [comment]
> 
> 
> @gaurivn, @annabauza, @nandini45, @sakshi1499, (Just to be clear)I need to integrate 'ABOUT US', 'PROGRAMS', 'PROJECTS', 'EVENTS', 'CONTRIBUTE', in a stack navigator(according to the React Navigation). Should I create those screens.

Actually, according to the file structure, there are no separate components for those pages('ABOUT US,..'), but either [React Navigation](https://reactnavigation.org/) or [React-Router-Native](https://reactrouter.com/native/guides/quick-start) need individual components to use the navigation( <Route path={/path`} component={Topic} />).

**Comment by sakshi1499** [comment]
@saideepesh000 Those screens are being created through other PRs in the web format. For now, you have to integrate [this](https://reactnavigation.org/docs/getting-started/) & Each menu tab should have its own stack so we can go back from nested pages.

**Comment by saideepesh000** [comment]
@sakshi1499, @gaurivn, @nandini45, @annabauza, Once review this [codesandeboxlink](https://codesandbox.io/s/interesting-khayyam-vkyi8?file=/src/Navigation.js)(This may load slowly), I am going to change if we use "tab navigator".

**Comment by annabauza** [comment]
Yes we want tab navigator so we can reuse it in native app

**Comment by saideepesh000** [comment]
> 
> 
> Yes we want tab navigator so we can reuse it in native app

@annabauza, Is the "Navigation.js"([codesanbox](https://codesandbox.io/s/interesting-khayyam-vkyi8?file=/src/Navigation.js)) file what we want. I mean is that correct.

**Comment by annabauza** [comment]
Are you talking about linked [document](https://reactnavigation.org/docs/getting-started/) ?

**Comment by saideepesh000** [comment]
> 
> 
> Are you talking about linked [document](https://reactnavigation.org/docs/getting-started/) ?

@annabauza, No, This one -> [Project](https://codesandbox.io/s/interesting-khayyam-vkyi8?file=/src/Navigation.js). Is this what we want for the mobile version. Review this, I would make changes if any.

**Comment by annabauza** [comment]
but we should be able to use it on web as well right?

**Comment by saideepesh000** [comment]
@annabauza, why can't we use react-router-native for react-native version & react-router-web for the web version?. Like this
`import React from 'react'
import { Platform } from 'react-native'

let Router
if (Platform.OS === 'web') {
  Router = require('react-router-dom').BrowserRouter
} else {
  Router = require('react-router-native').NativeRouter
}`

**Comment by annabauza** [comment]
router will not work with static pages unfortunitely.

**Comment by saideepesh000** [comment]
@annabauza, Then, should I try like this [article on react-navigation on the web](https://codersera.com/blog/how-to-do-navigation-in-react-native-web-in-2020/)

**Comment by annabauza** [comment]
Maybe I'm wrong with router, can you please deploy on your repo static github page and test it?

**Comment by saideepesh000** [comment]
@annabauza, [react-router example](https://codesandbox.io/s/react-router-basic-d3wix?file=/example.js)

**Comment by annabauza** [comment]
Code sandbox is not github static pages environment. Can you please check on the same environment we deploy to?

**Comment by saideepesh000** [comment]
@annabauza, When trying to deploy it on Github pages this error has occurred, I searched it online but couldn't find the solution, could you help me with this. If you want the repository -> [repository](https://github.com/saideepesh000/react-router-demo/) 

![Screenshot (253)](https://user-images.githubusercontent.com/43727167/89550180-ef197000-d826-11ea-80ea-f61a59cab3cf.png)

**Comment by annabauza** [comment]
Have you added this package to package.json?

**Comment by saideepesh000** [comment]
> 
> 
> Have you added this package to package.json?

@annabauza, which package, "gh-pages"?, please go through the repo if you have time.

**Comment by annabauza** [comment]
Router

**Comment by annabauza** [comment]
React-routed-basic

**Comment by saideepesh000** [comment]
> 
> 
> Router

@annabauza, yes, added.

**Comment by saideepesh000** [comment]
> 
> 
> React-routed-basic

@annabauza, Actually, React-router-basic is the name of the folder for this app -> [react-router-demo](https://github.com/saideepesh000/react-router-demo/)

**Comment by annabauza** [comment]
You can try to connect it to Travis and merge to your repo master, this will kick a build from Travis. You just need to add personal token to Travis settings and setup github pages to use master. Not sure if it help, but this has to be tested against github pages before we move forward with this code.

**Comment by saideepesh000** [comment]
@annabauza, It's not working, can I leave this issue for now and work on some other issues, I apologize for taking up this issue and wasting your time.

**Comment by annabauza** [comment]
You can take any other issue if that one is too hard. You are not waisting my time at all. I think you are close, just have challenges to solve.

**Comment by annabauza** [comment]
If you decide to drop maybe you want to keep your changes for others. Thanks

**Comment by saideepesh000** [comment]
@annabauza, this issue is now available.

**Comment by Bucky25** [comment]
can i give it a try @Akanksha1212

**Comment by gaurivn** [comment]
Assigning you @Bucky25

**Comment by Bucky25** [comment]
@gaurivn i am working on this issue and i think it will take a lot of time guys .

**Comment by gaurivn** [comment]
@Bucky25 , it is perfectly fine so long as you post an update here regarding progress on the issue every 3 days, all the best.

**Comment by Bucky25** [comment]
@gaurvin @annabauza to integrate react native nav in app either we have to add header and footer in all components as they cannot be rendered differently in app.js under the view component because then we can not change screens through react-navigation so what's are ur suggestions regarding this

**Comment by nandini45** [comment]
@annabauza  can you help him out here?
this is pending from a long time?

**Comment by annabauza** [comment]
Closing because we move to react js

**Comment by nandini45** [comment]
@annabauza  ok .
thank you

**Comment by nandini45** [comment]
@Bucky25  thank you for your work. As Anna mentioned we are closing this issue.
