### ISSUE TITLE
Mobile Resposive Issue

### ISSUE THREAD

**Issue by Yashank18** [anitab-org/anitab-org.github.io#45]
### Describe the bug
When the Social media page is opened in the Mobile view, the page isn't responsive.

### To Reproduce
1. In mobile view
2. Go to Social Media Page
3. Scroll right

### Expected behavior
Data should not flow out so that there is no responsiveness issue

### Screenshots
![Screenshot (162)](https://user-images.githubusercontent.com/46098062/81724200-99406080-94a1-11ea-94b4-2b56c584fa16.png)

### Desktop (please complete the following information):
 - OS: Windows
 - Browser Chrome
 - Version 81.0.4044.138 (Official Build) (64-bit)

### Smartphone (please complete the following information):
 - Device: iPhone X
 - Browser: Chrome

### Additional context
Will like to work on this issue

**Comment by saurabhkanswal** [comment]
hey @Yashank18, thanks for the issue
but  you are raising a issue in wrong repository. 
this repository is for anitaBorg open source (https://anitab-org.github.io). 
btw you can look at other open issues also.   
thanks
