### ISSUE TITLE
Content: 4 short descriptions needed to be added in the about us page

### ISSUE THREAD

**Issue by nandini45** [anitab-org/anitab-org.github.io#46]
### **Description**
As a Developer,
I need to have descriptions (our history, our mission. about anitab.org & Meet our open source community),
so that I can place them in About us page following the agreed mockup.
you can check the design here(https://xd.adobe.com/view/34329ed1-3736-4657-767b-203765c85ada-4203/)

### **Mocks**
Agreed mockup
### **Update [Required]**
- [ ]  our mission short descriptions
- [ ]  about anitab.org short descriptions
- [ ]  our history short descriptions
- [ ]  Meet our open source community

### **Definition of Done**

- [ ]  All of the required items are completed.
- [ ]  Approval by 1 mentor.

### **Estimation**
[3] hours

**Comment by gaurivn** [comment]
I would like to work on this issue.

**Comment by annabauza** [comment]
@gaurivn - haven't you got any in progress issues atm?

**Comment by gaurivn** [comment]
No @annabauza , I mean I would want to be unassigned from the other issue, please can I unassign myself from the other one

**Comment by nandini45** [comment]
@annabauza  these issue are meant solely for the content team or the coding team can also work on it??

**Comment by sakshi1499** [comment]
@nandini45 I think we should let the content team handle it, Gauri can probably help them in it.

**Comment by nandini45** [comment]
that is what i was asking. is she on the content team?
@sakshi1499

**Comment by nandini45** [comment]
gauri*

**Comment by sakshi1499** [comment]
@nandini45 We can directly ask for the content team, if she is there already she can work on it. I am not sure if she is on the content team. 🤔

**Comment by nandini45** [comment]
i think she is on the coding and the design team. but even i am not sure.

**Comment by nandini45** [comment]
i think you are right we can tag the content team. there are few issues for them to work on

**Comment by abha224** [comment]
@nandini45 The mock-up actually includes a sentence under "Meet our open source community" as well. Could you pls add it to this issue, as most of the things are covered in it?

**Comment by nandini45** [comment]
@abha224  this a content issue for the about us page. not a coding issue

**Comment by abha224** [comment]
@nandini45 I understand that this is a content issue, and that's why I suggested that in the issue we include another description, ie, a description for Meet our open source community.

**Comment by nandini45** [comment]
i misinterpreted your words. i will change edit the issue @abha224

**Comment by abha224** [comment]
@nandini45 That's alright! :blush:

**Comment by annabauza** [comment]
can I have someone from @anitab-org/content-team to take this issue please?

**Comment by foongminwong** [comment]
hey @annabauza  I am one of the members from content team. You can assign to me

**Comment by foongminwong** [comment]
thank you @sakshi1499 !~

**Comment by foongminwong** [comment]
hi @nandini45 I was trying to view the design by clicking the link that you attached in this issue, but it requires a password. Do I need to know the password to view the About Us design in order to create the descriptions or it will be fine if I don't view the design template? 🤔

**Comment by nandini45** [comment]
@foongminwong  now when it is also asking me for a password. although you can create the description without viewing the design but still once if you need you can view it. i will send you the password or the screenshots of the design

**Comment by nandini45** [comment]
however. now when i am trying to access it is asking for a password. although you can create the description without viewing the design but still once if you need you can view it. i will send you the password or the screenshots of the design
@foongminwong

**Comment by nandini45** [comment]
meanwhile you can write the description. i will ask Sonal for the password or i think i will just post the screenshot of the design here

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/82837394-88064380-9ee6-11ea-8d45-c169ee8fff76.png)
here is the design

**Comment by foongminwong** [comment]
The screenshot clears up what kind of descriptions that you're expecting! Just created a pull request but I'll need to modify some of the contents to match the design mockup :)

**Comment by Sonal240** [comment]
I've redesigned the page according to the web metrics that was discussed(currently under review)  and as there were 2 links for design review I had deleted one...the content remains the same though...
