### ISSUE TITLE
Content: Add descriptions for each project in Projects page

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/anitab-org.github.io#47]
## Description
As a developer,
I need to see each project described briefly,
so that I can add them to Projects page following [this design](https://xd.adobe.com/view/5a5a8a52-a713-4d60-6bd5-536dfb21c2ae-2c6b/).

### Update [Required]
Added brief descriptions for
- [ ] mentorship-android
- [ ] mentorship-backend
- [ ] mentorship-ios
- [ ] portal
- [ ] vms
- [ ] anitab-org.github.io
- [ ] bridge-in-tech-web
- [ ] bridge-in-tech-backend
- [ ] open-source-programs-web
- [ ] open-source-programs-backend
- [ ] stem-diverse-android-tv 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3 hours

**Comment by annabauza** [comment]
@gaurivn can you list all our active projects as check list?

**Comment by gaurivn** [comment]
Sure, will do

**Comment by annabauza** [comment]
Missing Bridge in Tech, Open Source Programs, Stem Diverse TV

**Comment by vardhinipawar** [comment]
Can I work on this?

**Comment by gaurivn** [comment]
Sure @vardhinipawar :)

**Comment by vardhinipawar** [comment]
@gaurivn so I just have to find the definition of required terms?

**Comment by gaurivn** [comment]
Yes @vardhinipawar , for some projects, "Description" under respective github repos would do, for the others, please check out their "README" and frame them.

**Comment by vardhinipawar** [comment]
@gaurivn 

•	mentorship-android: 
•	 mentorship-backend: 
•	  mentorship-ios:
•	  portal: A World Wide Web site that is or proposes to be a major starting site for users when they get connected to the Web or that users tend to visit as an anchor site. 
•	  vms: Virtual Memory System used to operate digital equipment. 
•	  anitab-org.github.io: Open Source 
•	  bridge-in-tech: A type of computer network device that provides interconnection with other bridge networks that use the same protocol. 
•	  open-source-programs: A type of computer software in which source code is released under a license in which the copyright holder grants users the right to study, change, and distribute the software to anyone and for any purpose. 
•	  stem-diverse-android-tv:

**Comment by gaurivn** [comment]
VMS
AnitaB.org has many volunteers that offer their skills, time, and commitment to our vision and projects. The Volunteer Management System (VMS) will be useful for volunteer coordinators, volunteer sign-up, tracking hours, and reporting. This project uses the Django web framework and Python.

Like this one, it would be better to include a line that tells languages and/or frameworks used.
@annabauza please tell where the descriptions should be added.

**Comment by gaurivn** [comment]
@vardhinipawar , please refer [this](https://github.com/anitab-org/anitab-org.github.io/issues/39) for the location to add the descriptions for the Projects page.

**Comment by vardhinipawar** [comment]
@gaurivn I am not quite sure? Also, can you please tell me the purpose of the project? Along with with tools are used for this project?

**Comment by gaurivn** [comment]
@vardhinipawar , sorry for the delay, please ignore [previous comment](https://github.com/anitab-org/anitab-org.github.io/issues/47#issuecomment-632930229). I guess this issue can only be taken up by @anitab-org/content-team (as mentioned [here](https://github.com/anitab-org/anitab-org.github.io/issues/46)) , however you can help by suggesting descriptions for projects but no need to place them anywhere or send a pull request (for now). These projects are hosted [here](https://github.com/anitab-org). Please go through their README and Description, you'll find the purpose and tools, frameworks etc there.

**Comment by annabauza** [comment]
@vardhinipawar there should be file created under `src/content/projects_content.json` and this should contains structure at follows:
```
{
  "sections": [
    {
      "title": "First section title",
      "content": [
        {
          "par": "The AnitaB.org community is a fusion of rich values and diverse cultures consisting of members all across the seven oceans with a fearless mission of inspiring ,motivating and helping women with their involvement in technical fields and has made a significant impact with regards to contribution of women in tech.The other values of the organization include Accountable, Agile, Curious, Courageous, & Diversity, Equity, Inclusion (DEI), encourage everyone to follow the org’s contributing guidelines and obviously passion for open source."
        },
        {
          "par": "Zulip is our main communication platform and you should join us there and first give a short introduction about yourself in the #newcomers stream.Zulip consists of various streams like Documentation,Coding,Design,etc and the one that fascinates you the most is the one you should start contributing in.The #announcements stream will be displaying all the important announcements.Ttag our community members if there's any confusion or ask for proper guidance from them regarding your contributions to the community."
        }
      ]
    },
    {
      "title": "Next section title",
      "content": [
        {
          "par": "The AnitaB.org community is a fusion of rich values and diverse cultures consisting of members all across the seven oceans with a fearless mission of inspiring ,motivating and helping women with their involvement in technical fields and has made a significant impact with regards to contribution of women in tech.The other values of the organization include Accountable, Agile, Curious, Courageous, & Diversity, Equity, Inclusion (DEI), encourage everyone to follow the org’s contributing guidelines and obviously passion for open source."
        },
        {
          "par": "Zulip is our main communication platform and you should join us there and first give a short introduction about yourself in the #newcomers stream.Zulip consists of various streams like Documentation,Coding,Design,etc and the one that fascinates you the most is the one you should start contributing in.The #announcements stream will be displaying all the important announcements.Ttag our community members if there's any confusion or ask for proper guidance from them regarding your contributions to the community."
        },
        {
          "par": "Zulip is our main communication platform and you should join us there and first give a short introduction about yourself in the #newcomers stream.Zulip consists of various streams like Documentation,Coding,Design,etc and the one that fascinates you the most is the one you should start contributing in.The #announcements stream will be displaying all the important announcements.Ttag our community members if there's any confusion or ask for proper guidance from them regarding your contributions to the community."
        }
      ]
    }
  ]
}
```

**Comment by mitchell-frost** [comment]
Is this issue open or closed? I would like to work on this.

**Comment by gaurivn** [comment]
@vardhinipawar , how is the progress... please give us an update.

**Comment by gaurivn** [comment]
@annabauza , I would like to work on this issue.

**Comment by sakshi1499** [comment]
@gaurivn Hey would you like to work on it still? I am assigning you. Thank you <3

**Comment by gaurivn** [comment]
I am currently working on it, will send a PR soon.

**Comment by annabauza** [comment]
@sakshi1499 you assigned @gaurivn while @vardhinipawar was next in the queue according to messages.. Let's make sure we keep the queue properly.

**Comment by sakshi1499** [comment]
@annabauza I thought of the 4 day no update rule. @vardhinipawar hadn't responded in 4 days, exactly why I went ahead and assigned @gaurivn

**Comment by sakshi1499** [comment]
I guess @mitchell-frost could have been made the next assignee. That's my fault, sorry :(

**Comment by annabauza** [comment]
Ient @mitchell-frost  😬

**Comment by sakshi1499** [comment]
@annabauza Haha, got it!! I am sorry will take extra care next time.

**Comment by gaurivn** [comment]
> @sakshi1499 you assigned @gaurivn while @vardhinipawar was next in the queue according to messages.. Let's make sure we keep the queue properly.

@annabauza, @sakshi1499 , I'm sorry I didn't notice the same before commenting here due to inactivity. I suggest @mitchell-frost be assigned this issue.

**Comment by gaurivn** [comment]
@mitchell-frost , would you like to work on this issue?
