### ISSUE TITLE
design: Improve projects page

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#50]
Improve [this design](https://xd.adobe.com/view/5a5a8a52-a713-4d60-6bd5-536dfb21c2ae-2c6b/)
- [x] **Projects section:** remove line between projects description 
- [x] **Projects section:** Replace card content with designs from [here](https://xd.adobe.com/view/80f2e4fb-75fb-4706-5d62-b72f70e5ce84-f6c3/)
- [x]  **Projects section:** Replace `view more` to be consistent alignment (left or right)
- [x] Make separator line 1px height and no dots on sides 
- [ ] **Major contributors:** change size of fonts to fit normal text
- [x] **Projects section:** weight of Projects description feels too heavy. is is medium or light?

**Comment by alpha2320** [comment]
![image](https://user-images.githubusercontent.com/58825698/82297857-e3a96c00-99d0-11ea-98d8-5ed17329354c.png)

**Comment by alpha2320** [comment]
![image](https://user-images.githubusercontent.com/58825698/82298436-bf9a5a80-99d1-11ea-9b23-da300ebc2d41.png)

**Comment by Vuyanzi** [comment]
Hey, @annabauza is it possible for whoever made the design to share it in a way that we can edit their designs, since redesigning this afresh will take time. Then I cant see the section major contributors, is it where we have the images of people? And the footer, are we having it as is? cause its different from the about us page footer, it would be nice if we had the same footer in the entire website.

**Comment by vardhinipawar** [comment]
Can I work on this?

**Comment by devRD** [comment]
@annabauza The navbar section in the mockup for the Projects page is different than the one in About Us page (referred to this [issue](#51)). Is this an inconsistency or will the navbar design be different for each section?

**Comment by Sonal240** [comment]
@devRD navbar is already developed and would remain the same...the design is finalized margin guidelines are in progress..the issue will be updated and will be available for development soon

**Comment by Sonal240** [comment]
In about us too no need to develop navbar as it is already developed...

**Comment by Abhishec177** [comment]
Can I work on this?

**Comment by alpha2320** [comment]
@Vuyanzi  it's in the google drive of anita.b design

**Comment by nandini45** [comment]
@Abhishec177  it is not available..those issues which have the label available are the ones which you can work on.

**Comment by annabauza** [comment]
Long time no action. Closing this issue.
