### ISSUE TITLE
Coding: Develop the following About Us Page 

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#51]
## Description
As a developer,
I need the following attached About Us mock-up to be implemented,
so that I can add it as an About Us Component [here ](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components).

## Mocks
(Only the section in the red box avoid navbar as it is already developed)
![about-us-part1](https://user-images.githubusercontent.com/49720151/85366642-65973280-b545-11ea-9493-68a047bf3861.png)

NOTE:
The horizontal lines in insights are downloadable assets..kindly go through design development link shared
The horizontal gutter between the lines mentioned above and the description (the one which is left aligned and next to it) is 16pt
The margin between heading and description: 8pt
Font Size for headings: Header Medium(32pt) weight- Medium 
Font Style-Avenir
Font Size for the description below including the learn more link: body 18pt weight- Light
Font Color (headings): #103B81
Font Color (Body): #103B81
Font Color (Learn More): #103B81

[Design Link for Development](https://xd.adobe.com/view/ba1323d0-760e-4f29-4658-c83848c894ba-cc22/)

### Update [Required]
- [ ] When a user clicks Learn More Link (below OUR HISTORY) redirect them[ here](https://anitab.org/about-us/mission-and-history/)
- [ ] When a user clicks Learn More Link (below ABOUT ANITA BORG) redirect them[ here](https://anitab.org/about-us/about-anita-borg/)
- [ ] When a user scrolls down to INSIGHTS a countUp effect should be implemented.
- [ ] Please go through the Development link shared with mock-up for margin guidelines, also the side image's height should extend till insights, as mentioned in mock-up and text, should be adjusted according to the image.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by nandini45** [comment]
@Sonal240  edit your issue add no of hours and other criteria.

**Comment by nandini45** [comment]
check issue #46 
you will know what to add and how

**Comment by annabauza** [comment]
@Sonal240 we want to spread it into 2 components. `Meet our open source community` and all above. I will add related issues then. We don't have issue for content of `Insights` and we don't have issue for description of `Meet our open source community`.

**Comment by annabauza** [comment]
@Sonal240 we need to give developer all insights - margins, fonts weight & sizing, colors, describe that size of image should be adjusted to text.

**Comment by Sonal240** [comment]
So what should I remove??

**Comment by annabauza** [comment]
@Sonal240 you need to split it into 2 and maybe put red rectangle which section this ticket is about, and same thing in 2nd issue you create. Thanks!

**Comment by Sonal240** [comment]
Ok on it...Thanks @annabauza

**Comment by devRD** [comment]
Hi, can I work on this issue?

**Comment by annabauza** [comment]
@Sonal240 this design is not complete information for developer, we need margins, paddings, font typography and colors used in this component. Please add this first, thanks!

**Comment by annabauza** [comment]
@Sonal240 Issue approved @devRD I have assigned you to the issue.

**Comment by annabauza** [comment]
@Sonal240 we need to align this to fit latests metrics agreements. Thanks!

**Comment by Sonal240** [comment]
on it @annabauza,

**Comment by mitchell-frost** [comment]
If this is open, can I work on this?

**Comment by adi-001** [comment]
@mitchell-frost  yes you can, also keep us in loop about your progress

**Comment by adi-001** [comment]
> If this is open, can I work on this?

I'm assigning it to you

**Comment by mitchell-frost** [comment]
@Sonal240 the design link for development isn't working?

**Comment by nandini45** [comment]
@devRD is already working on this issue and @mitchell-frost  you are already assigned another issue..  you can't work on two at the same time.. complete the first one

**Comment by adi-001** [comment]
@nandini45  there's no harm if @mitchell-frost  is willing to work two issues at the same time, also if she is unable to work then she will update us

**Comment by adi-001** [comment]
@mitchell-frost are you willing to work on this issue? 
If yes then I can assign it to you

**Comment by devRD** [comment]
@adi-001 Yes, I'm currently working on this.

**Comment by nandini45** [comment]
@annabauza i had a question  can a first timer work on two issues at the same time??

**Comment by nandini45** [comment]
Now i don't think so @adi-001 that a coding issue can be assigned to two people at the same time??
Just correct me if i am wrong??

**Comment by adi-001** [comment]
> Just correct me if i am wrong?
Hush also I haven't heard anyone telling if there would be any fuss, 
Anyways lets clear it in next bi-weekly meet

**Comment by Sonal240** [comment]
The design was again put under review as we all are developing the metric guidelines so I have deleted the design link...
I'll update the issue once the design gets approved again

**Comment by nandini45** [comment]
@adi-001  i apologize for sounding rude. 
there are some rules which are to be maintained. those contribution guideline will be updated soon.

**Comment by adi-001** [comment]
> @adi-001 i apologize for sounding rude.
> there are some rules which are to be maintained. those contribution guideline will be updated soon.

Never mind 😙
And @nandini45  yes coding issue can't be assigned to two people, my bad

**Comment by annabauza** [comment]
@devRD how is it going?

**Comment by devRD** [comment]
@annabauza The design was being re-evaluated and the issue was on hold. I'll soon work on this and send a PR. :)

> The design was again put under review as we all are developing the metric guidelines so I have deleted the design link...
> I'll update the issue once the design gets approved again

**Comment by devRD** [comment]
@annabauza @anitab-org/coding-team I had a quick question about the setup as I am a bit new to `react-native-web`. How to add media queries for the mobile view of the page? 
It looks like this at the moment. Any help regarding how to proceed further would be appreciated. :)

![Screenshot_AnitaBorg_open_source](https://user-images.githubusercontent.com/35831931/83969635-ac9eea00-a8ee-11ea-994a-8f3f1bb2fbc7.png)

**Comment by Sonal240** [comment]
@devRD are you using Avenir Font... ,coz it doesn't seem so

**Comment by Sonal240** [comment]
@devRD can you add an green color triangle as overlay as mentioned in the design 
Moreover the image should extend till last line of Insights.. Currently it is not

**Comment by annabauza** [comment]
Regarding the font not sure, it should come from style possibly we will need to attach the font in assets. I would Google it.

**Comment by devRD** [comment]
Hi @annabauza, the mentioned font 'Avenir' looks like a paid font, I think we wouldn't want to include a paid font into our open-source project. I would personally recommend using the font '[Nunito](https://fonts.google.com/specimen/Nunito?selection.family=Nunito:wght@200)', which is the closest alternative to 'Avenir' and is also freely available. What's your opinion about it?

**Comment by Sonal240** [comment]
I think the header too is using Avenir font if not then try using the same font as header @devRD

**Comment by devRD** [comment]
@Sonal240 I checked the font that I was using for the header section, turns out it was 'Avenir', thanks for mentioning it, I added the `font-family` for the rest. I would also suggest keeping a fallback font for the same in case the users' system doesn't have this font available.  :)

I tried correcting the margins accordingly and the top margin of `128pt` looks rather odd. Here's a screenshot for reference.

![Screenshot_AnitaBorg_open_source1](https://user-images.githubusercontent.com/35831931/84176069-8455ed80-aa9e-11ea-914e-3b911a655d28.png)

The image section uses `height: 996px` as mentioned and doesn't fit the whole text area, and also breaks, any suggestion on how to correct this? I've looked for a solution and couldn't find any. :/

I also thought I was mistaking the use of `pt` as `px` and I tried changing the `height` of the image to `996pt` and this is what I get: 

![Screenshot_AnitaBorg_open_source3](https://user-images.githubusercontent.com/35831931/84176635-4f966600-aa9f-11ea-9dd2-924073897229.png)

Although it kind of fits the text area, I think it should be more responsive than this. Any idea on how to proceed with it? 

One more query I had regarding this was about the green triangle overlay over the image. Since `react-native` doesn't use the CSS property `clip-path`, I found the library for SVG in `react-native` called the `react-native-svg`, should I go ahead and use that?

**Comment by Sonal240** [comment]
Have you read this [npm package](https://www.npmjs.com/package/react-native-image-overlay) which deals with having an overlay over the images @devRD if this does not give fruitful output go ahead with react-native-svg
I'll figure out something for other points that you've mentioned and revert back to you

**Comment by Sonal240** [comment]
@devRD instead of using an API to convert given pt values can you directly use them in your code, considering dp=pt like padding:32...I know pt!=dp, but still just want to see how things look...another thing the image extends only till the last line of INSIGHTS section

**Comment by Sonal240** [comment]
I found an interesting [article](https://codedaily.io/tutorials/22/The-Shapes-of-React-Native) that deals with creating polygons without using any react library may you go through it else try using react shapes for the same...first try making the polygon responsive keeping in mind the margins that it should maintain from the text fields...

Another[ article on using clip-path for responsive polygons](https://www.smashingmagazine.com/2015/05/creating-responsive-shapes-with-clip-path/) hope it helps

**Comment by Sonal240** [comment]
As we are developing it on react-native mobile responsiveness should not be an issue..earlier even I thought that we should provide developers with a mobile view of pages but @annabauza explained to me this point...

Convert px to pt first and then assign the values for all fields like padding: 32, height: 747 like that...

Another query...Is the polygon responsive??

Few links that you may go through:
[How to put an image in a polygon](https://github.com/react-native-community/react-native-svg/issues/1111)
[react-native-shape-image-view package](https://www.npmjs.com/package/react-native-shape-image-view)
[responsive image in react-native](https://www.skptricks.com/2018/09/react-native-responsive-image-example.html)

**Comment by Sonal240** [comment]
how's it going @devRD ??

**Comment by devRD** [comment]
Hi, @Sonal240, Can I make a WIP PR so that you can take have a proper look at the code? Maybe I'm messing up somewhere.

**Comment by Sonal240** [comment]
ok @devRD

**Comment by devRD** [comment]
It kind of looks like this at the moment, although the image is responsive now, it dynamically contains the respective image width and height in different screen sizes. :confused: 

![Screenshot_AnitaBorg_open_source5](https://user-images.githubusercontent.com/35831931/84596220-0d439f00-ae7a-11ea-83cd-84c28ae990e6.png)

**Comment by Sonal240** [comment]
Looks good...Can you start the image from OUR MISSION and extend it till the last line if INSIGHTS as mentioned in the mock given in issue?? and adjust the overlayed triangle as well...thanks

**Comment by Sonal240** [comment]
How is it going? are you done with the issue @devRD ? May you submit a pr for the same...thanks

**Comment by Sonal240** [comment]
@devRD kindly see the issue again and do the required changes in the code and update it here...thanks

**Comment by devRD** [comment]
@Sonal240 I have made a WIP pull request, please feel free to go through the code and the needed modifications for the same.

**Comment by sakshi1499** [comment]
@devRD Are you still working on it? You closed the PR.

**Comment by nandini45** [comment]
@sakshi1499  he said he cant work on it. so i think we should reopen it. or you can ask him if anything we can do to help him out

**Comment by sakshi1499** [comment]
@nandini45 Actually the issue was assigned and also labelled as available. I might have missrd comments by him, where he said he won't work on it. So yes, you can unassign him then.

**Comment by nandini45** [comment]
![image](https://user-images.githubusercontent.com/62046625/87884801-6b8e0f80-ca2e-11ea-86d9-8284e9929fd1.png)

**Comment by saideepesh000** [comment]
@nandini45, @sakshi1499, @annabauza, is [this](https://xd.adobe.com/view/ba1323d0-760e-4f29-4658-c83848c894ba-cc22/specs/) the final design, can I work on this.

**Comment by saideepesh000** [comment]
@annabauza, @Sonal240 should I use "SectionSubHeader" component for titles like "OUR MISSON", "OUR HISTORY", "ABOUT ANITA BORG", "INSIGHTS".

**Comment by annabauza** [comment]
Yes

**Comment by saideepesh000** [comment]
@annabauza, @Sonal240, @sakshi1499, For content, Should I follow the [design ](https://xd.adobe.com/view/ba1323d0-760e-4f29-4658-c83848c894ba-cc22/specs/), or the content/about_us.json, because both have got different content. And the styling of the "SectionSubheader" component doesn't match with the design.

**Comment by sakshi1499** [comment]
@saideepesh000 Follow about_us.json for content. The design has dummy content.

**Comment by Sonal240** [comment]
@saideepesh000 follow section subheader...I had updated the design accordingly long ago when it was discussed. Try working on the image thing first after a dummy set-up because that's the most tricky part of this section...thanks

**Comment by saideepesh000** [comment]
@annabauza, @Sonal240, @sakshi1499, Are we going to use this library for responsiveness [react-native-web-responsive](https://www.npmjs.com/package/react-native-web-responsive)

**Comment by Sonal240** [comment]
So far the issues that I have been following...the assignees have not used this library(they might have tried at their end)... They have used Platform OS etc for responsiveness... You may give that lib a try... 
@sakshi1499 @annabauza what do you say?

**Comment by 19-pragya** [comment]
If it is open can i work on this issue

**Comment by saideepesh000** [comment]
@Sonal240, @annabauza  Is this fine.
![Screenshot (261)](https://user-images.githubusercontent.com/43727167/90018539-b405b980-dcca-11ea-9763-1242d0ac3ae3.png)

Was trying with responsiveness, I think Platform==='web' doesn't work for 'web' according to the [RN docs](https://reactnative.dev/docs/platform-specific-code), now trying with some external modules for responsiveness, can we use 'rem' for size because [react-native-web-example](https://codesandbox.io/s/q4qymyp2l6).

**Comment by Sonal240** [comment]
Make sure you don't use em for font size... For others give it a try 
Also the insights should have a count Up effect on Number mentioned 
So far it looks good to me... 
Share the responsive view once done.. Thanks

**Comment by saideepesh000** [comment]
@Sonal240, On the mobile screen either image should come first or the text part should come first, and both of them should be aligned column wise, right?

**Comment by Sonal240** [comment]
aligned column wise

**Comment by saideepesh000** [comment]
@Sonal240, Here's [Progress](https://drive.google.com/file/d/1g8uGJa0oJcr3jO-k7h1cVVedtBY-onAv/view?usp=sharing), I've used this package called [react-native-reflect](https://sntx.github.io/react-native-reflect/#/?id=single-style), it's super helpful for these kind of projects.

**Comment by Sonal240** [comment]
Hey,@saideepesh000  it looks great!! just few comments...
make sure the image extends till the last line of the insights section
also the trapezium looks a bit cut try to fix that...
regarding the mobile view, I'm not sure if it looks good, the image below the text...can you try not to shift the image below or up...keep it side by side ...in this case I think the user would need to zoom in ....@sakshi1499 what do you think? I had asked Anna for a mobile view design but she told me that it would be catered since we are developing on react native...or for the time being, let's approve this and later we can add a feature request?

**Comment by saideepesh000** [comment]
> 
> 
> Hey,@saideepesh000 it looks great!! just few comments...
> make sure the image extends till the last line of the insights section
> also the trapezium looks a bit cut try to fix that...
> regarding the mobile view, I'm not sure if it looks good, the image below the text...can you try not to shift the image below or up...keep it side by side ...in this case I think the user would need to zoom in ....@sakshi1499 what do you think? I had asked Anna for a mobile view design but she told me that it would be catered since we are developing on react native...or for the time being, let's approve this and later we can add a feature request?

@Sonal240, As a confirmation, should I send a PR with [this](https://drive.google.com/file/d/1g8uGJa0oJcr3jO-k7h1cVVedtBY-onAv/view?usp=sharing)(with changes mentioned above) or should I send the unresponsive code?

**Comment by Sonal240** [comment]
Put a pr with the video and I'll ask @sakshi1499 and @annabauza for reviews...Anna is busy right now so may be by next week or so your pr would get approved

**Comment by saideepesh000** [comment]
@Sonal240, Ya but which one should I send one with the responsive view(image going down on resize) or just the normal view

**Comment by Sonal240** [comment]
both responsive and web view
