### ISSUE TITLE
Coding: Design The Meet Our Open Source Community Part Of About Page

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#53]
## Description
As a developer,
I need the following mock-up to be implemented,
so that I can add as Open-Source Community Component [here](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components).

## Mocks
(Only the section in the red box to be developed)
![about-us-part2](https://user-images.githubusercontent.com/49720151/85365802-ad1cbf00-b543-11ea-927c-e54d90117a28.png)

Font Size for heading MEET OUR OPEN SOURCE COMMUNITY: Header Medium(32pt) weight- Medium
Font Size for the description below: body 18pt weight- Light
Font Style- Avenir
Font Color (heading): #103B81
Font Color (Body): #103B81

Margin between heading and description: 16pt
Image size: 81px X 81px
horizontal and vertical gutter between two images: 2px 
corner radius: 8px
Top margin of the entire image component on page: 1320px
image block size: height:310px ,width:1638px

[Design Development Link](https://xd.adobe.com/view/ba1323d0-760e-4f29-4658-c83848c894ba-cc22/)

### Update [Required]
- [ ] Instead of dummy images in MEET OUR OPEN SOURCE COMMUNITY, get GitHub profile images of all members and arrange them according to mock-up shared, also when a user hovers on a particular image redirect them to respective Github profiles.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by annabauza** [comment]
@Sonal240 footer is not part of this task

**Comment by Sonal240** [comment]
another issue for footer??

**Comment by annabauza** [comment]
I think we planned to add FAQ.

**Comment by annabauza** [comment]
we need specify:
- header: font + size + color + top margin
- description: font + size + color + top margin
- icons: sizing + vertical & horizontal gutters + top margin.
- bottom margin from highest section
- icons needs to be provided.

**Comment by mitchell-frost** [comment]
If this is open, I would like to work on this? I am new to open source and new here. I would love to start contributing.

**Comment by Sonal240** [comment]
Hey, @mitchell-frost it's good to have you here...We're currently working on margin guidelines...I'll update this issue by tomorrow once it gets approved it would be open for development...Thanks

**Comment by Sonal240** [comment]
@sakshi1499 can I proceed to assign the issue to @mitchell-frost ??
@mitchell-frost are you willing to take up this issue??

**Comment by nandini45** [comment]
@Sonal240  she is already working on some issue. you just put the label available

**Comment by Sonal240** [comment]
The issue is open for all

**Comment by anna4j** [comment]
@Sonal240 Can I work on this issue?

**Comment by sakshi1499** [comment]
@anna4j Sure

**Comment by Sonal240** [comment]
Thanks @sakshi1499

**Comment by anna4j** [comment]
@sakshi1499 currently there are 32 members in the member's list on the main GitHub page. 
Should I only include those members? Or is there another list?
If you could also tell me how many members to be placed per row and column, so I can accordingly work on the responsiveness
Thanks :)

**Comment by sakshi1499** [comment]
@anna4j If you go on the org page of AnitaB where you can see all the repositories, you'll see that there is a section named Members. I can see there are 100 members. I guess we can add them.

**Comment by anna4j** [comment]
@sakshi1499  I'm able to see only 32 :(

![image](https://user-images.githubusercontent.com/43845261/85569440-2dc8e180-b650-11ea-9a60-43057fe09ec0.png)

**Comment by anna4j** [comment]
@sakshi1499 I'm able to see only 32, could you look into this, please?

![image](https://user-images.githubusercontent.com/43845261/85570035-ab8ced00-b650-11ea-9175-f1b81fc37c71.png)

**Comment by Sonal240** [comment]
@anna4j Can you check out this link https://github.com/orgs/anitab-org/people

**Comment by sakshi1499** [comment]
@Sonal240 If you see the link in her screenshot, its the same as yours. I am not sure if all the members don't get visible for everyone. :/
Still @anna4j if you could confirm, it'll be of some help.

**Comment by anna4j** [comment]
@sakshi1499 The link that @Sonal240 sent also shows 32 members only

**Comment by Sonal240** [comment]
![Screenshot_20200624_202626](https://user-images.githubusercontent.com/49720151/85580050-062a4700-b659-11ea-9412-47e01785d923.png)
well it has arrow buttons for navigation below 
Same link @anna4j

**Comment by anna4j** [comment]
@Sonal240 It shows only 2 arrows and 32 members. Do I need to be added somewhere or something to see all members? Actually @isabelcosta had addressed this issue in yesterday's meeting, perhaps she knows what the issue is

**Comment by isabelcosta** [comment]
@anna4j I'm not sure what I can help you with. What is the question here?

**Comment by sakshi1499** [comment]
@isabelcosta Her question is asking about the reason why 32 members are visible to her and not 100.

**Comment by isabelcosta** [comment]
> @isabelcosta Her question is asking about the reason why 32 members are visible to her and not 100.

@sakshi1499 @anna4j I have no idea 🤔 I really don't. @mayburgos do you have any idea about this?

**Comment by sakshi1499** [comment]
@isabelcosta I think she hasn't been added as a member that is she hasn't been invited to the open source teams. I guess that is the reason, not sure though.

**Comment by gaurivn** [comment]
> ![Screenshot_20200624_202626](https://user-images.githubusercontent.com/49720151/85580050-062a4700-b659-11ea-9412-47e01785d923.png)
> well it has arrow buttons for navigation below
> Same link @anna4j

I think this is because these 32 members have made their member visibility as Public, the remaining are Private, if they too can change it to Public, it would be visible to @anna4j .

**Comment by anna4j** [comment]
@sakshi1499 I've already started work with the 32 members, but please do update me when you have any information about how I should go about it :)

**Comment by sakshi1499** [comment]
@anna4j Sure. I'll confirm and get back.

**Comment by vj-codes** [comment]
Heyy I can see all 100 members , you just have to check the remaining pages by clicking on pg no/next button at bottom.
Or
There's a role button on right of display bar click on that and select everyone .  @anna4j

**Comment by anna4j** [comment]
@vj-codes hi, were you by any chance recently added to OS teams? because that would explain why I can see 33 members now instead of 32, and you can see 100. If not nevermind :)

**Comment by vj-codes** [comment]
Ahh no I've been there since april but made my profile public few mins before.
Another thing I observed is when I'm on guest or incognito mode on chrome I see 33 members too.Just check if you have signed in on chrome and try again .Maybe it'll work . @anna4j

**Comment by anna4j** [comment]
@vj-codes I tried signing in again too! I think it's a matter of me not being a member. Because only members can see private and public members.

**Comment by anna4j** [comment]
@sakshi1499 hey! I'm almost done with code, just need to fetch images so if I could have an update since I can only see 34. I also had 2 questions:
1) if someone has not set a profile picture, what to do in that case?
2) should I write the corresponding em values for all the specifications that are mention in pixels, or should I move forward with pixel only?
thanks

**Comment by sakshi1499** [comment]
So I am not sure how many members we will have on the whole screen if only 50 are visible we can try and keep the people who have display picture otherwise we can keep even the ones who don't have picture. I'll talk to may today in my 1:1 about this issue and get back to you tonight okay?
So i think writing em values is better than writing pixels but @annabauza will be the best judge about that.

**Comment by Sonal240** [comment]
@anna4j We are discussing the point that you've raised  so I have put it on hold, it will be open soon once we get a clear picture...thanks

**Comment by mayburgos** [comment]
> @anna4j If you go on the org page of AnitaB where you can see all the repositories, you'll see that there is a section named Members. I can see there are 100 members. I guess we can add them.

Actually, it doesn't show if the member hasn't added it to their profile.

**Comment by sakshi1499** [comment]
@anna4j Hii! I hope you are still interested in working on the PR for this issue. For now use the 32 members that are visible to you and repeat them until the grid the completed. We will update it later with actual members as we are currently also unsure about who among the 100 members is still active or in the org.

**Comment by anna4j** [comment]
@sakshi1499 okay sure! I'll use only the visible members
