### ISSUE TITLE
Coding: Develop Footer

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#55]
## Description
As a user,
I need the following footer mock-up to be implemented,
so that I can submit any feedback or query, follow on social media, and contact open source community.

## Mocks
![Footer](https://user-images.githubusercontent.com/49720151/82147008-81cef200-986a-11ea-8570-eafc3972a10a.png)
(Only the section in the red box to be developed)
![Text-Guidelines](https://user-images.githubusercontent.com/49720151/82231468-d77acb80-994a-11ea-911d-6c2fa3286e1d.png)
(use footer text for body and small header for footer item titles)
![Screenshot (159)](https://user-images.githubusercontent.com/49720151/82237450-43f9c880-9953-11ea-9cd4-6b636698f8cf.png)
![Screenshot (160)](https://user-images.githubusercontent.com/49720151/82237453-45c38c00-9953-11ea-8cf4-cc0defd74c1c.png)
![Screenshot (161)](https://user-images.githubusercontent.com/49720151/82237455-45c38c00-9953-11ea-9374-5f210a1c7438.png)
NOTE:
Background color: Rich Black (#101820 )
Button color: Caribbean (#54BCEB)
Text color: white (#FFFFFF)
The margin between text input fields and button in the feedback form is 8pt.
[Design Link for Development](https://xd.adobe.com/view/ba1323d0-760e-4f29-4658-c83848c894ba-cc22/)
### Update [Required]
- [ ] The first input field in feedback form takes email id as input and the second field is for taking queries and feedback, and below is a submit button.
- [ ] When a user clicks on the Linkedin icon, he/she should be redirected [here](https://www.linkedin.com/company/anitab-org/)

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by annabauza** [comment]
@Sonal240 can you specify following:

background color:
font color:
button color:
button size:
button corner radius:
button text: font + size +weight + margins

Form: sizing +color + corner radius+ gutters

Top & side container margins

Icons sizes and gutters and top margins

Then the ticket will be ready.

**Comment by annabauza** [comment]
As a user,
I want to have a footer following the designs,
so I could send a feedback, follow on social media, and contact open source community.

**Comment by Sonal240** [comment]
I'm on it @annabauza...I'm adjusting  the screenshot for the same points as you have mentioned for all issues and I'll attach them in the mock

**Comment by annabauza** [comment]
@Sonal240 approved 🎉

**Comment by annabauza** [comment]
@anitab-org/coding-team ☝️

**Comment by tichnas** [comment]
Anyone working on this? If not, I would love to take this issue.

**Comment by annabauza** [comment]
no-one is working on it assigning you @tichnas

**Comment by tichnas** [comment]
Should I stick to the exact size (in pixels) given? How will we make it responsive then?

**Comment by Sonal240** [comment]
Hey @tichnas ...Try finding equivalent rem or em for  given px /pt..thanks

**Comment by tichnas** [comment]
Please take a look and let me know the changes needed.
![Screenshot from 2020-05-26 01-50-06](https://user-images.githubusercontent.com/56799401/82841372-6d869700-9ef3-11ea-8232-2f0d4a1f72ab.png)


Currently, the columns are not of the fixed-width given. Rather, each column is 33% of the total width. The layout looks pretty good on different sizes (except for mobile devices).
I have some questions to further develop the footer:
1. What should be done for mobile devices?
2. What should be the font-size of the heading of each column and the normal text?
3. Any changes on "Submit" button on hover/click?

**Comment by Sonal240** [comment]
May you please share a screenshot of the footer for the responsive screen too... 
Secondly convert given pt measurements to em  12pt ->1 em light weight  for description and 16pt->1.4em medium weight for headings 
Lastly, Form should be submitted when user clicks on submit button and once the feedback is received the form should turn blank apply necessary form validations too

**Comment by tichnas** [comment]
Sorry, I'm not able to understand what is required. Only the font-size should be in em or all the width/height?
Also, in my case 1em is showing 16px, and you said 12pt -> 1em. Now this gives 16px = 12pt (initially, I thought 1pt = 1px). If this is true, then the layout breaks even on my fully wide laptop screen.
Can you please clarify a little bit more.

This is how my original design (each column width ~33%) looks on an iPad (width: 768px):
![Screenshot from 2020-05-26 21-29-05](https://user-images.githubusercontent.com/56799401/82923267-55b51e80-9f98-11ea-85a3-7dbe8275bd7c.png)

This is the design after changing everything to em (assuming 12pt = 1em):
![Screenshot from 2020-05-26 21-28-21](https://user-images.githubusercontent.com/56799401/82923433-94e36f80-9f98-11ea-9f84-f9073849d6d2.png)

**Comment by Sonal240** [comment]
I was talking about font size that the heading is of 16pt medium, weight, and description 12pt lightweight...I was going through one website there they had cited the converted value that I had mentioned in my comment earlier...go ahead with your values
can you try 40% 20% 40% instead of 33% for all
May you share the screenshot of the footer for screen sizes below 768px like iPhone Xs or something too..thanks

**Comment by tichnas** [comment]
Thanks for explaining. 40% 20% 40% looks good on a widescreen so I did that. For smaller screens like iPads or mobiles, I have written some small media queries (for 1200px, 900px & 600px).
I think attaching screenshots for all the sizes will kind-of spam. For this, I have uploaded the footer online (https://web.iiit.ac.in/~sanchit.arora/temp/) by normal HTML & CSS. Please check the design and responsiveness from there only.

**Comment by Sonal240** [comment]
@tichnas may you fix the font size and update the link that you have shared in above comment

**Comment by snitin315** [comment]
We should follow a design system

**Comment by tichnas** [comment]
@Sonal240 The textarea was behaving differently from the other inputs for font size and weight.
To solve the issue with font-size I changed em to rem and now font size of the heading of each column is 1.4rem and that of paragraph, button & text inside the input areas is 1rem.

Now font-weight is still causing problems. I have the same weight for both the input and textarea, but still, they look different.
![Screenshot from 2020-05-27 18-22-36](https://user-images.githubusercontent.com/56799401/83021816-31b11600-a048-11ea-8ca7-971ed919de3a.png)
I was not able to find a satisfactory answer from the internet. But, we can still increase the font-weight of input to correct this problem. Please take a look from the link above, and let me know if there is some mistake on my end because of which this weird thing is happening.

@snitin315 Hi, Sorry but I'm new to OpenSource, could you please elaborate?

**Comment by Sonal240** [comment]
May you give 4pt margin to the texts in the  field, are you using Avenier font...it doesn't seem so though... I can see variation
may you please use px for font size and update the link... I would like to see how it looks, because the font and it's size looks  heavy now and I  think when components get loaded footer text might outshine it,

**Comment by tichnas** [comment]
- [x] Added padding to the texts in the field.
- [x] Changed font-size of headings to 21px and that of other text to 16px.

I didn't specify font-family explicitly so not sure which font it was using. Now I have changed the font-family to match that in the body (from index.css).

**Comment by Sonal240** [comment]
Add medium weight (bold) to heading and light weight to body

**Comment by tichnas** [comment]
The headings and body already have a weight of 500 and 300 respectively. For the email input, however, I have a weight of 400 because of the problem I described earlier.

**Comment by Sonal240** [comment]
Hey, @tichnas sorry for responding late..you don't need to cater responsiveness of the footer it's later going to be developed on react-native..it was discussed today in the session..you may submit a or if you are done..thanks

**Comment by annabauza** [comment]
@tichnas can you push your changes to you branch so I could see it?

**Comment by tichnas** [comment]
@annabauza I have pushed the changes on `footer` branch of my fork (https://github.com/tichnas/anitab-org.github.io/tree/footer). I was not aware of any conventions (of file and variable naming) therefore please suggest me the changes needed before a PR.
Also, @Sonal240 said that it need not be responsive. Should I remove the media queries or keep them as it is?

**Comment by annabauza** [comment]
We use react native not reactjs

**Comment by tichnas** [comment]
Silly me! I was not familiar with React Native and misinterpreted the issue. However, I changed it to React Native with the dimensions mentioned. Please check it here https://github.com/tichnas/anitab-org.github.io/tree/footer @annabauza .
Currently, email validation takes place by comparison with a regex. Also, the fields only show a red border on wrong/empty input.

@Sonal240 I'm extremely sorry for wasting your time by asking silly questions.

**Comment by Sonal240** [comment]
why sorry buddy.. it's ok 😊...the code looks good to me wait for @annabauza to review it... good work @tichnas

**Comment by tichnas** [comment]
Thanks, it was all possible due to your continuous help.

**Comment by annabauza** [comment]
I don't see form to be sended anywhere. Also I found this: `<TouchableHighlight onPress={null}>`, are you missing some informations @tichnas ?

**Comment by annabauza** [comment]
and you need to create the PR

**Comment by tichnas** [comment]
@annabauza Where should the form send data? Also, the null should be replaced by `            Linking.openURL('<social-link>')` along with the corresponding image. Can you please provide the social links to update them?

**Comment by Sonal240** [comment]
The LinkedIn page link is provided in the issue

**Comment by tichnas** [comment]
Yes. Currently, all the three social icons have an image of the LinkedIn logo out of which only first one redirects to LinkedIn page. Since in the mockup, there were 3 icons, I left the other two for now.

**Comment by Sonal240** [comment]
Only LinkedIn was finalized as far as I remember so I left 2 blanks... @annabauza what else can be added?? Github and medium official page links??

**Comment by Sonal240** [comment]
@sakshi1499 can you look into this part??

> Only LinkedIn was finalized as far as I remember so I left 2 blanks... @annabauza what else can be added?? Github and medium official page links??

**Comment by annabauza** [comment]
Remove blanks for now. We can always rise issue and add it. Thanks.

**Comment by tichnas** [comment]
The icons don't link anywhere. Should I remove them (I think only one icon will look awkward)?
Also, anything needs to be done on the form?

**Comment by Sonal240** [comment]
Don't remove them..leave it as it is, as Anna said we will raise an issue for it later on...You may put a pr and later on, we may give it to the QA team for testing it (form part) if required, also I saw that only e-mail is being validated..what about the suggestion/feedback box below??

**Comment by tichnas** [comment]
@Sonal240 I kept the feedback box required. Is there any other validation required like max/min characters?

**Comment by Sonal240** [comment]
Yes...look for test cases..like it should not contain spam words generate a warning by changing the border-color look 
@annabauza can ping the QA team for generating test cases ??

**Comment by tichnas** [comment]
@Sonal240 Sorry but I have no idea on how to implement that. Can you please guide? The best I can even think of is having a list of all possible spam words and check if the message contains any of them.

**Comment by Sonal240** [comment]
@tichnas I think it might be a tedious job creating a list of spam words and checking them...to execute it efficiently ML models like the one used for Gmail can be implemented..but I don't think that's our priority as of now...I think we may leave it and raise an issue later if required

@annabauza @sakshi1499 can you review the pr raised by @tichnas...thanks a ton!!!

**Comment by tichnas** [comment]
Thanks @Sonal240 @annabauza. It was a great experience contributing here. Looking forward to contributing more :)

**Comment by anna4j** [comment]
@tichnas could you please tell me how you set up the project? The way I did is causing some trouble with react-native modules required for the features I'm adding. thanks
