### ISSUE TITLE
Content - Create content for the following Contribute Page Section

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#59]
## Description
As a user,
I need a brief yet engaging content for the following section,
so that as a newcomer I get a rough idea of open source.

## Mocks
(develop content for section in red box only)
![newcomer](https://user-images.githubusercontent.com/49720151/83353260-e4e27d80-a36e-11ea-8e13-32f2a1b9b5f8.png)

[design link](https://xd.adobe.com/view/0bfde3f8-de19-4c3d-61e9-0d11752d875d-7dcc/)

### Update
- [ ] Add description for newcomer section

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2-3 hours

**Comment by sakshi1499** [comment]
Seems good @Sonal240 I think we can tag the content team :)

**Comment by Sonal240** [comment]
@anitab-org/content-team 👆

**Comment by sakshi1499** [comment]
@anitab-org/content-team Can you please work on this issue?

**Comment by foongminwong** [comment]
@sakshi1499  I'm one fo the content teams, you can assign it to me. I'm also working on this [issue](https://github.com/anitab-org/anitab-org.github.io/issues/60), which they are connected under Contribute Page section :)

**Comment by nandini45** [comment]
no issue @foongminwong .

**Comment by sakshi1499** [comment]
@foongminwong Thank you <3

**Comment by foongminwong** [comment]
Check out @archanaserver suggestion here for newcomers contribution: https://anitab-org.zulipchat.com/#narrow/stream/212722-general/topic/%28no.20topic%29/near/202613341
