### ISSUE TITLE
Create all issue templates for this repository

### ISSUE THREAD

**Issue by sidvenu** [anitab-org/anitab-org.github.io#6]
## Describe the bug/feature
We need to create issue templates for this repository.

- [ ] User Story
- [ ] New Feature
- [ ] Bug Report

## Expected behavior
1. We have an issue template as a markdown file in the repository.
1. Every time a person creates an issue, this template is auto-filled into the issue's body.

*Expected time to complete: 1 hour*

**Comment by sidvenu** [comment]
@mayburgos @annabauza I would like to work on this issue if it is approved.

**Comment by nandini45** [comment]
shouldn't we divide into sub categories(like under what section what we want to have ) or for now the  whole home page layout?
@sidvenu

**Comment by nandini45** [comment]
or for now you are focusing on the whole home page template?

**Comment by sidvenu** [comment]
@nandini45 I am not sure I understand your question correctly - I think you confused the issue template with the template of the webpage?

**Comment by mayburgos** [comment]
@sidvenu Assigning! Please include all 3 templates: User Story, New Feature, Bug Report

**Comment by mayburgos** [comment]
@nandini45 This is only templates for the repo itself (i.e. issue templates, pull request templates, guidelines, etc). The MD files that we have in all of the repos.

**Comment by mayburgos** [comment]
@sidvenu Can you please make sure to add a .github folder to put the templates in? Follow the [mentorship android .github](https://github.com/anitab-org/mentorship-android/tree/develop/.github) folder. 

Please move the code_of_conduct.md and reporting_guidelines.md files there too.

**Comment by sidvenu** [comment]
@mayburgos Will do :+1:
