### ISSUE TITLE
maintain: content folders and consistancy in naming

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#61]
All content json should be in content folder and should follow lowercase naming with underscore.

Acepted Criteria:

- [ ] Move `src/aboutUs.json` to `src/content/about_us.json`
- [ ] Move `src/homet.json` to `src/content/home.json`

**Comment by nandini45** [comment]
only the first timer can work on it?/

**Comment by siddhipandare** [comment]
Hello, Can I claim this issue? I have never contributed before and might take a little more time to create a PR if that's okay :sweat:

**Comment by Trimankaur** [comment]
Hi , I would like to work on this issue. This would be my first contribution to open source so can you please suggest me steps for getting started ?

**Comment by Trimankaur** [comment]
I have fixed the issue and created a PR ( #78 ) , waiting for review.

**Comment by mayburgos** [comment]
@Sonal240 @annabauza Please follow the first come, first serve contributing guidelines. @siddhipandare commented first and wasn't assigned.

**Comment by annabauza** [comment]
Thank you May, missed that somehow 😟

**Comment by Sonal240** [comment]
I was not following the issue and by the time I saw it @siddhipandare was working on another one... So I assigned @Trimankaur  I'll take care of it from next time thanks @mayburgos 😊

**Comment by annabauza** [comment]
@Sonal240 can we find first time for @siddhipandare ?

**Comment by Sonal240** [comment]
Are you talking about some first time issues? @annabauza

**Comment by annabauza** [comment]
Yep

**Comment by Sonal240** [comment]
I think once the homepage and events page gets finalized and the content issues are created she may choose any one section and contribute coz I saw all content issues are closed if she's interested in coding then there's one issue of About us page meet our community section

**Comment by siddhipandare** [comment]
Hello! Actually, in the content meet I had few doubts about contributing (I am a beginner at it) and one of which was "Can I start working on an issue and open PR even if I am not assigned because I saw someone do it " and send the link to this issue. I didn't know it was a mistake and against contributing guidelines 😓 </br>

I can work on any new content issues raised no problem 😅 Thank you for helping with my first PR 😄 Very sorry if there was any misunderstanding.
