### ISSUE TITLE
Design: Events Page UI Tweaks

### ISSUE THREAD

**Issue by simranaggarwal1999** [anitab-org/anitab-org.github.io#62]
### **Describe the bug**

[This design](https://xd.adobe.com/view/ef6821ef-76d9-4a96-75dd-021545d11ebc-9959/) needs the following UI Tweaks:

- [ ] Should follow Margin Guidelines

- [ ] Add a Google Calendar Screenshot for Events Calendar Component

- [ ] Add a component for Tech Talks

- [ ] Improvise Events and Highlight section (should have past, current and future event cards organized neatly, is user friendly)

**Comment by nandini45** [comment]
can you please update the issue in the correct format. and accordingly u can be assigned

**Comment by Frenzyritz13** [comment]
Me and Simran are working on this. So i will remove the available label

**Comment by Sonal240** [comment]
![EventsPageDesign-Simran Shilky](https://user-images.githubusercontent.com/49720151/85365971-008f0d00-b544-11ea-956e-8cc7805dc40e.png)

[Design Link
](https://xd.adobe.com/view/7956c9f9-f4dc-4de6-7616-c127feeed71f-0f67/)

@simranaggarwal1999 @Frenzyritz13 kindly work on the top illustration and share it thanks

**Comment by abha224** [comment]
@simranaggarwal1999 HI! I see that the issue you created does not follow the issue template. Can you pls modify the description of the issue so that it appropriately follows one of the 3 issue templates?

**Comment by Sonal240** [comment]
![EventsPageDesign-Simran Shilky](https://user-images.githubusercontent.com/49720151/86120160-6b66b800-baf1-11ea-9362-824b0bdb9da9.png)

I've updated the design with your illustration @simranaggarwal1999 
@annabauza @sakshi1499 can I make coding issues for this??

**Comment by Sonal240** [comment]
![EventsPageDesign-Simran Shilky](https://user-images.githubusercontent.com/49720151/88647191-6c383d00-d0e3-11ea-8470-633fe3320a7f.png)

I've updated the design

[Design Link](https://xd.adobe.com/view/7956c9f9-f4dc-4de6-7616-c127feeed71f-0f67/)
@nandini45 @annabauza @sakshi1499
