### ISSUE TITLE
Coding: Develop the New To Open Source Section of Contribute Page

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#63]
## Description
As a user,
I need the following section of the mockup to be developed,
so that I can add it as New To Open Source Component [here](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components).

## Mocks

(Only the section in the red box to be developed excluding navbar)

![contribute part1](https://user-images.githubusercontent.com/49720151/85372095-f6264080-b54e-11ea-9be7-a85112b9d0d7.png)

Font Size for heading NEW TO OPEN SOURCE: Header Medium(32pt) weight- Medium
Font Size for the description below: body 18pt weight- Light
Font Style- Avenir
Font Color (heading): #103B81
Font Color (Body): #103B81
Image Size:  width: 352px,  height: 562px

[Design Link For Development
](https://xd.adobe.com/view/b3ce723d-5bc6-45f5-7035-0a637d919751-c5ff/)

### Update
- [ ] Follows all the design guidelines as mentioned and is responsive enough on large screen devices

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-5 hours

**Comment by sakshi1499** [comment]
LGTM @Sonal240

**Comment by Sonal240** [comment]
Can someone from @anitab-org/coding-team kindly take this issue ...thanks

**Comment by sanchibansal340** [comment]
@Sonal240 Can I work on this issue?

**Comment by sanchibansal340** [comment]
@Sonal240 @gaurivn I just saw that this issue requires knowledge of react and react native. I am beginner in JavaScript, so can I take 2 days to resolve it?

**Comment by gaurivn** [comment]
No issues @sanchibansal340

**Comment by Sonal240** [comment]
@sanchibansal340 I've updated the margins have a look...thanks

**Comment by Sonal240** [comment]
Hey @sanchibansal340, how is it going? May you submit a pr if you are done...thanks

**Comment by sanchibansal340** [comment]
@Sonal240 I am almost done, there are just some minor styling issues and will submit it by day after tomorrow. Thank you for giving me plenty of time to work on this issue.

**Comment by abha224** [comment]
@sanchibansal340 Hey! Can you pls give us an update on your progress?

**Comment by sanchibansal340** [comment]
@abha224 I am having problem with adding spaces between the elements.

**Comment by nandini45** [comment]
@sanchibansal340  can u tell us the issue.. so that we can help you out

**Comment by anna4j** [comment]
@sanchibansal340 you can add justiftContent: "space-between" in the styles

**Comment by sanchibansal340** [comment]
@nandini45 I have been using the 'Under Construction' image as a dummy. Can you tell me how to snip the image that goes next to the 'New To Open Source' section? Also, I am having problem with the folder structure. Where should I place the folder that I created which contains the index.js file? Lastly, I am not able to view the changes that I have made? Can you please help me with that as well?

**Comment by anna4j** [comment]
@sanchibansal340 hey! So you can add the folder you created under the Components folder which can be found inside the src folder. And in order to view the changes, you're making kindly import the component ( that you've exported from your index.js ) into the App.js which is also under the src folder. Hope that helps!

**Comment by sanchibansal340** [comment]
![Screenshot (87)](https://user-images.githubusercontent.com/51092036/87528817-b06f1a80-c6ab-11ea-923f-4074b7236fe8.png)
@anna4j Yes, thank you that helped. I took a screenshot of the image from the Design Link and the cropped it. Now my image is not appearing properly. Can anyone please tell me what might be the reason for this?

**Comment by anna4j** [comment]
@sanchibansal340 okay so if you see on the rightmost side after opening the development link, there are three small icons. Select the "code" icon and then you'll actually be able to download the image by right-clicking on it instead of taking a screenshot. Hope that helps :)

**Comment by sanchibansal340** [comment]
Thank you so much @anna4j

**Comment by sanchibansal340** [comment]
@Sonal240 How do I have to change it to responsive, according to the platform, screen orientation or both?

**Comment by Sonal240** [comment]
Both @sanchibansal340  if possible...else leave it to screen size

**Comment by sanchibansal340** [comment]
@Sonal240 One last question. Do you know why flexWrap : 'wrap' might not be working because when I am decreasing the size of the browser window the image is not moving to next line?

**Comment by Sonal240** [comment]
How's it looking now? Can you share a screenshot... For both responsive and large screens ...I'll see and get back to you asap🙂

**Comment by sanchibansal340** [comment]
I don't think the responsiveness is working.

![Screenshot (88)](https://user-images.githubusercontent.com/51092036/87570284-052f8700-c6e6-11ea-9aba-d37e17f2b28c.png)
![Screenshot (89)](https://user-images.githubusercontent.com/51092036/87570367-2db78100-c6e6-11ea-8669-8a1f710d668b.png)

**Comment by Sonal240** [comment]
Have you tried changing the width to max width :(max size of screen)....or 100% of viewport

**Comment by sanchibansal340** [comment]
I will try max-width of screen but 100% of viewport is not working

**Comment by Sonal240** [comment]
Instead of width... Use max width and add max screen size value

**Comment by sanchibansal340** [comment]
@Sonal240 You can unassign me the issue. I am not able to make it responsive and I have already taken a lot of your and the coding team's time. I am sorry.

**Comment by anna4j** [comment]
@sanchibansal340 https://necolas.github.io/react-native-web/docs/?path=/docs/apis-platform--page
you could try this :)

**Comment by sanchibansal340** [comment]
Oh okay. Thank you @Sonal240 . I will try to complete it by tomorrow :)

**Comment by sanchibansal340** [comment]
@Sonal240 can you help me know why flexWrap might not be wrapping elements? I have tried to search a lot but can find any results

**Comment by Sonal240** [comment]
@sanchibansal340 I read it in stackoverflow that flexWrap needs to be applied on a container rather than a specific element...if this is not working then try using grid classes...have you tried this? Also @anna4j had shared a link... Did that help you in some way?

**Comment by Akanksha1212** [comment]
Hi @sanchibansal340 Were you able to resolve this? let us know if you need some help

**Comment by sanchibansal340** [comment]
No @Akanksha1212 I am not able to. You can unassign me. Thank you for giving me time and sorry for taking so long.

**Comment by Akanksha1212** [comment]
@sanchibansal340 it's totally if you need more time. I think you're very close in fixing it. Can you share the screenshot of the code? Or @Sonal240 @anna4j can she make a PR and then we can suggest changes?

**Comment by Sonal240** [comment]
I'm cool with anything 🙃👍

**Comment by sanchibansal340** [comment]
Okay @Akanksha1212 @Sonal240 that's so kind of you. I'll share screenshots of the code
![Screenshot (116)](https://user-images.githubusercontent.com/51092036/88384952-09852f80-cdcb-11ea-8a75-9195d099a127.png)
![Screenshot (117)](https://user-images.githubusercontent.com/51092036/88384956-0b4ef300-cdcb-11ea-8d0c-4fcb5393b42f.png)
![Screenshot (118)](https://user-images.githubusercontent.com/51092036/88384959-0be78980-cdcb-11ea-939b-63af8277f8ad.png)

**Comment by Sonal240** [comment]
We have a component for SectionHeader use that instead of using inline styling for headings...there's a typo mxWidth  line 57

**Comment by sanchibansal340** [comment]
Okay, I will do the SectionHeader thing and mxWidth might have been by mistake, I was adding and deleting things to check if any would work. Thanks for checking.

**Comment by Sonal240** [comment]
Another thing, did you try Platform.OS thing without flex?

**Comment by sanchibansal340** [comment]
No, I didn't. I will do it and get back to you in an hour.

**Comment by Sonal240** [comment]
Any updates?

**Comment by sanchibansal340** [comment]
@Sonal240 Oh sorry! No, it didn't work. i just removed all flex related items and changed the maxWidth according to Platform.OS. But the image even on full-width moved to the next line and with/ without Platform.OS or flex thing: on decreasing the screen size the width of the left column(Text) keeps decreasing but the image doesn't have any effect

**Comment by nandini45** [comment]
@sanchibansal340  any updates?

**Comment by sanchibansal340** [comment]
Hi @nandini45 I tried quite a few things but wasn't able to add responsiveness. I apologise for wasting the team's time. You can unassign me this issue.

**Comment by nandini45** [comment]
@sanchibansal340 
ok are you sure about that?
can we help you somehow?

**Comment by nandini45** [comment]
@saideepesh000  can you have a look at this issue and help her here?

**Comment by saideepesh000** [comment]
> 
> 
> > @sanchibansal340
> > ok are you sure about that?
> > can we help you somehow?
> 
> @nandini45 Yes. I will try to understand my mistake from the person who solves the issue. Thank you for your patience :)

@sanchibansal340, have a look at my PR, it may help you I think. [My Pr](https://github.com/anitab-org/anitab-org.github.io/pull/133), I used [React-Native-Reflect](https://sntx.github.io/react-native-reflect/#/?id=single-style), It is used to give responsiveness for React(Native(Web))) projects.

**Comment by sanchibansal340** [comment]
Thanks @saideepesh000 Will check it 👍🏼

**Comment by nandini45** [comment]
@sanchibansal340  do you want to continue working on it?

**Comment by sanchibansal340** [comment]
Sorry @nandini45 for not updating. I was not able to apply this.

**Comment by Aaishpra** [comment]
Hey @nandini45 can i try working on this issue if no one else is currently working on it.

**Comment by Aaishpra** [comment]
@nandini45 are we going to use cpontribute_intro.json file for the content?

**Comment by Aaishpra** [comment]
Another question should i use scaledimage or imagecontent for the image part?

**Comment by nandini45** [comment]
yes @Aaishpra
