### ISSUE TITLE
Readme should inform that we are using React Native.

### ISSUE THREAD

**Issue by annabauza** [anitab-org/anitab-org.github.io#65]
### Describe the bug
Readme file does not tell anything about framework we use

### To Reproduce
1. Go to https://github.com/anitab-org/anitab-org.github.io
2. Read about project
3. Notice React Native is not mention anywhere

### Expected behavior
It should be clear for developer which framework they should use.

**Comment by abhi0504** [comment]
I would like to work on this issue , Should I ?

**Comment by nandini45** [comment]
yeah sure i will assign it to you
@abhi0504
