### ISSUE TITLE
spelling mistake: make changes in content for home page

### ISSUE THREAD

**Issue by gaurivn** [anitab-org/anitab-org.github.io#68]
### Describe the issue
In src/home_content.json (after famous quote by Einstein-) t is not capital, and knowledge is spelt wrong.
```
"par": "2) Google Code In \nAnitaB.org has been actively participating in the Google Summer of Code in the years 2014, 2015, 2016, 2017, 2019 and is one of the most successful organizations since the very beginning. Here's what participants shared about their experience with AnitaB.org - \nVatsal Kulshrestha, former GCI 2017 participant in his Medium blog says- AnitaB.org has been a true personification of the famous quote by Einstein- ‘the only source of nowledge is EXPERIENCE’ "
```

### Expected
In src/home_content.json, make t of "the" capital (after famous quote of Einstein-) and add "k" for knowledge in the same line as shown in bold below:
```
"par": "2) Google Code In \nAnitaB.org has been actively participating in the Google Summer of Code in the years 2014, 2015, 2016, 2017, 2019 and is one of the most successful organizations since the very beginning. Here's what participants shared about their experience with AnitaB.org - \nVatsal Kulshrestha, former GCI 2017 participant in his Medium blog says- AnitaB.org has been a true personification of the famous quote by Einstein- ‘**T**he only source of **k**nowledge is EXPERIENCE’ "
```

**Comment by abhi0504** [comment]
I would like to work on it

**Comment by gaurivn** [comment]
@abhi0504 , you are already assigned to [this first timer issue](https://github.com/anitab-org/anitab-org.github.io/issues/65).

**Comment by abhi0504** [comment]
i have submitted a PR for [first timer issue](https://github.com/anitab-org/anitab-org.github.io/issues/65) can i now work on it

**Comment by gaurivn** [comment]
@abhi0504 , those who have already submitted PRs for first timer issues are not first timers anymore. Please check other issues.

**Comment by adi-001** [comment]
@gaurivn checkout PR #74

**Comment by gaurivn** [comment]
> @gaurivn checkout PR #74

Yes I saw here.
