### ISSUE TITLE
Create a Pull Request template for this repository

### ISSUE THREAD

**Issue by sidvenu** [anitab-org/anitab-org.github.io#7]
## Describe the bug/feature
We need to create a PR template for this repository.

Template attached below: 

```
### Description

Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

### Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)



### How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.


### Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged
- [ ] I have written Kotlin Docs whenever is applicable


**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules
```

## Expected behavior
1. We have a PR template as a markdown file in the repository.
1. Every time a person creates a PR, this template is auto-filled into the PR's body.

*Expected time to complete: 1 hour*

**Comment by mayburgos** [comment]
@sidvenu Thank you for the issue! This is a valid issue. If we can assign a newcomer to this issue, it'd be great. :)

**Comment by aditmehta9** [comment]
@mayburgos can I work on this?

**Comment by mayburgos** [comment]
@aditmehta9 Go ahead! I will assign you.

**Comment by mayburgos** [comment]
@aditmehta9 Oh. I just realized. Maybe wait until @sidvenu updates the folder structure. Since this template will go into the .github folder.

**Comment by sidvenu** [comment]
@mayburgos I don't think they will need to wait, since git can automatically merge such conflicts (with folder name), if any. Anyhoo, I've submitted a PR for the issue templates 😁

**Comment by mayburgos** [comment]
@sidvenu Awesome. Perfect. 

I saw but am not on my computer to look over the files. Will review once I’m at a comp.

**Comment by aditmehta9** [comment]
@mayburgos I have created a pull request, please review whenever you are free.

**Comment by annabauza** [comment]
Kotlin Docs ?

**Comment by sidvenu** [comment]
@annabauza I think @mayburgos inserted the mentorship system template for reference to @aditmehta9, not to be copied line by line.

**Comment by aditmehta9** [comment]
> 
> 
> Kotlin Docs ?


Sorry, I didn't read the whole template. It won't happen again.
