### ISSUE TITLE
Content: Create descriptions for each recent program for Programs page

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/anitab-org.github.io#72]
As a user,
I need a brief description for  About Our Recent Programs section of the Programs Page
so that as a newcomer I understand each recent program.
The About Our Recent Programs should contain the  program title , program description and  program eligibility for participants for each program regards the AnitaB.org 

**Mocks-**
![programs (2)](https://user-images.githubusercontent.com/60894542/84393668-7b3d5b80-ac19-11ea-9c51-7752815dd8b9.png)

**Acceptance criteria** : the PR must contain the following programs
- [ ] Google Summber of Code
- [ ] Outreachy 
- [ ] Hacktoberfest

**Definition of Done**
- [ ] All of the required items are completed.
- [ ]  Approval by 1 mentor.

Estimation
3 hours

**Comment by sakshi1499** [comment]
@vj-codes Can you please take out specific mocks and add their screenshot in the description instead of redirecting it to the folder? That would be really helpful.

**Comment by vj-codes** [comment]
@sakshi1499 done.Should I create a coding issue for the same?Also do you know about any other program that I missed here?

**Comment by nandini45** [comment]
i think google code in need not be there. as it is no longer active.

**Comment by vj-codes** [comment]
yeah I'll do it @nandini45

**Comment by nandini45** [comment]
can i work  on it?

**Comment by nandini45** [comment]
@annabauza  can i work on it? i know its for the content team. no one has taken it so can i?

**Comment by annabauza** [comment]
Sure!

**Comment by nandini45** [comment]
@annabauza can u tell me what does our recent program actually means? 
does it includes our programs that we conduct we organize or the program with which we are associated?

**Comment by annabauza** [comment]
@anitab-org/content-team @mayburgos can you help @nandini45 with programs?

**Comment by annabauza** [comment]
Accepted criteria tells which projects

**Comment by nandini45** [comment]
these three programs are with which we are associated . the programs like grace hopper celebrations wont be included then?

**Comment by nandini45** [comment]
@vj-codes  i am working on this issue but due to other work i couldn't update here. i will update asap

**Comment by vj-codes** [comment]
> these three programs are with which we are associated . the programs like grace hopper celebrations wont be included then?

I was aware of these 3 programs and not exactly sure about Rail Girls and GHC , but if confirmed will be included in recent programs.

> @vj-codes i am working on this issue but due to other work i couldn't update here. i will update asap

Sure:) @nandini45

**Comment by nandini45** [comment]
@vj-codes  @sakshi1499  should be include some scholarship programs also like women techmakers or else?

**Comment by nandini45** [comment]
@vj-codes 
just like google code in 
rails girls summer of code has been cancelled or closed now due to the pandemic and shortage of funding as well..

**Comment by nandini45** [comment]
@isabelcosta  https://railsgirlssummerofcode.org/about/

**Comment by siddhipandare** [comment]
> these three programs are with which we are associated . the programs like grace hopper celebrations wont be included then?

If the descriptions are needed for open-source programs only then these programs could be included:
Google Summer of Code
Outreachy 
Hacktoberfest 
Open-Source Hackday ([#outreach-research](https://anitab-org.zulipchat.com/#narrow/stream/216324-outreach-research/topic/Task.20Force.20-.20Open.20Source.20HackDay) on Zulip)
details about Hackday are in this [doc](https://docs.google.com/document/d/1HDijfrVdmIiO8CvViT_iz5V6DFEb9Qz8eVOe7hc1rnU/edit#heading=h.w7i370g71p2b)

Codeathons (I  found them on [systers website](http://systers.io/) but don't know if they are discontinued or not) 😓 
Anita's Moonshot 
EmpowerHERsummit

Also if mentor eligibility is to be included then the eligibility criteria are in the google forms in this [folder](https://drive.google.com/drive/folders/137ymeoNbnKK6OwSB9aSgRQ_LH_qvpCEE) 
😄

**Comment by sakshi1499** [comment]
@nandini45 Hii! Just saw your question. I hope you are working on it, because it has already been 10 days. Yes I agree that RGSoC has gotten cancelled and GCI has been discontinued, so Add about Open Source Hack Day, GSOC & Outreachy.

**Comment by nandini45** [comment]
@sakshi1499  i just saw the reply....
yes i am working but just needed a confirmation to submit the pr.. will do it by tomorrow then

**Comment by nandini45** [comment]
@sakshi1499  @vj-codes  l will create a PR as soon as i can. i know i said to do it the next day.. but i am caught in some college work. some sort of training is going on therefore i couldnt create a PR.. sorry for the late work

**Comment by vj-codes** [comment]
thanks for the update @nandini45
