### ISSUE TITLE
Coding: Develop a timeline of recent programs for the Programs Page

### ISSUE THREAD

**Issue by vj-codes** [anitab-org/anitab-org.github.io#73]
As a developer,
I need a recent programs timeline on Programs Page to be developed.
The timeline should follow the [Web Metrics Guide.](https://docs.google.com/document/d/1HhcXfc1qSj8aoj31psUgfdecI6zTkkzxUvueiEu4eas/edit) 

[Programs Page Mock](https://drive.google.com/drive/folders/1QSFH6e1WqJ1t--O_cQa-VS6o6zpF3xeG)
 
**Timeline -**

![programs-timeline](https://user-images.githubusercontent.com/60894542/84303850-45469b80-ab75-11ea-81ac-0d9ebcd4b005.png)

**Acceptance criteria :**
- [ ] PR must follow the Web Metrics Guide

**Definition of Done**
- [ ] All of the required items are completed.
- [ ]  Approval by 1 mentor.

Estimation
1-3 days

**Comment by adi-001** [comment]
@anitab-org/coding-team   anyone interested to take this?

**Comment by annabauza** [comment]
That one is complex one - I can take it.

**Comment by nandini45** [comment]
@annabauza  as i know you are quite busy with your open source work as well new job search.
so do u want me to make it available for the other contributors?

**Comment by B417037** [comment]
Can I take up this issue?

**Comment by nandini45** [comment]
@B417037  Someone is already working on it.
 look for a issue with available tag in it

**Comment by nandini45** [comment]
@annabauza do you want to work on it or should i make it available?

**Comment by iamkryptonite** [comment]
hey @nandini45, can I work on this ?

**Comment by nandini45** [comment]
@iamkryptonite  are you working on it?

**Comment by iamkryptonite** [comment]
Hey, I'm really sorry about this. I will try and get it done by the end of this week.

**Comment by nandini45** [comment]
ok
