### ISSUE TITLE
CODING:develop the partners section in the project page. 

### ISSUE THREAD

**Issue by nandini45** [anitab-org/anitab-org.github.io#75]
### Description
As a developer,
I need the following section of mockup to be developed,
so that I can add it in my projects page.

https://xd.adobe.com/view/e83904d0-fe4d-47c1-7762-155628f7de25-9e08/

### Mocks
![image](https://user-images.githubusercontent.com/62046625/84561379-78518080-ad69-11ea-87a8-f18f421b20dc.png)

**SIZE AND OTHER markings**
![image](https://user-images.githubusercontent.com/62046625/84561437-fada4000-ad69-11ea-8d65-eeca4cca51fb.png)

**here is a gif**
![Webp net-gifmaker (1)](https://user-images.githubusercontent.com/62046625/84563777-93c58700-ad7b-11ea-9e7a-48ed19c8e6d5.gif)

Font Size for the the heading:  35pt for partners 29pt for various types weight- medium
Font Style- Avenir
Font Color (heading): #010101
Font Color (Body): #103B81

### Acceptance Criteria
**Update [Required]**

- [x] create a hover style section of projects
- [x] Follows all the design guidelines as mentioned and is responsive enough on large screen devices.
- [x] create all the partners icons(total around 90 are there) all are mentioned in the link in both format grayscale as well as in color 

### Definition of Done

- [x]  All of the required items are completed.
- [x]  Approval by 2 mentor.

### Estimation
6-7 hours

**Comment by sakshi1499** [comment]
Looks good. We can tag coding team to start working on it.

**Comment by annabauza** [comment]
I'm happy to implement this.

**Comment by sakshi1499** [comment]
I assigned you <3 @annabauza

**Comment by nandini45** [comment]
here is the link to the drive which has all the images i have arranged all the icons according to alphabets and  placed them number wise. 5 in each row for the 2 section and 3 for the last one.
(65 for supporting, 12 for pioneering 3 for in kind) they are placed folder wise and alphabets.

**Comment by nandini45** [comment]
gray scale icons for supporting is missing i will upload it asap.

**Comment by annabauza** [comment]
@sakshi1499 I believe those values are wrong but I will fix that.

```
Font Size for the the heading: 35pt for partners 29pt for various types weight- bold
Font Style- Arial
Font Color (heading): #010101
Font Color (Body): #103B81
```

**Comment by sakshi1499** [comment]
@annabauza Can you please share the changes? I'll see if other issues have the same problem. Thank you

**Comment by nandini45** [comment]
@annabauza  you said avenir and medium for the font weight but that type of font was not available so i changed it. temporarily. i will change that and other than that is there anything else which is wrong?

**Comment by annabauza** [comment]
all good @nandini45 :)

**Comment by isabelcosta** [comment]
@annabauza @nandini45 @sakshi1499 what is supposed to be the content for this page? What is a partners in this context?
This is a mockup for Projects, right? If so, we can start thinking about the content

**Comment by annabauza** [comment]
We put things in section so there will be more content here 😊when we merge more sections.

**Comment by annabauza** [comment]
But @isabelcosta maybe partners should go under about us page?

**Comment by isabelcosta** [comment]
> We put things in section so there will be more content here 😊when we merge more sections.

Is the "Partners" section supposed to be about Partners (like in the context of a company that has partners) or Projects (like mentorship system, vms, portal)?

**Comment by nandini45** [comment]
partners here actually refer to the companies with which Anitab.org is related to.
@isabelcosta

**Comment by annabauza** [comment]
But I have made it in a way we can edit the content structure to add remove. And we can easily move it from one sub page to other or split and show on 2 subpages. I wish to merge the PR if everything looks good. There are common components there which should be reused in other sections like SectionHeader and SectionSubheader. @isabelcosta .

**Comment by isabelcosta** [comment]
I understand what you mean @annabauza @nandini45 , since this is still in the works I guess we can have it like that. I just wanted to avoid adding information that is not accurate in the open source website, that relates to external entities/companies we may not be affiliated with. It can mislead people who go to https://anitab-org.github.io/

I was just wondering if this information is not accurate. Although I also understand that this community is part of AnitaB.org 🤔 
I already pinged @mayburgos just to clarify this on zulip or here 😄
