### ISSUE TITLE
Content: Add a description for Contact Us Section of Footer

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#77]
## Description
As a developer,
I need a short description for the  contact us section,
so that I can replace the dummy text field.

## Mocks
![Footer](https://user-images.githubusercontent.com/49720151/84648702-045ad800-af23-11ea-890c-ecda31d5c0f0.png)

### Update [Required]
- [ ] The content should be consistent with the design and be clear enough so that a user can communicate effectively to the contact details provided as and when required.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by Sonal240** [comment]
@sakshi1499 can you review it??

**Comment by sakshi1499** [comment]
Yes looks good. It would be better if we cropped down the image to just footer. But otherwise great ☺️ @Sonal240

**Comment by Sonal240** [comment]
done @sakshi1499 

@anitab-org/content-team may you please take up this issue??

**Comment by siddhipandare** [comment]
Hello, I am from the content team with very little web-dev knowledge. As suggested by admins, I could write up the description in a google doc if that's okay.

**Comment by nandini45** [comment]
assigned to u @siddhipandare

**Comment by Sonal240** [comment]
I think you may create a json file and write your content that would be easy for the developer as well... If you are ok with that @siddhipandare

**Comment by siddhipandare** [comment]
@Sonal240 Can you please elaborate a little on what exactly is needed in the PR/Doc? Thank you for assigning me @nandini45

**Comment by sakshi1499** [comment]
@siddhipandare Hi! So basically you have to make a .json file and add content in it. This json file will be in src folder 
![image](https://user-images.githubusercontent.com/42520146/84666801-2a8e7100-af3f-11ea-80b5-cb583b436658.png)


You can have it in a similar format.

**Comment by Sonal240** [comment]
Thank you @sakshi1499

**Comment by siddhipandare** [comment]
@sakshi1499 Thank you! I am working on it.

**Comment by siddhipandare** [comment]
Is the content and structure okay? 
![vs](https://user-images.githubusercontent.com/50794652/84741579-e8137580-afcc-11ea-92ca-4f9ac6cbb88c.JPG)
![contactus](https://user-images.githubusercontent.com/50794652/84741652-feb9cc80-afcc-11ea-91e0-70b21dc23671.JPG)

P.S.: sorry for taking so much time and asking questions this is my first time contributing i don't want to mess up :sweat:

**Comment by Sonal240** [comment]
I'm not so good at making content so can someone from @anitab-org/content-team 
review this ...the structure looks nice though @siddhipandare

**Comment by siddhipandare** [comment]
Update: waiting for @anitab-org/content-team to review the content.

**Comment by Sonal240** [comment]
@isabelcosta @foongminwong may you review the content please!!! Thanks 😊

**Comment by isabelcosta** [comment]
@siddhipandare you can submit a PR and we can review it there :) I think it would be easier for us.

**Comment by siddhipandare** [comment]
@isabelcosta Thank you! I opened an PR. I hope I did it correctly 😓 . @sakshi1499 @Sonal240 Thank you for helping me 😄
