### ISSUE TITLE
Both package-lock.json and yarn.lock exists in the repository

### ISSUE THREAD

**Issue by sidvenu** [anitab-org/anitab-org.github.io#8]
## Describe the issue
I can see both `package-lock.json` and `yarn.lock` files in the repository.

## To Reproduce
1. Go to the [`develop`](https://github.com/anitab-org/anitab-org.github.io/tree/develop) branch.
2. See both `package-lock.json` and `yarn.lock` files in the repository.

## Expected behavior
It is a good practice to choose only one of the two lock files, and stick to it in this repository. There is a concern that the dependency trees of both the lock files may go out of sync with each other if both are being committed.

There are [limitations](https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/#limitations) in what the `yarn.lock` file can represent in a few cases of nuanced dependency trees, so including both lock files with/without effort to maintain sync with both lock files is not a recommended practice. Quoting Yarn from a [blog post](https://classic.yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/#future-plans),

> We highly recommend you to delete the package-lock.json file if you decide to use yarn in order to avoid future confusion and possible consistency issues.

## Estimation
30 minutes (after deciding what lock file to use)

**Comment by annabauza** [comment]
Approved
