### ISSUE TITLE
Content: Add description for project in Projects page

### ISSUE THREAD

**Issue by nandini45** [anitab-org/anitab-org.github.io#85]
### **DESCRIPTION**
write the description for the project heading

### **Mocks**

![image](https://user-images.githubusercontent.com/62046625/85916686-cfc71480-b870-11ea-9e8d-966f44ff89c7.png)\

### Acceptance Criteria
**Update [Required]**
- [x] projects content

**Definition of Done**

- [x]  All of the required items are completed.
- [x]  Approval by 1 mentor.

**Estimation**
3 hours

**Comment by Souvikns** [comment]
I will like to do this as my first contribution. 
I checked for content to write but couldn't find any in the content folder. I only contains: 
-  about 
- contact  
- home 

*Please specify what to write*.

**Comment by siddhipandare** [comment]
@nandini45 Hey! Can you mention a few more details about what is needed? How is this issue different from issue #47? :smile:

**Comment by nandini45** [comment]
yeah.. @siddhipandare  descriptions actually refer to the project we are working on and everything about it..
 whereas in this issue you only have to describe what is a project(definition sort) and something about Anitab,org related to it..

@Souvikns  i explained what you need to do in the above text.. if you clear about what it is and want to work on it.. i will assign it to u.. ok?

**Comment by Souvikns** [comment]
Yeah I would like to work on it.

**Comment by Souvikns** [comment]
I had started working on this, and I wanted to clarify somethings before making a pr. 
- I found the image in the mock-up but it is a paid image, I used another image instead. 
- Is this a website or are you planning for a react-native mobile app to. 

## This is what I have done so far
![image](https://user-images.githubusercontent.com/41781438/86256097-84489980-bbd5-11ea-846d-72ce48d0f598.png)

For writing the content I use [this](https://anitab.org/about-us/), let me know if I need to change or update anything.

**Comment by annabauza** [comment]
Closing due to closing PR #86

**Comment by tichnas** [comment]
@annabauza I think the PR wasn't merged so the issue still exists...

**Comment by annabauza** [comment]
Thanks @tichnas

**Comment by Yunika-Bajracharya** [comment]
Hi, I would like to work on this issue. How can I get started?

**Comment by nandini45** [comment]
Actually the content is available. We have to reshape it.
Some minor fixes are there.
If u want i can assign you the issue

**Comment by Yunika-Bajracharya** [comment]
Thank you, I would like to work on this. This is my first open-source contribution. Can you guide me on how it should be reshaped?

**Comment by nandini45** [comment]
@Yunika-Bajracharya  do u want  work on it?

**Comment by Yunika-Bajracharya** [comment]
@nandini45 yes, I would like to work on this.

**Comment by HeroicHitesh** [comment]
@nandini45 @annabauza I think this issue can be closed now as the `lorem ipsum ...` text is replaced by some content on the Projects page.
<img width="1440" alt="Screenshot 2021-03-09 at 9 36 06 AM" src="https://user-images.githubusercontent.com/37622734/110417065-e2117780-80ba-11eb-9213-7540df861ea6.png">
