### ISSUE TITLE
Content- Add a description for Events Section 

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#89]
## Description
As a developer,
I need a welcoming and friendly description for Events,
so that I can replace the default text field in the mock.

## Mocks
![events-content](https://user-images.githubusercontent.com/49720151/86528230-a38c4300-bec3-11ea-8582-44d8eb98fef5.png)

### Update [Required]
- [ ] The description should be brief yet engaging and should encourage the users to explore our events and participate in them

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6-8 hours

**Comment by Sonal240** [comment]
@sakshi1499 kindly check the issue...thanks

**Comment by sakshi1499** [comment]
LGTM @Sonal240

**Comment by anna4j** [comment]
@sakshi1499 I can work on this since I'm working on the component already :)

**Comment by abha224** [comment]
@anna4j Hey! How is the work going? Can you pls update here?

**Comment by anna4j** [comment]
@abha224 hey! so the coding part is almost done for this section, I'm working on the responsiveness right now. So I'll open PR for both content and coding part together within a day or two

**Comment by abha224** [comment]
@anna4j okay, that sounds great! :smiley:

**Comment by nandini45** [comment]
@anna4j  i will be unassigning you from this issue.

**Comment by nandini45** [comment]
@anitab-org/coding-team  can someone take up this issue?

**Comment by anna4j** [comment]
@nandini45 oh but i was going to open a PR I mentioned above a few hours ago
