### ISSUE TITLE
Coding: Develop the following Events Section

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#90]
## Description
As a developer,
I need the following section to be developed,
so that I can add it as an Events component [here](https://github.com/anitab-org/anitab-org.github.io/tree/develop/src/Components).

## Mocks
Develop the section in the red box only
![event1](https://user-images.githubusercontent.com/49720151/86531909-03dead00-bee3-11ea-8e04-ada95ba44b4c.png)

Font Size for heading EVENTS: Header Medium(32pt) weight- Medium
Font Size for the description below: body 18pt weight- Light
Font Style- Avenir
Font Color (heading): #103B81
Font Color (Body): #103B81

[Design Link for Development](https://xd.adobe.com/view/237a598d-ce4a-4fee-5642-3048a38e6a8b-554b/)

### Update [Required]
- [ ] Should follow all the margin guidelines mentioned above and should be responsive

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6-8 hours

**Comment by Sonal240** [comment]
Hey @sakshi1499, kindly review the issue..thanks

**Comment by sakshi1499** [comment]
Can you zoom in and change the screenshot because dimensions are not visible? @Sonal240

**Comment by anna4j** [comment]
@Sonal240 I can work on this I'm going to create a PR for the previous issue assigned to me, in an hour :)

**Comment by anna4j** [comment]
@Sonal240 where can I find the image that's visible in the mockup, which I'm supposed to add? thanks

**Comment by sakshi1499** [comment]
@anna4j Here is the link to the image [Link](https://www.figma.com/file/g9MmU2PP7Jhr3S8l10ciiQ/Untitled?node-id=0%3A1)

**Comment by Sonal240** [comment]
I've updated the issue as well

**Comment by sakshi1499** [comment]
@Sonal240 Not an issue 😬♥️

**Comment by anna4j** [comment]
@sakshi1499 @Sonal240  I have to include this image in the component as .png format and not .svg right? please confirm this
Also, the background isn't white as it should be as per mockup
![Untitled](https://user-images.githubusercontent.com/43845261/86592032-4d48fe00-bfb0-11ea-98bc-29acea1b8c74.png) please have a look. thanks :)

**Comment by sakshi1499** [comment]
Have you snipped it? @anna4j I think if you download it directly from figma it should come without any background and just the image we need.

**Comment by sakshi1499** [comment]
@anna4j I got it! @Sonal240 Can you change the background to white instead of grey. If you can't edit then, we'll ping Simran aggarwal to change it to white.

**Comment by Sonal240** [comment]
I don't have an access...@anna4j download the image from development link

**Comment by Sonal240** [comment]
If problem persists then we may ping her @sakshi1499

**Comment by anna4j** [comment]
@Sonal240 I've downloaded it from the development link. thanks

**Comment by nandini45** [comment]
@anna4j  i will be unassigning you from this issue too.

**Comment by nandini45** [comment]
@anitab-org/coding-team  can someone take up this issue?

**Comment by anna4j** [comment]
@anna4j but I already told @abha224 that I'm working on the responsiveness and I'll be opening a PR within a day

**Comment by anna4j** [comment]
@Sonal240 @sakshi1499 Kindly review the content for this component and let me know the changes!

**Comment by nandini45** [comment]
about us page is a different page
 how will that issue close this issue.

**Comment by anna4j** [comment]
@nandini45 I didn't update the heading of the PR. Please check the actual PR description

**Comment by nandini45** [comment]
@anna4j  have  u create one single pull request for all the three issues?

**Comment by nandini45** [comment]
i was having the issue but someone helped me out. i hope this helps u out
Before working on any issue follow these steps-
1 checkout the develop.
2 fetch the latest repo-> run git pull if upstream is set otherwise run git pull https://github.com/anitab-org/mentorship-backend.git.
3 create a new branch xyz from the develop branch git checkout -b XYZ.
4 if you are done with your changes, then add the modified files by git add <file_name> and then commit git commit -m "".
5 push your code and create a pull request.
Hope this will help you.

**Comment by Malvika18** [comment]
hello i  am a beginner , would like to contribute in this can you please guide me how to get started.

**Comment by Sonal240** [comment]
Hey @Malvika18 this issue is assigned to @anna4j and she has put a pr as well.. May you look for some other issue thanks

**Comment by nandini45** [comment]
@Malvika18  welcome to the community girl. and if u want to start contributing to this repository  look for the issue that have tag of available.. if u want to know more about this project you can checkout the zulip app.
 i ,mentioned u the link below

https://anitab-org.zulipchat.com/#narrow/stream/235478-anitab-org.2Egithub.2Eio.

**Comment by prabhat04011998** [comment]
**Hey Guys,** 
I seen that this issue is open and unassigned , can i pick up this issue if not assigned to anyone?

**Comment by Akanksha1212** [comment]
Sure @prabhat04011998. Go ahead. Looking forward to your PR. Let us know if you need any help and do update us with your progress after 3 days.

**Comment by prabhat04011998** [comment]
Sure @Akanksha1212  i'll update my status .
here is my current status , Component Implemented , alignments left.

![image](https://user-images.githubusercontent.com/28345582/100122699-b2d65200-2e9f-11eb-8792-91bae90d224e.png)

**Comment by prabhat04011998** [comment]
Hey @Akanksha1212 , 
Component done,
responsiveness checked.
i can generate the PR or any step i am missing need to follow?

**Comment by Akanksha1212** [comment]
Great! @prabhat04011998 You can create a PR now and please follow the PR guidelines especially the deployment part and share the link in PR as well.

**Comment by prabhat04011998** [comment]
Done Please Check .
I am attaching the deployed URL.
Deployment Guidelines followed.
https://prabhat04011998.github.io/anitab-org.github.io/
