### ISSUE TITLE
Content: Replace all dummy text fields in the given mock of events page

### ISSUE THREAD

**Issue by Sonal240** [anitab-org/anitab-org.github.io#92]
## Description
As a user,
I need brief yet engaging descriptions for all events displayed in cards and the heading EVENTS and HIGHLIGHTS,
so that I can walk through all of them and participate.

## Mocks
![event-con-2](https://user-images.githubusercontent.com/49720151/86560649-6fc12400-bf7c-11ea-924d-e87230ba0f6f.png)

### Update [Required]
- [ ] The description below the main heading of this section should encourage the user to check out all our events and participate in upcoming or present ones
- [ ] Should have details of all the events conducted by the organization so far.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
3-5 days

**Comment by Sonal240** [comment]
@sakshi1499 kindly review the issue thanks...

**Comment by sakshi1499** [comment]
@Sonal240 Awesome!!

**Comment by sakshi1499** [comment]
@anitab-org/content-team Please take up this issue :)

**Comment by siddhipandare** [comment]
Hey can I work on this?

**Comment by sakshi1499** [comment]
@siddhipandare Hey, sure. I'll assign you

**Comment by siddhipandare** [comment]
@sakshi1499 Thank you! 
@Sonal240  Few doubts , since the event names are not mentioned I suppose these are one day (short) events and *not* GSoC or hackathons
I found the details of AnitaB open source Events ➡️  [here](https://drive.google.com/drive/folders/1S76M1Iy1-K-pcaHbTS04-LwZ-peuP1sV)

But I don't know if these are recurring events. Are these the events you need description for? 
Also, as the event location and time is continually changing should I leave it as they are? 
What should be added in the event highlights? I am unable to understand the purpose of the small white boxes.

**Comment by Sonal240** [comment]
I think @mayburgos would be the right person to answer this...

**Comment by siddhipandare** [comment]
@anitab-org/content-team  @mayburgos  Can you help with this? 

> @sakshi1499 Thank you!
> @Sonal240 Few doubts , since the event names are not mentioned I suppose these are one day (short) events and _not_ GSoC or hackathons
> I found the details of AnitaB open source Events ➡️ [here](https://drive.google.com/drive/folders/1S76M1Iy1-K-pcaHbTS04-LwZ-peuP1sV)
> 
> But I don't know if these are recurring events. Are these the events you need description for?
> Also, as the event location and time is continually changing should I leave it as they are?
> What should be added in the event highlights? I am unable to understand the purpose of the small white boxes.

**Comment by nandini45** [comment]
@annabauza  Can you look into this issue and answer her questions?

**Comment by annabauza** [comment]
@nandini45 can we provide the json/js format like we implement under content folder?

**Comment by nandini45** [comment]
@sonal420 can u tell the purpose of these boxes.. what are these for.?
![image](https://user-images.githubusercontent.com/62046625/87248126-4cfba780-c475-11ea-8fd3-2cf6cb7d06d9.png)

**Comment by nandini45** [comment]
yes if we have to put the content of the events page then yeah sure @annabauza

**Comment by nandini45** [comment]
@siddhipandare  yes the events which you are referring to are the events that you need to mention.
As for location of the events all of them will be conducted virtually i suppose. and for the timezone i think you can mention two standard time Indian standard time, European standard time.
i think when @Sonal240  answers your questions all the question will be answered. if still any query feel free to ask.

**Comment by Sonal240** [comment]
Those boxes are for thumbnail images of events

**Comment by siddhipandare** [comment]
@nandini45  Thank you 👍 I am working on this.
 I'll keep you all posted.
 @Sonal240 I'll refer to the existing code in the content folder for the structure. 😄

**Comment by siddhipandare** [comment]
Update : I am still editing the content. Just confirming, I'll name the file as events.js which will be in src/content/events.js is that okay?

**Comment by Sonal240** [comment]
rename it as events and highlights...I think it might conflict with another file with the same name...the top description...thanks

**Comment by siddhipandare** [comment]
This is the structure of ```events_and_highlights.json``` file (In the last update I said it's a .js file, apologies)

The current structure is -
```
{
  "sections": [
    {
      "title": "Our Events and Highlights",
      "content": [
        {
          "par": ".."
        }
      ]
    },
    {
      "title": "Events",
      "content": [
        [
          {
            "Event Title": "..."
          },
          {
            "Event Date": "..."
          },
          {
            "Event Location": "..."
          },
          {
            "Event Timings": "..."
          },
          {
            "Event description": [
              {
                "par": "..."
              }
            ]
          }
        ],
        [
          {
            "Event Title": "..."
          },
          {
            "Event Date": "..."
          },
          {
            "Event Location": "..."
          },
          {
            "Event Timings": "..."
          },
          {
            "Event Description": [
              {
                "par": "..."
              }
            ]
          }
        ]
      ]
    }
  ]
}
```
I am almost done with the content. Let me know is it's okay, will open PR soon 😄

**Comment by nandini45** [comment]
@Sonal240  can u check the content and approve it.. so she can proceed further and open the PR

**Comment by Sonal240** [comment]
@siddhipandare can you add 2 more sections for event highlight(images) and know more( links to respective event website if available, or a particular section of a website)...thanks

**Comment by siddhipandare** [comment]
Okay, will do that! By add images do you mean I should add promotional flyers? For reference, in this folder ➡️ [events](https://drive.google.com/drive/folders/16BJylmGwkuIK_yn9QbFnq7y-z79i26dt) there are promotional images, **Why I contribute to open source_Twitter.png** (or **Why I contribute to open source_LinkedIn.png**). If yes, I'll add images in a new folder called events_and_highlights ➡️ src/assets/image/events_and_highlights/images..

As for the know more section, I'll direct it to ```Contact us``` section.

**Comment by Sonal240** [comment]
Instead of contact us section, we can redirect them to the specific website(eg open-source hack day). Use promotional images for online events and for rest of the events that were conducted offline try collecting onsite images if possible

**Comment by siddhipandare** [comment]
I thought 'events' are only online (virtual) guest speaker events because the description for Open Source Hackday, etc will be covered in issue #72. As for the offline events, I couldn't find any 🤔

**Comment by Sonal240** [comment]
I just gave an example for the website...I think grace hopper event etc can also be considered here

**Comment by Sonal240** [comment]
@siddhipandare kindly have a look I have updated the issue and update the pr
