### ISSUE TITLE
Improvement Of README.md File.

### ISSUE THREAD

**Issue by saideepesh000** [anitab-org/anitab-org.github.io#97]
### Description
As a developer,
While setting up the remote upstream, documentation was unclear.

The README.md file describes the following.
"When a repository is cloned, it has a default remote named origin that points to your fork on GitHub, not the original repository it was forked from. To keep track of the original repository, you should add another remote named upstream. For this project, it can be done by running the following command -

git remote add upstream https://github.com/anitab-org/anitab-org.github.io."

### Expected Result
"When a repository is cloned, it has a default remote named origin that points to your fork on GitHub, not the original repository it was forked from. To keep track of the original repository, you should add another remote named upstream. For this project, it can be done by running the following command -

**cd anitab-org.github.io**
git remote add upstream https://github.com/anitab-org/anitab-org.github.io"

### Mocks
![Screenshot (241)_LI](https://user-images.githubusercontent.com/43727167/87247209-fa6bbc80-c46f-11ea-81ca-912658253fbd.jpg)

**Comment by saideepesh000** [comment]
can I work on this, this could be my first issue.

**Comment by nandini45** [comment]
@saideepesh000  i think one such issue was created and merged 
i will mention that issue give me a minute

**Comment by nandini45** [comment]
https://github.com/anitab-org/anitab-org.github.io/issues/29

**Comment by saideepesh000** [comment]
But why it is not on the README.md file.

**Comment by nandini45** [comment]
that's a different issue the. i will ask the admin for the confirmation if she agrees you can make the changes in the readme ..meanwhile just one more thing edit the template of you issue 

@annabauza  can u tell me if this change has to be made on the readme??

**Comment by saideepesh000** [comment]
Ok

**Comment by IC1101Virgo** [comment]
Can I claim this? This can be the first github issue I might work on 😃

**Comment by nandini45** [comment]
@IC1101Virgo  actually the person who created this issue. wants to work on it and he asked it beforehand, so i cant assign it to u.
you can  look for other issues

**Comment by husainattar** [comment]
Hi, @nandini45  ma'am, we can add in the readme for synchronized the forked using repository if someone is not comfortable with git.

**Comment by nandini45** [comment]
i am a student like you.. not maam please @husainattar 
and as u approved i will assign it to the person who made it. thanks

**Comment by saideepesh000** [comment]
@nandini45, should I put this(anitab-org.github.io) above this(git remote add upstream https://github.com/anitab-org/anitab-org.github.io) line on README.md or anything else I can add.

**Comment by nandini45** [comment]
after the fork and clone in the remote you can add it with some instructions that if you forked cloned the repository , now for entering locally into the repository write this command and then you will enter into the stream and then you can work accordingly.. ok?
